/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "and assets from": "和资产来自",
    "Art by": "艺术by",
    "Bestiary": "图鉴",
    "Bigmode 2025 Game jam": "Bigmode 2025 Game jam",
    "Can you reach the summit and clear the game?": "你能到达顶峰并通关吗？",
    "Combat": "战斗",
    "End run": "结束运行",
    "Game": "游戏",
    "Gameplay and Development by": "游戏玩法和开发",
    "Hard Reset": "硬重置",
    "Home": "首页",
    "Isha": "Isha",
    "Kenney": "Kenney",
    "Lockley Labs": "Lockley实验室",
    "Made for the": "制作为了",
    "Music by": "音乐",
    "Powers": "力量",
    "Robartzy": "Robartzy",
    "Select locations on the map to travel through various areas, finding powerful items.": "在地图上选择地点，穿越不同的区域，寻找强大的道具。",
    "Start!": "开始！",
    "The Road Not Taken": "未选之路",
    "When you eventually meet your end, the gods spare you and grant you powers based on your performance\n                    that run.": "当你最终遇到你的结局时，众神会放过你，并根据你的表现赋予你力量。",
    "You are sent to explore the world by the gods, facing deadly creatures.": "你被神派去探索世界，面对致命的生物。",
    "Boots of Lightness": "轻靴",
    "Buried deep in the desert": "深埋在沙漠里",
    "Eternal Water": "永恒之水",
    "I want this to be mine...": "我希望这是我的……",
    "Illuminating a fallen hero": "照亮倒下的英雄",
    "Lantern": "灯笼",
    "Locally sourced and organic!": "本地采购和有机！",
    "Made from the silkiest silk": "由最柔滑的丝绸制成",
    "Maybe someone left one behind?": "也许有人落下了一个？",
    "Pickaxe": "镐子",
    "Ruby Necklace": "红宝石项链",
    "Silver Tiara": "银色王冠",
    "Surely I can find this in the woods": "我肯定能在树林里找到这个",
    "Torch": "火炬",
    "Visit all regions": "参观所有地区",
    "Wooden Shield": "木盾",
    "Worn by only the prettiest spirits": "只有最美丽的精灵才会穿",
    "You have not been granted this power.": "您尚未获得该力量",
    "play the game here": "在这里玩游戏",
    "If you see this page, it means that Itch messed up their URL": "如果你看到这个页面，这意味着Itch弄乱了他们的URL",
    "Please": "请",
    "Peck": "啄",
    "Bite": "咬",
    "Cabin": "舱室",
    "Damage dealt": "造成的伤害",
    "Damage taken": "受到的伤害",
    "Locations visited": "访问过的地点",
    "Monsters defeated": "击败怪物",
    "Next Run!": "下一站！",
    "Powers Gained": "获得的力量",
    "Stomp": "跺脚",
    "Chicken": "鸡",
    "Mosquito": "蚊子",
    "Bull Rush": "牛牛冲击",
    "Camel": "骆驼",
    "Owl": "猫头鹰",
    "Village": "村庄",
    "Snare": "陷阱",
    "Snake": "蛇",
    "Cactii": "嘶嘶",
    "Camp": "营地",
    "Crocodile": "鳄鱼",
    "Chomp": "咀嚼",
    "Guard": "守卫",
    "Camp Lost": "营地丢失",
    "Goblin": "哥布林",
    "Quick Attack": "快速攻击",
    "Sweep": "扫荡",
    "Giant Tree": "巨树",
    "Clearing": "清理",
    "Campfire": "营火",
    "Bushes": "灌木",
    "Spider": "蜘蛛",
    "Cow": "奶牛",
    "Crossroads": "十字路口",
    "Statue": "雕像",
    "Torch unlocked!": "火炬已解锁！",
    "Improve attack by 75%": "提高75%的攻击",
    "Goat": "山羊",
    "Bat": "蝙蝠",
    "Rock Crab": "岩蟹",
    "Dungeon": "地牢",
    "Horn Ram": "角公羊",
    "Mine": "矿洞",
    "Pickaxe unlocked!": "镐子已解锁!",
    "Pinch": "掐",
    "Screech": "尖叫",
    "Speed up combat by 50%": "战斗速度提高50%",
    "Treasure": "宝藏",
    "Slime": "史莱姆",
    "Witch": "女巫",
    "Troll": "巨魔",
    "Dragon": "龙",
    "Castle": "城堡",
    "Club Swing": "俱乐部摇摆",
    "Eternal Water unlocked!": "永恒之水已解锁！",
    "Fire Breath": "炎息",
    "Fountain": "喷泉",
    "Hex": "六角",
    "Increases health by 100%": "增加100%生命值",
    "Increases your defence by 100%": "使你的防御提高100%",
    "Maze": "迷宫",
    "Mirror": "镜子",
    "Oasis": "绿洲",
    "Splish Splash": "溅射",
    "Spring": "温泉",
    "Tower": "塔",
    "Witch": "女巫",
    "Wooden Shield unlocked!": "木盾已解锁！",
    "Haunted Tree": "百鬼树",
    "Wolf": "狼",
    "Skeleton": "骷髅",
    "Howl": "嚎叫",
    "Lantern unlocked!": "灯笼已解锁!",
    "Outpost": "前哨",
    "Speed up combat by 75%": "战斗速度提高75%",
    "Rattling Bones": "嘎嘎作响的骨头",
    "River Spirit": "河灵",
    "Giant Spider": "巨型蜘蛛",
    "": "",
    "Scorpion": "蝎子",
    "Boosts your health by 100%": "生命值提升100%",
    "Boots of Lightness unlocked!": "轻靴已解锁！",
    "Crystals": "水晶",
    "Fisherman": "渔夫",
    "Improve Travel speed by 50%": "移动速度提高50%",
    "Remains": "遗迹",
    "Ruby Necklace unlocked!": "红宝石项链已解锁！",
    "Spider Den": "蜘蛛巢穴",
    "Splash": "飞溅",
    "Sting": "刺击",
    "Monolith": "巨石",
    "Giant": "巨人",
    "Mummy": "木乃伊",
    "Free Play": "自由游戏",
    "give us a rating": "给我们一个评价",
    "if you enjoyed the game.": "如果你喜欢这个游戏。",
    "Make sure to": "一定要",
    "Pyramid": "金字塔",
    "runs and completed the game!": "运行并完成游戏！",
    "Summit": "峰顶",
    "Thank you for playing": "谢谢你的参与",
    "You have reached the summit in": "你们在年到达了峰顶",
    "Docks": "码头",
    "Silver Tiara unlocked!": "银色王冠已解锁！",
    "Increases attack by 100%": "攻击力提升100%",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "You just sort of gave up": "你就这样放弃了",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Defeat ([\d\.,]+) monster$/, '击败 $1 怪物'],
    [/^Defeat ([\d\.,]+) monsters$/, '击败 $1 怪物'],
    [/^Deal ([\d\.,]+) damage$/, '造成 $1 伤害'],
    [/^Take ([\d\.,]+) damage$/, '受到 $1 伤害'],
    [/^Visit ([\d\.,]+) different Locations$/, '走过 $1 不同的位置'],
    [/^Visit ([\d\.,]+) different Locations in the Desert$/, '在 沙漠 走过 $1 不同的位置'],
    [/^Visit ([\d\.,]+) different Locations in the Forest$/, '在 森林 走过 $1 不同的位置'],
    [/^Visit ([\d\.,]+) different Locations in the Mountains$/, '在 山地 走过 $1 不同的位置'],
    [/^Visit ([\d\.,]+) different Locations in the Riverlands$/, '在 河地 走过 $1 不同的位置'],
    [/^(.+)You were defeated\n(.+)by a Camel$/, '$1你被 骆驼 击败了'],
    [/^(.+)You were defeated\n(.+)by a Chicken$/, '$1你被 鸡 击败了'],
    [/^(.+)You were defeated\n(.+)by a Mosquito$/, '$1你被 蚊子 击败了'],
    [/^(.+)You were defeated\n(.+)by a Cow$/, '$1你被 奶牛 击败了'],
    [/^(.+)You were defeated\n(.+)by a Snake$/, '$1你被 蛇 击败了'],
    [/^(.+)You were defeated\n(.+)by a Crocodile$/, '$1你被 鳄鱼 击败了'],
    [/^(.+)You were defeated\n(.+)by a Goblin$/, '$1你被 哥布林 击败了'],
    [/^(.+)You were defeated\n(.+)by a Spider$/, '$1你被 蜘蛛 击败了'],
    [/^(.+)You were defeated\n(.+)by a Rock Crab$/, '$1你被 岩蟹 击败了'],
    [/^(.+)You were defeated\n(.+)by a Dragon$/, '$1你被 龙 击败了'],
    [/^(.+)You were defeated\n(.+)by a Troll$/, '$1你被 巨魔 击败了'],
    [/^(.+)You were defeated\n(.+)by a Witch$/, '$1你被 女巫 击败了'],
    [/^(.+)You were defeated\n(.+)by a Slime$/, '$1你被 史莱姆 击败了'],
    [/^(.+)You were defeated\n(.+)by a Giant$/, '$1你被 巨人 击败了'],
    [/^(.+)You were defeated\n(.+)by a Wolf$/, '$1你被 狼 击败了'],
    [/^(.+)You were defeated\n(.+)by a Skeleton$/, '$1你被 骷髅 击败了'],
    [/^(.+)You were defeated\n(.+)by a Goat$/, '$1你被 山羊 击败了'],
    [/^(.+)You were defeated\n(.+)by a River Spirit$/, '$1你被 河灵 击败了'],
    [/^(.+)You were defeated\n(.+)by a Giant Spider$/, '$1你被 巨型蜘蛛 击败了'],
    [/^(.+)You were defeated\n(.+)by a Mummy$/, '$1你被 木乃伊 击败了'],
    [/^(.+)You were defeated\n(.+)by a Bat$/, '$1你被 蝙蝠 击败了'],
    [/^(.+)You were defeated\n(.+)by a Giant Tree$/, '$1你被 巨树 击败了'],
    [/^(.+)You were defeated\n(.+)by a Haunted Tree$/, '$1你被 百鬼树 击败了'],
    [/^(.+)You were defeated\n(.+)by an Owl$/, '$1你被 猫头鹰 击败了'],
    [/^Lvl. ([\d\.,]+) Camel$/, '等级 $1 骆驼'],
    [/^Lvl. ([\d\.,]+) Chicken$/, '等级 $1 鸡'],
    [/^Lvl. ([\d\.,]+) Mosquito$/, '等级 $1 蚊子'],
    [/^Lvl. ([\d\.,]+) Owl$/, '等级 $1 猫头鹰'],
    [/^Lvl. ([\d\.,]+) Haunted Tree$/, '等级 $1 百鬼树'],
    [/^Lvl. ([\d\.,]+) Skeleton$/, '等级 $1 骷髅'],
    [/^Lvl. ([\d\.,]+) Wolf$/, '等级 $1 狼'],
    [/^Lvl. ([\d\.,]+) Spider$/, '等级 $1 蜘蛛'],
    [/^Lvl. ([\d\.,]+) River Spirit$/, '等级 $1 河灵'],
    [/^Lvl. ([\d\.,]+) Slime$/, '等级 $1 史莱姆'],
    [/^Lvl. ([\d\.,]+) Troll$/, '等级 $1 巨魔'],
    [/^Lvl. ([\d\.,]+) Giant Spider$/, '等级 $1 巨型蜘蛛'],
    [/^Lvl. ([\d\.,]+) Scorpion$/, '等级 $1 蝎子'],
    [/^Lvl. ([\d\.,]+) Mummy$/, '等级 $1 木乃伊'],
    [/^Lvl. ([\d\.,]+) Witch$/, '等级 $1 女巫'],
    [/^Lvl. ([\d\.,]+) Giant$/, '等级 $1 巨人'],
    [/^Lvl. ([\d\.,]+) Dragon$/, '等级 $1 龙'],
    [/^Lvl. ([\d\.,]+) Goat$/, '等级 $1 山羊'],
    [/^Lvl. ([\d\.,]+) Cow$/, '等级 $1 奶牛'],
    [/^Lvl. ([\d\.,]+) Bat$/, '等级 $1 蝙蝠'],
    [/^Lvl. ([\d\.,]+) Rock Crab$/, '等级 $1 岩蟹'],
    [/^Lvl. ([\d\.,]+) Snake$/, '等级 $1 蛇'],
    [/^Lvl. ([\d\.,]+) Goblin$/, '等级 $1 哥布林'],
    [/^Lvl. ([\d\.,]+) Crocodile$/, '等级 $1 鳄鱼'],
    [/^Lvl. ([\d\.,]+) \-\> ([\d\.]+)x$/, '等级 $1 -> $2x'],
    [/^And it only took you ([\d\.,]+) minutes$/, '这只花了你 $1 分钟'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);