//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Amulet": "护身符",
    "Hey. Have a nice day!!!": "嘿。祝你今天愉快！！",
    "Buff": "增益",
    "Combat": "战斗",
    "Equipment": "装备",
    "Level": "等级",
    "Rebirth": "重生",
    "Soul": "灵魂",
    "Tree": "技能树",
    "Stage": "关卡",
    "Ascension": "转生",
    "Close": "关闭",
    "Unlock new BUFF": "解锁新BUFF",
    "UPGRADE": "升级",
    "Extra Levels": "额外等级",
    "EQUIPMENT": "装备",
    "Chance to drop equipment:": "装备掉率:",
    "-After 10 stage all buffs become permanent. You can change them after ASCENSION or REBIRTH": "- 10关后所有增益效果变为永久效果。你可以在转生或重生后改变它们。",
    "-Reach 20 stage to gain EXP for buff.": "- 达到20关可以获得增益的经验",
    ": 33% that your DEF will be double when enemy hits you": "：33%几率当敌人击中你时，你的防御将翻倍",
    "Blacksmithing Experience": "锻造经验",
    "Max Level": "最大等级",
    "Open the slot for the ring": "解锁戒指栏位",
    "Reset to stage 1, but you will lose level, tree and equipment.": "重置到第1关，但会失去等级、树和装备。",
    "Ring Slot": "戒指栏位",
    "Unlock Amulet Slot.": "解锁护符栏位.",
    "Popup AFK": "挂机弹窗",
    "--- Why LevelUp?": "--- 什么是升级?",
    "--- Endless progress?": "--- 无限进度?",
    "AFK doesn't work in Abyss": "AFK在深渊中不起作用",
    "Hi. If you are here that means you wanna know something.": "嗨。如果你在这里，说明你想知道些什么。",
    "I think this title will make sense when you reach 700 level or when you break the reality and open the first dimension. (It's all about future content)": "我认为当你达到700级，或者当你打破现实，打开第一个维度时，这个游戏才会有意义。（这都是关于未来的内容）",
    "When you are AFK enemies are getting stronger. You can kill only 1 enemy per second. Total enemy kills based on max stage passed * 50. You can pass stages until the boss. You can avoid it when the stage boss is lower than max stage minus 15. Exp gain based on current stage and active perks from Tree, Ascension, Rebirth. Buffs and Formations don't work.": "当你在AFK的时候，敌人会变得更强大。你每秒只能击杀一个敌人。基于通过的最大关卡* 50杀死敌人的总数。你可以通过关卡直到boss。当关卡boss低于最大关卡- 15时，你可以避免它。根据当前关卡获得的经验，以及树、转生、重生的主动特权。增益和阵型无效。",
    " Slot": "栏",
    "Rewards": "奖励",
    "Description:": "介绍:",
    "HP MULT:": "生命值乘数:",
    "DMG MULT:": "伤害乘数:",
    "LOOT MULT:": "战利品乘数:",
    "BUFF - Bloot Art (P)": "BUFF - 果体艺术 (P)",
    "-As a higher stage, as a higher chance to find a soul": "-作为一个更高的关卡，作为一个找到灵魂的更高机会",
    "-Each soul gives +1 Max Level and +10% EXP.": "-每个灵魂给予 +1 最高等级和 +10% 经验。",
    "-Kill 10 to up soul gathering Tier.": "-击杀 10 敌人提升灵魂收集层级。",
    "-Kill soul to gain ascension shards 1 time": "-击杀灵魂可获得 1 次转生碎片",
    "-P - Permanent after reaching": "- P -达到后永久不变",
    "-Souls appear from 15 stage": "-灵魂从15关卡出现",
    " Base": " 基数",
    "Extra Max Level": "额外等级上限",
    "Deeper": "更深层次",
    "-2 and more curses give you extra MULT to bonus.": "-2及以上的诅咒会给你额外的乘数加成。",
    "-Bonus gives you EXP and EXP to your BUFFS.": "-奖励给你经验和你的BUFF经验。",
    "-Higher stages provide you MULT to bonus.": "-更高的关卡提供你的乘数加成。",
    "Amulet Suffix": "护身符后缀",
    "Armor Base": "护甲基数",
    "Soul Spreading": "灵魂蔓延",
    "Stage killing require scalles better": "关卡击杀要求规模更好",
    "Reset": "重置",
    " are 15% weaker": " 减弱 15%",
    "The Lord": "领主",
    "The Gift": "礼物",
    "Trap": "陷阱",
    "Through the Sky": "穿越天空",
    "Weakness": "虚弱",
    "Ascend && Rebirth": "转生 && 重生",
    "Curses": "诅咒",
    "Infinity": "无限",
    "Radiation": "辐射",
    "Stardust": "星尘",
    "Weapon": "武器",
    "Space": "空间",
    "EXP": "经验值",
    "Closed": "关闭",
    "MAX": "最大",
    "Extra Level": "额外等级",
    "] Twilight Remnant": "] 暮光余辉",
    "BUFF - Overkill (P)": "BUFF - 超杀 (P)",
    "^ - Exponent": "^ - 指数",
    "= Current Level + MIN Level": "= 当前等级 + 最低等级",
    "ApS - Attack per Second": "ApS - 攻击每秒",
    "Buffs": "BUFF",
    "Corruption": "腐败",
    "Lore": "传说",
    "Max AFK Kills = Max Stage Passed × 75.": "最大 AFK 击杀 = 通过的最大关卡 × 75.",
    "Next update 0.3: Dimension Atlas": "下一个更新0.3：维度地图集",
    "S - Can be stacked with the same effect": "S -可以堆叠，效果相同",
    "Usefull Info": "有用的信息",
    "Why LevelUp?": "什么是升级？",
    "You skip boss fights if their stage is 15 below your max stage.": "如果他们的关卡比你的最大关卡低15级，你可以跳过boss战斗。",
    "* - When you hover over it, a pop-up window appears with information": "* -当您将鼠标悬停在它上面时，会出现一个带有信息的弹出窗口",
    "Abyss": "深渊",
    "Endgame content is 700 Level (Infinity [T6])": "终局内容是700级（无限 [T6]）",
    "Endless Progress": "无尽的进度",
    "Enemies grow stronger when you are AFK. You can kill a maximum of 1 enemy per second..": "当你AFK时敌人会变得更强。你每秒最多可以杀死1个敌人。",
    "Event information is revealed when you reach that event.": "当您到达该事件时，将显示事件信息。",
    "Exp gain depends on stage and Tree, Ascension, Rebirth perks.(excluding Formation, Buffs)": "经验增益取决于关卡和树，提升，重生特权。（不包括阵型、buff）",
    "Green circle next to progress(GCNP) - activate to stop in current zone. Useful for farming. Maximum farming efficiency when you kill an enemy with one hit": "进度（GCNP）旁边的绿色圆圈-激活在当前区域停止。对开荒很有用。当你一击击杀一个敌人时，最大的开荒效率",
    "I think this title will make sense when you reach 700 level or when you break the reality and open the first dimension to find out about D-Rule": "我认为当你到达700级或者当你打破现实并打开第一个维度去发现d规则时，这款游戏才会有意义",
    "On AFK Radiation affects T3 curse chance and each mutagen Tier chance": "在AFK上，辐射影响T3诅咒的几率和每个变异层的几率",
    "Soul Booster increase The chance of soul appearence. The Power depends on Total AFK kills. Soul Booster works for only One Soul.": "灵魂助推器增加灵魂出现的几率。力量取决于总AFK击杀。灵魂助推器只对一个灵魂有效。",
    "Stats from the level are added only those that are in the range of the maximum level + minimum level *When your current Level is higher than the Maximum Level*": "当你当前的等级高于最高等级时，只有在最高等级+最低等级范围内的等级才会被添加",
    "True Max Level - Level without any effects": "真正的最大等级-没有任何效果的等级",
    "*LOOT MULT:": "*战利品乘数:",
    "] Ashen Echo": "] 苍白回响",
    "Max Level:": "最大等级:",
    "Prefix:": "前缀:",
    "Suffix:": "后缀:",
    "CRIT": "暴击",
    "CRIT DMG": "暴击伤害",
    "Every tier provides stonger enemies and high rewards": "每一层都提供更强大的敌人和更高的奖励",
    "Increased soul appear based on unspent points": "根据未消耗的点数增加灵魂数量",
    "Only Up": "只有向上",
    "Rebirth to stage 1, but you will lose level, tree, equipment, souls.": "重生到 关卡 1，但你会失去等级，树，装备，灵魂。",
    "The recover is going faster": "恢复的速度更快",
    "You reached the Limit of Max Level. Rebirth to break this Limit": "您已达到最高等级限制。重生以打破这个限制",
    "Buff Slot:": "增益栏位:",
    "Max Curses:": "最大诅咒:",
    "Collect the set to get a bonus:": "收集套装可以获得奖励：",
    "[Infinity]": "[无限]",
    "] Whispering Soul": "] 低语之魂",
    "+5% extra EXP per found soul": "每发现一个灵魂+5%额外经验",
    " power scales better per tree tier": "每个树层级的战力扩展更好",
    "Increases your level while your level is below 10% of max level (P)(S)": "当你的等级低于最高等级的10%时增加你的等级(P)(S)",
    "Stage killing scales better": "关卡击杀比例更好",
    "Your HP is full when special enemy appears": "当特殊敌人出现时，你的生命值回满",
    "Enemy EVO": "敌人进化",
    "Blood Art": "血液艺术",
    "Berserk": "狂暴",
    "Overkill": "超杀",
    "Sniper": "狙击手",
    "Abyss T2 - After complete you will be cursed by 3 new curses. Soul CAP -> 40. There are new enemies after 20 stages that drops Ascension Shards.\n  Ascension Shards now affect to enemies make them weaker.": "深渊T2 -完成后你将被3个新的诅咒。灵魂上限 -> 40。20级后会有掉落转生碎片的新敌人。转生碎片现在对敌人起作用，使他们变得更弱。",
    "= Levels + MIN Levels": "= 等级 + 最小等级",
    "MIN Levels = stats only": "最小等级 = 仅属性",
    "No EVO Power in Abyss": "深渊中没有进化力",
    "+1 MIN Level per 10 Souls [Infinity T6]": "每10个魂+1 MIN等级[无限T6]",
    "Abyss T1 - After complete you will be cursed by 3 new curses. Soul CAP -> 30. x1.3 MULT Rebirth Pts per Abyss Tier. +50% souls appear for each curse": "深渊T1 -完成后你将被3个新的诅咒。灵魂帽- bbbb30。每层深渊多点重生点数。每个诅咒增加50%的灵魂",
    "Abyss T3 - Break Rebirth Limits. Open Corruption. Unlock the Second Space Fragment": "深渊T3 -打破重生限制。开放的腐败。解锁第二个空间碎片",
    "Ascension Shards are obtained by completing stages": "转生碎片是通过完成关卡获得的",
    "At the beginning you can only have weapons of tier 3": "一开始你只能拥有3级武器",
    "Curse tiers: Green (T1), Yellow (T2), Red (T3), Purple (T4)": "诅咒等级：绿色（T1），黄色（T2），红色（T3），紫色（T4）",
    "Each 5 Rebirth Tier(10 After Tier 20) discover new possibilities of Rebirth": "每5层重生（20层后10层）发现重生的新可能性",
    "Each soul gives +1 Max Level & (+10% EXP until 40 Souls - +40 After [Infinity T6]).": "每个灵魂+1最高等级和（+10%经验，直到40个灵魂- +40后[无限T6]）。",
    "Enemy EVO scales Power(DMG & HP)[until Infinity T3] & loot by Rebirth Tier": "敌人进化按重生层比例力量（伤害和生命值）[直到无限T3]和战利品",
    "EXP & EXP Buff from Bonuses.": "从奖励中获得经验和经验Buff。",
    "Extra Bonus Multiplier = ^(1 + 0.1 * total curses + [0.2 for each curse T4])": "额外奖励乘数= ^（1 + 0.1 *总诅咒+[每个诅咒0.2 T4]）",
    "Gain Ascension Shards after stage 10.": "第10关卡后获得转生碎片",
    "Get weapons from killed monsters": "从杀死的怪物身上获得武器",
    "Higher stage = Higher Curse tier chance && less Penalty.": "更高的关卡=更高的诅咒层几率&&更少的惩罚。",
    "Increase the MAX level of perks by raising the tree tier": "通过提高树层来增加最大特权等级",
    "Minimum Tier adds a Tier to your weapon without affecting the drop chance": "最低层在不影响掉落几率的情况下为武器增加一层",
    "Potential increases stats per level": "每升一级增加属性",
    "Rebirth = Total Level ≥ Cap": "重生=总等级≥上限",
    "Rebirth Points depends on Total Level.": "重生点数取决于总等级。",
    "Reset Perks: Resets all to level 1 and refunds Points.": "重置特权：将所有技能重置为1级并退还点数。",
    "Soul appears from stage 15.": "灵魂从第15关卡出现。",
    "Soul Cap = 20 (expandable post-Abyss).": "灵魂帽= 20（深渊后可扩展）。",
    "Soul chance depends on stage + total souls.": "灵魂几率取决于关卡+总灵魂数。",
    "Soul Loot & Power depends on total souls": "灵魂战利品和力量取决于总灵魂",
    "The drop chance depends on current Stage. The next tier has a lower drop chance": "掉落几率取决于当前关卡。下一层的掉落几率更低",
    "Unlock the Amulet Suffix to upgrade the Tree Tier.": "解锁护符后缀以升级树层。",
    "Revolution": "革命",
    "Destructive Play": "破坏性玩法",
    "Contribution": "贡献",
    "Reset Infinity": "重置无限",
    "Abyss D": "深渊维度",
    "Dive into the Endless darkness to open new possibilities to escape from this Dimension. Travell to the Abyss where enemies are stronger, Level scales worse. Buff EXP are locked. Souls are disappeared.\n  Reach as max as possible when you affected first 13 curses [T4]": "潜入无尽的黑暗中，打开逃离这个维度的新可能性。前往深渊，那里的敌人更强，等级等级更差。增益经验 被锁定。灵魂消失了。当你影响前13个诅咒时，尽可能达到最大值[T4]",
    "You become The Omnipotent , but The Dimension tries to keep you from breaking the D-Rule.": "你成为了全能者，但是维度试图阻止你打破维度规则。",
    "The Dimension is trying to destroy you. Reach 700 Level while your EXP Gain & Max Level ^0.98. The Celestials succumb to D's will, becoming stronger. Corruption spreads its influence among all entities of this dimension, making them wild.": "维度想要毁灭你。达到700级，而你的经验增益和最高等级^0.98。天神们屈服于维度的意志，变得更加强大。腐败在这个维度的所有实体中蔓延，使它们变得疯狂。",
    "Reset everyting you've got(except Abyss D), but you will get Inf-Tree. Force any perk to serve you forever, but everything has its own price. Auto-Tree. Double Points gaining": "重置你所拥有的一切（除了深渊维度），但你会得到无限树。强迫任何特权永远为你服务，但每件事都有自己的价格。自动树。获得双倍点数",
    "Reach 30 stage: Level scale better based on Max Stage in Abyss D": "关卡数达到30：等级比例更好了 基于深渊维度的最大关卡数",
    "Reach 70 stage: Stages scale better based on Max Stage in Abyss D": "关卡数达到70：关卡比例更好了 基于深渊维度的最大关卡数",
    "Reach 60 stage: Stardust gain is better based on Max Stage in Abyss D": "关卡数达到60：星尘增益更好了 基于深渊维度的最大关卡数",
    "Reach 50 stage: Curse Bonus gain is better based on Max Stage in Abyss D": "关卡数达到50：诅咒加成增益更好了 基于深渊维度的最大关卡数",
    "Reach 40 stage: Corruption weakness is better based on Max Stage in Abyss D": "关卡数达到40：腐败弱点更好了 基于深渊维度的最大关卡数",
    "Reach 20 stage: High Tier Curses appear more often": "关卡数达到20：高级诅咒出现的频率更高",
    "UNLOCK 5 SPECIAL PERKS IN ASCENSION": "在转生中解锁5个特殊特权",
    "Alpha Burst": "阿尔法爆发",
    "Genetic Overload": "基因超载",
    "Irradiated Presence": "辐照存在",
    "Ionizer": "电离器",
    "Mutation Vortex": "突变漩涡",
    "Nuclear Resilience": "核复原力",
    "Radionite": "放射性核素",
    "SOULS HAVE NO LONGER CAP": "灵魂不再有上限",
    "REBUILD REBIRTH SYSTEM THAT ALLOWS YOU TO SPEND MUTAGEN TO UP YOUR POTENTIAL": "重建重生系统，允许你使用突变原来提高你的潜能",
    "Gamma Breakthrough": "伽马突破",
    "Crystallized Genome": "结晶基因组",
    "+25% DMG, HP, DEF while you are in Space Fight": "在太空战中增加25%的伤害，生命值， 防御",
    "Accelerated Mutation": "加速突变",
    "Astral Harvest": "星体收获",
    "TIER-R": "层级-R",
    "Select equipment to enhance its power.": "选择装备，强化装备的战力",
    "Celestial Overdrive": "天体超速",
    "Corrupted Insight": "腐败洞察力",
    "Click to activate/deactivate radiation perk. You can choose only one perk.": "点击激活/停用辐射特权。你只能选择一种特权。",
    "Veilbreaker": "破面纱者",
    "Stage scalles better:": "关卡规模更好：",
    "Rebirth Shards Gain:": "重生碎片增益:",
    "♻️ Auto Rebirth": "♻️ 自动重生",
    "🌌 Auto Ascension": "自动转生",
    "Ascension Auto-Buyer": "转生自动购买者",
    "Click to": "点击以",
    "D-Soul": "维度灵魂",
    "Enter": "进入",
    "Enter the Dimension where souls have 100% appearence, but they are stronger than usual souls. Soul Loot scales better.": "进入灵魂100%显现的维度，但他们比一般的灵魂更强大。灵魂战利品的规模更大。",
    "Min Stage:": "最小关卡:",
    "Min Shards:": "最小碎片:",
    "Stage +:": "关卡 +:",
    "Stage to Stop:": "停止关卡:",
    "The Dimension": "维度",
    "Reach Stage 80: Open D-Atlas": "到达第80关：打开维度地图集",
    "Min Rebirth Pts:": "最小重生点数:",
    "Min Level(100+):": "最小等级(100+):",
    "Level +:": "等级 +:",
    "Click to leave or complete Abyss": "点击离开或完成深渊",
    "Off/On GCNP after Ascension/Rebirth/Infinity": "在转生/重生/无限 后 关闭/打开 GCNP",
    "Stop Until Kills:": "停止直到杀死：",
    "Singularity": "奇点",
    "Stats": "统计",
    "Dimension": "维度",
    "Auto": "自动",
    "Next update 0.4: ?": "下一个更新0.4:？",
    "Upgrade All": "升级全部",
    "The Dimension is trying to destroy you. Reach Total Level 700 while your EXP Gain & Max Level ^0.84. The Celestials succumb to D's will, becoming stronger. Corruption spreads its influence among all entities of this dimension, making them wild.": "维度想要毁灭你。当你的经验增益和最高等级^0.84时，总等级达到700级。天神们屈服于维度的意志，变得更加强大。腐败在这个维度的所有实体中蔓延，使它们变得疯狂。",
    "[You are here now]": "[你现在在这里]",
    "🌍 main": "🌍 主要",
    "Reward:": "奖励:",
    "Special Reward:": "特殊奖励:",
    "The cost of TIER-INF and TIER-S scale better": "无限层级和层级-S的成本比例更好",
    "This is your main dimension. You are powerful enough to move between other dimensions.": "这是你的主要维度。你有足够的力量在其他维度之间移动。",
    "You will be able to accumulate time and spend it on AFK": "你将能够积累时间，并把它花在AFK上",
    "*EQUIPMENT": "*装备",
    "Reset everyting you've got(except Abyss D). Complete to open Singularity [T1]": "重置你所拥有的一切（除了深渊维度）。通关后可开启奇点[T1]",
    "Reach 60 stage: Stardust drop is better based on Max Stage in Abyss D": "达到关卡60：星尘掉落更好，基于深渊维度的最大关卡",
    "Reach Stage 20: High Tier Curses appear more often": "达到关卡20：高层级诅咒出现的频率更高",
    "Reach Stage 30: Level scales based on Max Stage in Abyss D": "达到关卡30：根据深渊维度的最大关卡进行等级调整",
    "Reach Stage 40: Corruption weakness is based on Max Stage in Abyss D": "达到关卡40：腐化虚弱基于深渊维度的最大关卡",
    "Reach Stage 50: Curse Bonus boost is based on Max Stage in Abyss D": "达到关卡50：诅咒奖励提升基于深渊维度的最大关卡",
    "Reach Stage 70: Stage requirement scales better based on Max Stage in Abyss D": "达到关卡70：在深渊维度中，关卡要求基于最大关卡进行了更好的比例",
    "Recovery from death is faster": "从死亡中恢复得更快",
    "Stage requirement scales better": "关卡需求比例更好",
    "The chance of souls appearing depends on the unspent points": "灵魂出现的几率取决于未使用的点数",
    "All dead bosses give you +1 MIN LEVEL and +2 MAX LEVEL": "所有死去的boss给你+1最小等级和+2最大等级",
    "TIER-INF": "无限层",
    "Unlock a slot for the ring": "解锁戒指插槽",
    "+1% EXP, Equipment Chance, BUFF EXP, Ascension Shards, Rebirth Pts, Curse Bonus, Mutagens, Stardust": "+1%经验，装备几率，BUFF经验，转生碎片，重生点数，诅咒加成，诱变剂，星尘",
    "Damage Reduction": "伤害减免",
    "Endless Levels": "无尽等级",
    "Enemies weakness based on Corruption weakness [0.55]. Also works in The Abyss": "敌人的弱点基于腐蚀的弱点[0.55]。在深渊中同样有效",
    "HP Reduction": "生命值降低",
    "Loot Increase": "战利品增加",
    "] Abyssal Murmur": "] 深渊杂音",
    "The Distance": "距离",
    "Celestials dont see you": "天体不见你",
    "Space Power": "空间之力",
    " weakness:": " 虚弱:",
    "Equipment Chance:": "装备几率:",
    "HP:": "生命值:",
    "Stage scales better:": "关卡比例更好:",
    "Corruption weakness:": "腐败虚弱:",
    "Level scales better:": "等级比例更好:",
    "Ascension Shards Gain:": "转生碎片增益:",
    "Damage:": "伤害:",
    "Exp Gain:": "经验增益:",
    "Buff Exp Gain:": "增益经验增益:",
    "Abyss weakness:": "深渊虚弱:",
    "Reach E stage in Abyss D": "在深渊维度达到E关卡",
    "🧬 Radiation Perks": "🧬 辐射特权",
    "CORRUPTION IS WEAKER BY 0.01 PER KILLED BOSSES UNTIL YOUR MAX STAGE": "每杀死一个boss，腐败会降低0.01，直到你的最大关卡",
    "Mirror of the Infinity(%)": "无限之镜（%）",
    "Defense:": "防御:",
    "EXP Gain:": "经验增益:",
    "Extra Equipment Tier": "额外装备层级",
    "Infinity Bonuses": "无限加成",
    "90% of charges return to The next enemy": "90%的能量返回给下一个敌人",
    "Complete Dimension withouth Equipment. You start with Infinity [T5]": "不使用装备完成次元从无限开始[T5]",
    "Destroy 200 Mirror of The Infinity": "摧毁200个无限之镜",
    "Each attack has 5% to Stun the Enemy for 0.5s": "每次攻击有5%的几率使敌人昏迷0.5s",
    "Enhance Space Ring E times": "增加空间环E的次数",
    "Enter a dimension where enemies become stronger due to gravity. After stage 20, your damage becomes weaker": "进入一个敌人因重力而变得更强大的维度。在第20关卡之后，你的伤害会变弱",
    "Enter the Dimension where Bosses are stronger. They realized the curses. You start with Infinity [T14]": "进入boss更强大的维度。他们意识到了诅咒。你从无限[T14]开始",
    "Enter The Dimension where gravity has destroyed The World Line. Your possible Stage is 20": "进入次元，重力摧毁了世界线。你可能的关卡是20",
    "Enter the Dimension where The Ascension does not exist.": "进入不存在扬升的维度。",
    "Enter the Dimension where The requirements for the Stage are much worse. \n        Enemies become stronger depending on the number of kills in the zone": "进入维度时，关卡的需求要差得多。敌人变得更强取决于在区域内杀死的数量",
    "Enter the Dimension where The Tree does not exist. You start with Infinity [T10]": "进入“树”不存在的维度。你从无限[T10]开始",
    "Enter the Dimension where your HP and DEF - 1": "进入你的HP和DEF - 1所在的维度",
    "Enter the Dimension where your Max Level no longer Limits. Reach level as max as possible. You start with Infintity [T10]": "进入你的最高等级不再限制的维度。尽可能达到最高等级。从无限[T10]开始",
    "Exp boost 1.00 - \n  Max Level MULT 1.00 - \n  MIN Level 0": "经验加成1.00 - \n最高等级乘数 1.00 - \n最低等级0",
    "If you die, the enemy gains a Weakness charge of 1% per Infinity [Max - 90]": "如果你死亡，敌人每无限次获得1%的虚弱充能[最大 - 90]",
    "Infinity Tree Perks scale slightly better in value": "无限树特权在价值上稍微好一点",
    "Minus Tier of Requirement to Awaken per Singularity Tier": "减去每层奇点唤醒的要求",
    "Open new Dimensions and Dimension Shards": "开放新的维度和维度碎片",
    "Reach Level 1500 to get a Bonus to Infinite EXP in this Dimension by 1.75": "达到1500级可以获得1.75的这个维度的无限经验奖励",
    "You can move between Stages": "你可以在不同的关卡之间移动",
    "You will be able to enter this dimension once you have completed Infinity [T12] in the previous one and Infinity [T15] in the main one": "你们将能够进入这个维度，一旦你们完成了前一个维度的无限（T12）和主维度的无限（T15）",
    "You will be able to enter this dimension once you have completed Infinity [T5] in the previous one.": "你们将能够进入这个维度，一旦你们在前一个维度中完成了无限[T5]。",
    "Do you realize how powerful you are? Traveling between Dimensions, destroying Galaxies and Celestials. \n    But what you may not know is that D-Rule is watching you, and when you are weak enough, he will destroy you, because only one can be the Chosen One.\n     What is it that makes you want to be stronger every time, and break down every wall that stands in your way. \n     Ask me when you find me between all these dimensions.": "你知道你有多强大吗？穿梭于不同维度之间，摧毁星系和天界。\n但你可能不知道的是，维度规则正在监视你，当你足够虚弱时，他会摧毁你，因为只有一个人可以成为救世之子。是什么让你每次都想要变得更强大，冲破挡在你面前的每一堵墙？问我，你什么时候能在这些维度之间找到我。",
    "Endgame content is The Dimension [DD-zΘaYY]": "终局内容是维度[DD-zΘaYY]",
    "Level requirement scales better: You will need fewer EXP to advance to the next Level": "等级要求更好：你将需要更少的经验，以推进到下一个级别",
    "Level+: Add Value to *Min Level* when you Level is *Min Level*": "等级+：当你的等级是*最低等级时，增加值到*最低等级*",
    "Stage requirement scales better: You will need fewer kills to advance to the next Stage": "关卡要求比例更好：你将需要更少的杀戮来进入下一个关卡",
    "Stage+: Add Value to *Stage to Stop* when your current Stage is *Stage to Stop*.": "关卡+：当你当前的关卡是*关卡停止*时，增加价值到*关卡停止*。",
    "Unlock *Auto-Ascension* after reaching Infinity [T2]": "到达无限后解锁*自动转生* [T2]",
    "Unlock *Auto-Rebirth* after reaching Infinity [T3]": "到达无限后解锁*自动重生* [T3]",
    "Unlock *Stop at Stage* after reaching Infinity [T1]": "到达无限（T1）后，解锁*停止在关卡*",
    "T2]: Reset everyting you've got(except Abyss D), but you will get Ascend Permission. You have 5 Infinity Ascension Perks to serve you forever even after Infinity Reset. Extra skip stages until +25% Max Stage (S). You can get Shards from Bosses. Auto-Ascension": "T2]:重置你你有(深渊D除外),但你会得到转生的许可。你有5个无限转生特权，即使在无限重置后也会永远为你服务。额外跳过关卡，直到+25%最大关卡（秒）。你可以从boss那里得到碎片。自动转生",
    "Complete The Dimension [K7-D4n] to get the way to move between Stages. \n      Ravage the space-time continuum to travel to any possible point in the universe. But everything has its price. \n      During the journey, enemies will become 4 times stronger, over time their strength will return to normal. \n      Skipping stages and receiving ascension shards is blocked until the next ascension, rebirth etc.": "完成次元[K7-D4n]可以获得在不同关卡间移动的方法。破坏时空连续体，旅行到宇宙中任何可能的点。但凡事都有代价。在旅程中，敌人将变得4倍强大，随着时间的推移，他们的力量将恢复正常。跳过关卡和接收提升碎片被阻止，直到下一次提升，重生等。",
    "Reward: Complete the singularity to obtain 1.05 MULT IP, +25 singularity levels. Overkill [T4], +2% to skip stage per Singularity Tier (S), level up while your level is below 2% of Max Level per Singularity Tier (S).": "奖励：完成奇点获得1.05乘数 无限点数， +25奇点等级。超杀[T4]，每层奇点(S) +2%跳过关卡，当你的等级低于每层奇点(S)最大等级的2%时升级。",
    "ASCENSION": "转生",
    "REBIRTH": "重生",
    "T1]: Reset everyting you've got(except Abyss D), but you will get Inf-Tree. Force any perk to serve you forever, but everything has its own price. Auto-Tree. Double Points gaining. Auto-Stage": "T1]:重置你你有(深渊D除外),但你会得到无限树。强迫任何特权永远为你服务，但每件事都有自己的价格。自动树。获得双倍点数。自动关卡",
    "T4]: Reset everyting you've got(except Abyss D), but you will get Gamma Learning. Gain mutagens as if you have mutagen [T5]. Increase MAX Levels. Danger System scalles better. Danger System opens new Inf-Enemy": "T4]：重置你已经得到的一切（除了深渊D），但你会得到伽玛学习。获得诱变剂，就像你有诱变剂[T5]。增加最大等级。危险系统比例更好。危险系统打开了新的敌人",
    "T6]: Reset everyting you've got(except Abyss D), but you will get Thirst for Souls . D-Soul gives you a 100% chance to meet a soul, but its power will be limitless. Every Soul Tier gives you +1 MIN Level. EXP CAP SOULS - +40": "[T6]：重置除深渊D以外的所有物品，但会获得灵魂渴求。D-灵魂让你有100%的机会遇见灵魂，但它的力量是无限的。每一层灵魂给你+1分等级。经验上限灵魂- +40",
    "10: Souls": "10: 灵魂",
    "20: Ascension Souls": "20: 转生灵魂",
    "40: Rebirth Souls": "40: 重生灵魂",
    " gain = ∑(mutations)^2.5 * Mult.": " 增益 = ∑(突变)^2.5 * 乘数.",
    " = no limit.": " = 无上限.",
    "- The ability to kill an enemy without a fight. The enemy does not drop loot.": "-不战而杀的能力。敌人不会掉落战利品。",
    "After stage 10 all Buffs become permanent(+10 Stages for each Abyss Tier). You can change them after": "10级后，所有的buff变成永久的（每层深渊+10级）。你可以之后再换",
    "Appears after Abyss T3.": "出现在深渊T3之后。",
    "Auto - Reproduces combat without fighting. Suitable for fighting weak opponents. [Infinity T5]": "自动重现没有战斗的战斗。适合打弱对手。(无穷T5)",
    "Bonus [Extra Multiplier] = ^(1 + 0.05 * total curses + [0.1 for each curse T4])": "加成[额外乘数]= ^（1 + 0.05 *总诅咒+[每诅咒0.1次]）",
    "Bonus [Penalty]: 0.23": "加成[惩罚]:0.23",
    "Challenge: Enter the singularity, where gravity devours space, opponents under the influence of gravity destroy galaxies and your level is on the verge of destruction.": "挑战：进入奇点，重力吞噬空间，对手在重力的影响下摧毁星系，你的关卡处于毁灭的边缘。",
    "Corruption reduces Max Level × 0.1 after 300 Max Level.": "腐蚀降低最大等级× 0.1后，300最大等级。",
    "Danger ↑ = special enemy chance ↑ + strength ↑.": "危险↑=特殊敌人几率↑+力量↑。",
    "Danger doesnt work in Abyss": "危险在深渊中不起作用",
    "Danger Levels:": "危险等级:",
    "Double Check - If the first attempt is false, the check is repeated.": "双重检查-如果第一次尝试是错误的，重复检查。",
    "Each dimension has a reward for each Infinity completed and a special reward for reaching the maximum Infinity in a certain dimension.": "每个维度都有完成无限的奖励，在某个维度达到最大无限的奖励。",
    "Each Infinity provides rebuild mechanic, but everything is reset(except Abyss D)": "每个无限提供重建机制，但一切都是重置的（除了深渊D）。",
    "Higher stage = Higher Curse tier chance and less Penalty.": "更高的关卡=更高的诅咒层几率和更少的惩罚。",
    "Hold the button to upgrade quickly": "按住此键快速升级",
    "In dimensions that are weakly imbued with the D-Rule, the maximum possible stage in the Abyss is 100": "在弱d规则的维度中，深渊的最大可能关卡是100",
    "Infinity Bonuses depends on IP": "无限奖励取决于无限点数",
    "Infinity Discoveries:": "无限的发现:",
    "Kill a monster with a certain danger to find the boss": "杀死一个有一定危险的怪物来找到boss",
    "MAX available BUFF Tier - 3.": "最大可用BUFF 3级。",
    "Once you reach Level 700, you will automatically advance to the next Tier. Your power will make the transition easier.": "一旦你达到700级，你将自动进入下一层。你的力量会让过渡更容易。",
    "Reach stage 20 to gain BUFF": "达到20级获得BUFF",
    "s can mutate Curse [T3] to [T4].": "可以将诅咒[T3]突变为[T4]。",
    "Singularity [T0]": "奇点(T0)",
    "Singularity levels: increase the threshold after Max Level 700. After Level 700 your stats are getting double.": "奇点等级：在最高等级700后增加阈值。在700级之后，你的属性会加倍。",
    "Stages for mutagens finding: T1-30, T2-35, T3-40, T4-45": "突变发现关卡：T1-30， T2-35, T3-40, T4-45",
    "T(x+1) mutagen needs T(x) success.": "T（x+1）诱变剂需要T(x)成功。",
    "T3]: Reset everyting you've got(except Abyss D), but you will get Integration of Rebirth. Your Rebirth Tier are unlimmited. Enemy Power equals to 1. Auto-Rebirth": "重置你所拥有的一切（除了深渊D），但你会得到重生的整合。你的重生层是无限的。敌人的力量等于1。自动重生",
    "T5]: Reset everyting you've got(except Abyss D), but you will get Expansion of Space. Unlock Space [T5]. x2 stardust. Auto-Fight": "重置你所拥有的一切（除了深渊D），但你将获得空间扩展。解锁空间[T5]。x2星尘。自动战斗",
    "T7]: Reset everyting you've got(except Abyss D). Complete to open Singularity [T0]": "重置你所拥有的一切（除了深渊D）。完成打开奇点[T0]",
    "T8]: Reset everyting you've got(except Abyss D). Complete to open Singularity [T1]": "重置你所拥有的一切（除了深渊D）。完成打开奇点[T1]",
    "Weaken it to recover power.": "削弱它以恢复力量。",
    "You can get EXP Mult and EXP Buff from Bonuses.": "你可以从奖励中获得经验组合和经验Buff。",
    "You can reset the influence of Infinity in the settings if you are not strong enough to overcome this challenge.": "如果你不够强大，无法克服这个挑战，你可以在设置中重置无限的影响。",
    "∑ Bonuses": "∑ 加成",
    "Max": "最大",
    "HP": "生命值",
    "HP MULT": "生命值乘数",
    "IP MULT": "无限点数乘数",
    "Damage MULT": "伤害乘数",
    "HP Total": "总计生命值",
    "IP Total": "总计无限点数",
    "Damage Total": "总计伤害",
    "IP": "无限点数",
    "MAX Danger": "危险上限",
    "Defense": "防御",
    "DEF": "防御",
    "Extra DEF": "额外防御",
    "Danger": "危险",
    "Damage": "伤害",
    "Amulets": "护身符",
    "Base": "基础",
    "base": "基础",
    "Crit DMG": "暴击伤害",
    "Crit Chance": "暴击几率",
    "Curse": "诅咒",
    "Curse [Bonus]": "诅咒 [加成]",
    "Total": "总计",
    "Total [^]": "总计 [^]",
    "Total Pts": "总计点数",
    "Total DEF": "总计防御",
    " [Enhances]": " [强化]",
    " [Loot]": " [战利品]",
    "Boss [Loot]": "Boss [战利品]",
    " [Prefix]": " [前缀]",
    " [Suffix]": " [后缀]",
    " [Tier]": " [层级]",
    "Infinity Challenges": "无限挑战",
    "Extra Bonus [^]": "额外加成 [^]",
    "Equipment Drop Chance": "装备掉率",
    "DROPPED SWORD": "掉落的 剑",
    "DROPPED RING": "掉落的 戒指",
    "DROPPED BOOTS": "掉落的 靴子",
    "DROPPED BODY": "掉落的 身体",
    "DROPPED Mult": "掉落的 乘数",
    "MIN SWORD": "最小 剑",
    "MIN RING": "最小 戒指",
    "MIN BOOTS": "最小 靴子",
    "MIN BODY": "最小 身体",
    "MIN Level": "最小 等级",
    "Max Level MULT": "最大等级乘数",
    "Penalty [^]": "惩罚 [^]",
    "Bonus [Penalty]": "加成 [惩罚]",
    "Potential": "潜能",
    "Rebirth Soul": "重生灵魂",
    "Rebirth Pts": "重生点数",
    "Rebirth Mult": "重生乘数",
    "Rebirth Tier": "重生层级",
    "Rebirth [Tier]": "重生 [层级]",
    "Rebirth [Pts]": "重生 [点数]",
    "Rebirth [Loot]": "重生 [战利品]",
    "Soul [Loot]": "灵魂 [战利品]",
    "Soul [Tier]": "灵魂 [层级]",
    "Tree [T6]": "树 [T6]",
    "Tree [Infinity]": "树 [无限]",
    "Tree [Extra Level]": "树 [额外等级]",
    "Tree [Radiation]": "树 [辐射]",
    "Tree [Wisdom]": "树 [智慧]",
    "Ascension Shards after Ascension": "转生后转生碎片",
    "Ascension Soul": "转生灵魂",
    "Ascension [Loot]": "转生 [战利品]",
    "Ascension [Destructive Play]": "转生 [破坏性游戏]",
    "Ascension [Singularity Seed]": "转生 [奇点种子]",
    "Ascension [Void Hazard]": "转生 [虚空危险]",
    "Ascension [Endless Levels]": "转生 [无尽的等级]",
    "Ascension Soul [Loot]": "转生灵魂 [战利品]",
    "Ascension Shards": "转生碎片",
    "Base Drop Chance": "基础掉率",
    "Base [Stage 25]": "基础 [关卡 25]",
    "Base [Curse Bonuses]": "基础 [诅咒加成]",
    "Equipment [Set]": "装备 [套装]",
    "Equipment [Enhances]": "装备 [强化]",
    "Space [Bosses]": "空间 [Boss]",
    "Abyss [Tier]": "深渊 [层级]",
    "Abyss [Penalty]": "深渊 [惩罚]",
    "Amount of Mutations": "突变数量",
    "Ascension [Astral Harvest]": "转生[星光收割]",
    "Ascension [Blacksmithing Experience]": "转生[锻造经验]",
    "Ascension [Celestial Overdrive]": "转生[天体超速]",
    "Ascension [Corrupted Amplification]": "转生[腐化放大]",
    "Awakened Tier Requirements": "觉醒层级要求",
    "base: Ascension [Rebirth Echo]": "基础：转生[重生回声]",
    "Curse [Cursed Shield]": "诅咒 [诅咒之盾]",
    "Mirror of the Infinity": "无限之镜",
    "Penalty Reduction": "减少惩罚",
    "True Max Level Requirements [Infinity T0]": "真实最高等级要求[无限 T0]",
    "🌐 Dimension:": "🌐 维度:",
    "🕐 Time:": "🕐 时间:",
    "Exp/min:": "经验值/分钟:",
    "Buff Exp/min:": "Buff 经验值/分钟:",
    "Tier:": "层级:",
    "Creatures": "生物",
    "Average Loot": "平均战利品",
    "After complete you will be cursed by 3 new curses. Soul CAP -> 30. x1.3 MULT Rebirth Pts per Abyss Tier. +50% souls appear for each curse": "完成后，你将被3个新诅咒诅咒。灵魂上限 ->30.。每层深渊增加1.3x重生。每个诅咒增加50%的灵魂",
    "You reached MAX Souls. Travell to the Abyss where enemies are stronger, Level scales worse. Buff EXP are locked. Souls are disappeared. \n  Reach Stage 20 when you affected first 7 curses [T1]": "你到达了MAX Souls。前往深渊，那里的敌人更强，等级等级更差。Buff经验未解锁灵魂都消失了。当你到达第20关卡时，影响前7个诅咒[T1]",
    "Note:": "注意:",
    "You will not be able to change the buff after Stage 10. For more information, click on [ℹ️].": "在第10关卡之后，你将无法更改buff。更多信息，请点击[ℹ️]。",
    "] Graveborn Flicker": "] 墓碑闪烁",
    " are getting weaker in Soul-D": " 变得越来越弱在 灵魂维度",
    "Reward: Buff EXP Boost -": "奖励: Buff 经验提升 -",
    "Enter the Dimension": "进入维度",
    "Buff EXP upgrades all Buffs": "Buff 经验升级全部 Buff",
    "Singularity Pts": "奇点点数",
    "Unlock new special enemies": "解锁新的特殊敌人",
    "INF Bonus [Damage] scales better": "无限奖励 [伤害] 比例更好",
    "Requirements for Dimension Shards are better": "维度碎片的要求更好",
    "Get double DMG in Singularity challenge": "在奇点挑战中获得双倍伤害",
    "Min Level provides double stats": "最低等级提供双重属性",
    "Reach Level 2000 to unclock new Infinity Goal": "达到2000级解锁新的无限目标",
    "Enter the dimension where you are under danger 300 at the time. Next Infinity Increase Danger by 30. Danger Power gets worse. Danger does not effect a chance of special enemies appearing. You start with Infinity [T10]": "进入你现在处于危险300的维度。下一个无限增加30点危险。危险力量越来越糟。危险不会影响特殊敌人出现的几率。你从无限[T10]开始",
    "Enter the Soul Dimension. You start with Infinity [T10]": "进入灵魂维度。你从无限[T10]开始",
    "Open Dimension Shards. See Ascension in the main Dimension": "开放维度碎片。参见主维度的转生",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "ApS": "ApS",
    "⭐ Star Forge": "⭐ 星辰锻造",
    "AFK": "AFK",
    "☠️ *Curses": "☠️ *诅咒",
    "D-Atlas": "维度维度地图集",
    "🧝 *Hero": "🧝 *英雄",
    "🛡️ Cursed Shield": "🛡️ 诅咒护盾",
    "🤺 Acrobatic": "🤺 杂技",
    "💉 Active Blood": "💉 活血",
    "💢 Accurate Blow": "💢 精准打击",
    "🔮 Amulets": "🔮 护身符",
    "💫 Stun": "💫 眩晕",
    "⚙️ Penetration": "⚙️ 穿透",
    "🌪️ Fast Reflexes": "🌪️ 快速反应",
    "☠️ Curses": "☠️ 诅咒",
    "🎯 Target": "🎯 目标",
    "🧹 Reset": "🧹 重置",
    "📥 Import": "📥 导入",
    "📤 Export": "📤 导出",
    "💾 Save": "💾 保存",
    "⚙️ Settings": "⚙️ 设置",
    "🌀 Buffs": "🌀 增益",
    "🔄Reset perks": "🔄 重置特权",
    "🧝 Hero": "🧝 英雄",
    "📝 Logs": "📝 日志",
    "📜 Events": "📜 事件",
    "🌍 Progress": "🌍 进度",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "💀": "💀",
    "💠": "💠",
    "📖": "📖",
    "🔒": "🔒",
    "🔥": "🔥",
    "🔮": "🔮",
    "🥾": "🥾",
    "🧥": "🧥",
    "ℹ️": "ℹ️",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': '最大',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "BUFF: ": "BUFF: ",
    "Level: ": "等级: ",
    // "👾 ": "👾 ",
    "You dropped the ": "你掉落了 ",
    "Lvl ": "等级 ",
    "Points: ": "点数: ",
    "TIER[": "层级[",
    "TOTAL: ": "总计: ",
    "Total: ": "总计: ",
    "Boots": "靴子",
    "Body": "身体",
    "Iron Sword": "铁剑",
    "Leather Armor": "皮甲",
    "Leather Boots": "皮靴",
    "Rusty Sword": "生锈的剑",
    "Sword": "剑",
    "Berserk": "狂暴",
    "Combo": "连击",
    "Overkill": "超杀",
    "Sniper": "狙击手",
    "Conquer": "征服",
    "Flexible": "灵活",
    "Extra life": "额外生命",
    "Fast Slash": "快速斩",
    "Blood Art": "血液艺术",
    "Chainmail": "锁子甲",
    "Scout Boots": "侦查靴",
    "Active: ": "活跃: ",
    "Invisible": "隐形",
    "Racer": "赛车手",
    "Solid Body": "固体",
    "Wisdom": "智慧",
    "Endurance": "耐力",
    "Strength": "力量",
    "First Strike": "先发制人",
    "Ring": "戒指",
    "Shards:": "碎片:",
    "Total shards: ": "总计碎片: ",
    "Steel Blade": "钢刃",
    "Cloth Armor": "布甲",
    "Worn Slippers": "旧拖鞋",
    "Souls": "灵魂",
    "BUFF EXP MULT - ": "BUFF经验乘数 - ",
    "Ascend Shards MULT When you Ascend - ": "转生时转生碎片乘数 - ",
    "Weapon Chance per SOUL TIER - ": "每个灵魂层级武器掉率 - ",
    "Knight’s Edge": "骑士之刃",
    "Void Talisman": "虚空护身符",
    "Nemesis Сhaos": "复仇女神混乱",
    "COMBO": "组合",
    "Endless Eye": "无尽之眼",
    "Ethereal Pendant": "空灵吊坠",
    "♻️ Rebirth ": "♻️ 重生 ",
    "Traveller": "旅行者",
    "*Lvl: ": "*等级: ",
    "BASE CRIT DAMAGE: ": "基础暴击伤害: ",
    "BASE CRIT: ": "基础暴击: ",
    "Space: ": "空间: ",
    "D-Atlas: ": "维度地图集: ",
    "Infinity: ": "无限: ",
    "Overkill: ": "超杀: ",
    "Rebirth: ": "重生: ",
    "Abyss D: ": "深渊 D: ",
    "Radiation: ": "辐射: ",
    "Total Level ": "总等级 ",
    "BASE DOODGE: ": "基础闪避: ",
    "Soul Booster Chance equals to ": "灵魂助推器的几率等于 ",
    "- [MAX - ": "- [最大 - ",
    "Star Space ": "星辰空间 ",
    "APS: ": "APS: ",
    "Max Level MULT - ": "最大等级乘数 - ",
    "Rebirth Pts: ": "重生点数: ",
    "Knight’s Plate": "骑士板甲",
    "Mystic Band": "神秘乐队",
    "Obsidian Cutter": "黑曜石刀",
    "Ranger’s Tread": "游侠的脚印",
    "BUFF - ": "BUFF - ",
    "Rebirth Pts MULT - ": "重生点数乘数 - ",
    "Unlock Formation": "解锁阵型",
    "Cap: ": "上限: ",
    "DMG - ": "伤害 - ",
    "HP - ": "生命值 - ",
    "Potential: ": "潜能: ",
    "Bonus Penalty: ": "奖励处罚: ",
    "*CORRUPTION ": "*腐败 ",
    "Infinity [": "无限 [",
    "Max Stage: ": "最大关卡: ",
    "Juggernaut": "主宰者",
    "- Active: ": "- 活跃: ",
    "Lvl: ": "等级: ",
    "Space Boss": "空间Boss",
    "REBUILD ONE OF THE PERK IN TREE": "重建树中的一个特权",
    "Mutagen": "诱变剂",
    "Mutagens: ": "诱变剂: ",
    "DANGER: ": "危险: ",
    "Enemy Power: ": "敌人的力量: ",
    "Increase mutagen gaining": "增加诱变剂的获得",
    "Comet Ring": "彗星戒指",
    "Phantom Boots": "幻影战靴",
    "Dragonhide Armor": "龙皮铠甲",
    "Celestial Greatsword": "天体巨剑",
    "Open Invisible": "打开隐形",
    "✨ Stardust: ": "✨ 星尘: ",
    " of Stars": "星星",
    "BASE DODGE: ": "基础闪避: ",
    "Dimension: ": "维度: ",
    "Bronze Ring": "青铜戒指",
    "Inferno Blade": "地狱之刃",
    "Points(P): ": "点数(P): ",
    "Rebirth Pts(RP): ": "重生点数(RP): ",
    "The Flash": "闪光",
    "Unlock Amulet ": "解锁护身符 ",
    "Unlock Amulet: Prefix ": "解锁护身符: 前缀",
    "Unlock Amulet: Suffix ": "解锁护身符: 后缀",
    "Level Exp Reduction based on Rebirth Pts ": "等级经验减少基于重生点数 ",
    "Unlock Invisible ": "解锁隐形 ",
    "Reach Infinity": "达到无限",
    "Reach Soul": "达到灵魂",
    "Reach Total Lvl": "达到总等级",
    "The Infinite One": "无限一",
    "Ω-Infinity": "欧米伽无限",
    "✨ Space Power(SP) - ": "✨ 空间之力(SP) - ",
    "🌟Star(ST) - ": "✨ 星星(ST) - ",
    "*ASCENSION AFFECT: ": "*转生影响:",
    "*LOOT - ": "*战利品 - ",
    "Ascension Souls(%) - ": "转生灵魂(%) - ",
    "Rebirth Souls(%) - ": "重生灵魂(%) - ",
    "Max Level: ": "最大等级: ",
    "Reach True Lvl ": "达到真实等级 ",
    "Corruption - ": "腐败 -",
    "Complete the Singularity ": "完成奇点 ",
    "Infinity Points(IP): ": "无限点数(IP): ",
    "Potential - ": "潜能 - ",
    "Reach THE ETERNITY BRIGHT": "到达永恒的光明",
    "Reach The Celestial Greatsword": "到达天体巨剑",
    "Scale Armor": "鳞甲",
    "Swiftstride": "大步流星",
    "Dimension ": "维度 ",
    "Formation": "阵型",
    "Base: ": "基数: ",
    "Abyss[T": "深渊[T",
    "Damage MULT: ": "伤害乘数: ",
    "Your best time ": "你的最佳时间 ",
    "Max Danger: ": "最大危险: ",
    "Rebirth [": "重生 [",
    "You will get double stats until Level(not includeing Min Level) ": "你会得到双倍的属性，直到等级（不包括最低等级） ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " EXP": " 经验值",
    "33% that your DEF will be double when enemy hits you": "：33%几率当敌人击中你时，你的防御将翻倍",
    "35% to block the enemy attack to 1 DMG": "35%几率格挡敌人的攻击到 1 伤害",
    " after Ascension)": " 在转生后)",
    "Deal double DMG by First attack": "第一次攻击造成双倍伤害。",
    "First attack is always critical": "第一次攻击总是暴击。",
    "x Rebirth Pts": "x 重生点数",
    "Note: You gain the loot from only first killed enemy; 100% to kill next enemy;": "注意：你只能从第一个被杀死的敌人那里获得战利品；100%击杀下一个敌人；",
    "Heal HP equals to stage passed per second": "治疗生命值为每秒通过的关卡数",
    "extra kill per each 100 max level;": "额外击杀每100最大等级；",
    "HP per second [MAX - 500s]": "生命值每秒 [最大 - 500s]",
    "DMG per second [MAX - 750s]": "伤害每秒 [最大 - 750s]",
    "DMG per COMBO [MAX- 30]; +1 COMBO per hit; COMBO Resets if you was hit by enemy": "伤害每个连击的[最高- 30]；每击+1连击；如果你被敌人击中会重置",
    "35% to RISE UP after death with 50% HP. Does not work on the same enemy twice.": "在死亡后复活，生命值为50%。不能对同一个敌人起两次作用。",
    "to hit extra time; -0.7 Attack per Second": "额外攻击次数; -0.7 攻击每秒",
    "IF CRIT HIGHER 100% DEAL EXTRA DOUBLE DAMAGE": "如果暴击值高于100%，额外造成双倍伤害",
    " (P)": " (P)",
    "Conquer": "征服",
    "Berserk": "狂暴",
    "Combo": "连击",
    "Overkill": "超杀",
    "Sniper": "狙击手",
    "Flexible": "灵活",
    "Extra life": "额外生命",
    "Fast Slash": "快速斩",
    "Blood Art": "血液艺术",
    "Chance the appearance of the lower tier souls. The lower Tier souls drop Rebirth Pts.": "有概率出现低品质的灵魂。低品质的灵魂会掉落重生点数。",
    "*LOOT - [": "*战利品 - [",
    "only reward once by Ascension Shards.": "只奖励一次转生碎片。",
    "Heal 5% HP per second": "每秒治疗5%的生命值",
    "Stop at Stage": "停止关卡",
    "A separate 25% to hit an extra additional time; -0.6 Attack per Second": "一个单独的25%达到一个额外附加时间;每秒攻击-0.6",
    "WHEN YOUR HP is lower than 30% HEAL 1% PER 10% LOST HP": "当你的生命值低于30%时，每减少10%的生命值，则治疗1%生命值",
    "1% of enemy weakness per 75 seconds [MAX - 1250]; Start with 250 seconds": "每75秒使敌人虚弱1% [最大 - 1250]；从250秒开始",
    "+0.01 APS per each Stage Passed [MAX - 1]": "每通过一关+0.01点APS [最大 - 1]",
    "+0.1 ATTACK SPEED per 250 seconds [MAX - 1000s]": "+0.1攻击速度每250秒[最大- 1000秒]",
    "+1.5% DMG per COMBO [MAX- 50]; +1.5 COMBO per hit; COMBO Resets 50% if you get hit by an enemy": "每次连击伤害+1.5% [最大- 50]；每次命中+1.5连击；如果被敌人击中，连击重置50%",
    "+1.75% DMG per COMBO [MAX- 100]; +2 COMBO per hit; COMBO Resets get killed by an enemy; +0.3 Attack per Second when COMBO is MAX": "每次连击伤害增加1.75% [最大- 100]；每次命中+2连击；被敌人击杀时连击重置；连击值为最大时，每秒攻击+0.3",
    "10% to gain EXP && WEAPON CHANCE for each overkilled Enemy": "每杀死一个敌人，获得10%的经验和武器几率",
    "Dirty Blood": "肮脏之血",
    "Self-destruction": "自我毁灭",
    "Titan": "泰坦",
    "Bleeding": "流血",
    "Steel skin": "钢铁皮肤",
    "Strong Muscles": "强大的肌肉",
    "You can upgrade Body": "你可以升级身体",
    "Unlock new Buff: The Flash": "解锁新的BUFF：闪光",
    "Open Radiation": "开放辐射",
    "Unlock Amulet [T4]": "解锁护身符 [T4]",
    "CORRUPTION WEAKNESS based on SP": "基于空间之力（SP）的腐蚀虚弱",
    "You can upgrade Ring": "您可以升级戒指",
    "The Sword has Suffix and Prefix": "剑有后缀和前缀",
    "Unlock new BUFF: Jaggernaut": "解锁新BUFF：贾格诺特",
    "Open Second Ring": "开放第二戒指",
    "Unlock Abyss D": "解锁深渊维度",
    "You can upgrade Boots": "你可以升级靴子",
    "EXP Gain based on SP": "基于空间之力（SP）的经验增益",
    "+10% Equipment Drop per SP": "每空间之力（SP） +10%装备掉落",
    "Open the Star Forge. You can Enhance The Sword by Stardust": "打开星际熔炉。你可以通过星尘来增强剑",
    "+1 MIN SWORD TIER per Space Boss killed": "每击杀1个空间Boss，剑最小层级+1",
    " [Infinity Bonus]": " [无限加成]",
    " [Prefix]": " [前缀]",
    "Heal HP equal to current stage per second": "每秒恢复相当于当前关卡的生命值",
    "Heal 5% HP when you kill an enemy": "当你杀死敌人时，回复5%的生命值",
    "The ability to kill an enemy without a fight. The enemy does not drop loot.": "不战而胜的能力。敌人不会掉落战利品。",
    " Corruption weakness. [Corrupted Amplification] scales better": "腐化弱点。[腐化放大] 的缩比例更好",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)k$/,
    /^([\d\.]+)\/([\d\.]+)m$/,
    /^([\d\.]+)\/([\d\.]+)b$/,
    /^([\d\.]+) \/ ([\d\.]+)k$/,
    /^([\d\.]+)k \/ ([\d\.]+)k$/,
    /^([\d\.]+)k \/ ([\d\.]+)m$/,
    /^([\d\.]+)m \/ ([\d\.]+)m$/,
    /^([\d\.]+)b \/ ([\d\.]+)m$/,
    /^([\d\.]+)b \/ ([\d\.]+)b$/,
    /^([\d\.]+)t \/ ([\d\.]+)m$/,
    /^([\d\.]+)t \/ ([\d\.]+)b$/,
    /^([\d\.]+)t \/ ([\d\.]+)t$/,
    /^([\d\.]+)q \/ ([\d\.]+)t$/,
    /^([\d\.]+)Od \/ ([\d\.]+)Od$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    // /^🛡️(.+)$/,
    /^⚔️(.+)$/,
    /^👾(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^\(\+([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^🛡️([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^🧘\[\-([\d\.,]+)\]$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^T([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^\[([\d\.]+)\]$/,
    /^T\[([\d\.,]+)\]$/,
    /^⚡\[([\d\.,]+)\]$/,
    /^🕐\[([\d\.,]+)\]$/,
    /^ T\[([\d\.,]+)\]$/,
    /^([\d\.,]+) 🌌$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^All dead bosses give you (.+) MIN LEVEL, (.+) MAX LEVEL$/, '所有死去的boss给你 $1 最低等级，$2 最高等级'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Complete (.+) Dimension$/, '完成 $1 维度'],
    [/^You will be able to enter this dimension once you have completed Infinity (.+) in the previous one and Infinity (.+) in the main one$/, '你将能够进入这个维度，一旦你完成了 无限 $1 在上一个维度 和 无限 $2 在主维度'],
    [/^You will be able to enter this dimension once you have completed Infinity (.+) in the main one and Infinity (.+) in the previous one.$/, '你将能够进入这个维度，一旦你完成了 无限 $1 在主维度 和 无限 $2 在前一个维度。'],
    [/^You will be able to enter this dimension once you have completed Infinity (.+) in the previous one.$/, '你将能够进入这个维度，一旦你完成了上一个无限 $1。'],
    [/^Reward: (.+) to get AFK boost for (.+)s$/, '奖励：$1 获得AFK加成，持续 $2 秒'],
    [/^Deal (.+) Damage$/, '造成 $1 伤害'],
    [/^You gain (.+) ascension shards from Nether Gleam$/, '你从虚空之光获得 $1 转生碎片'],
    [/^Reach Stage (.+) in Abyss D$/, '在深渊维度达到关卡 $1'],
    [/^You will need (.+) True Max Level to reach (.+) Max Level$/, '你需要 $1 真实满级才能达到 $2满级'],
    [/^You will be able to enter this dimension once you have completed Infinity (.+) in the previous one and Infinity (.+) in the main one.$/, '一旦你完成了前一个维度的无限 $1 和主维度的无限 $2，你就能进入这个维度。'],
    [/^You will be able to enter this dimension once you have completed Infinity (.+) in the main one.$/, '你们将能够进入这个维度，一旦你们在主维度中完成了无限 $1。'],
    [/^Buff: Overkill (.+) instead of (.+)$/, 'Buff: 超杀 $1 而不是 $2'],
    [/^AMULET(.+) Prefix$/, '护身符$1 前缀'],
    [/^AMULET(.+) Prefix (.+)$/, '护身符$1 前缀 $2'],
    [/^AMULET(.+) SLOT$/, '护身符$1 栏位'],
    [/^AMULET(.+) SLOT (.+)$/, '护身符$1 栏位 $2'],
    [/^AMULET(.+) Suffix$/, '护身符$1 后缀'],
    [/^AMULET(.+) Suffix (.+)$/, '护身符$1 后缀 $2'],
    [/^Every level gives you (.+) HP, (.+) DMG, (.+) DEF$/, '每级给你 $1 生命值，$2 伤害，$3 防御'],
    [/^Unlock Amulet(.+) Suffix$/, '解锁 护身符$1 后缀'],
    [/^Unlock Amulet(.+) prefix$/, '解锁 护身符$1 前缀'],
    [/^Endgame content is (.+) Level\(Abyss (.+)\)$/, '终局内容是 $1 级（深渊 $2）'],
    [/^You gained (.+) BUFF EXP.$/, '你获得了 $1 增益经验。'],
    [/^You gained (.+) mutagens.$/, '你获得了 $1 诱变剂。'],
    [/^You gained (.+) stardust.$/, '你获得了 $1 星尘。'],
    [/^You gained (.+) EXP.$/, '你获得了 $1 经验值。'],
    [/^You gain (.+) ascension shards from Flickering Essence$/, '你获得了 $1 转生碎片 从 闪烁精华'],
    [/^You gain (.+) ascension shards from Shard of Dusk$/, '你获得了 $1 转生碎片 从 黄昏碎片'],
    [/^You gain (.+) ascension shards from Whispering Soul$/, '你获得了 $1 转生碎片 从 低语之魂'],
    [/^You gain (.+) ascension shards from Veiled Wraith$/, '你获得了 $1 转生碎片 从 面纱魔灵'],
    [/^You gain (.+) ascension shards$/, '你获得了 $1 转生碎片'],
    [/^You gain (.+) mutagens$/, '你获得了 $1 诱变剂'],
    [/^You gain (.+) ascension shards from Cinderfang$/, '你获得了 $1 转生碎片从煤渣牙'],
    [/^You gain (.+) stardust$/, '你获得了 $1 星尘'],
    [/^You gain (.+) Curse bonuses$/, '你获得了 $1 诅咒加成'],
    [/^\[T([\d\.]+)\]: ([\d\.]+)\% \- \[MAX \- ([\d\.]+)\]$/, '\[T$1\]: $2\% \- \[最大 \- $3\]'],
    [/You dropped the Leather Boots (.+)$/, '你掉落了 皮靴 $1'],
    [/You dropped the Chainmail (.+)$/, '你掉落了 锁子甲 $1'],
    [/You dropped the Scout Boots (.+)$/, '你掉落了 侦查靴 $1'],
    [/^You passed from (.+) stage (.+) zone \-\> (.+) stage (.+) zone$/, '你从 区域 $2 关卡 $1 -> $4 关卡 $3'],
    [/^Offline bonus for (.+)\n(.+)\(MAX \- (.+)h\). You gained (.+) EXP.  Buff EXP (.+). You passed from (.+) stage (.+) zone \-\> (.+) stage (.+) zone$/, '离线 $1 的奖励\n$2(最大 - $3小时）。获得 $4 经验，增益经验 $5。你从 区域 $7 关卡 $6 -> $9 关卡 $8'],
    [/^Offline bonus for (.+)\n(.+)\(MAX \- (.+)h\). You gained (.+) EXP. Buff EXP (.+). You passed from (.+) stage (.+) zone \-\> (.+) stage (.+) zone$/, '离线 $1 的奖励\n$2(最大 - $3小时）。获得 $4 经验，增益经验 $5。你从 区域 $7 关卡 $6 -> $9 关卡 $8'],
    [/^Offline bonus for (.+)\n(.+)\(MAX \- (.+)h\). You gained (.+) EXP. Buff EXP (.+)$/, '离线 $1 的奖励\n$2(最大 - $3小时）。获得 $4 经验，增益经验 $5'],
    [/^Offline bonus for (.+)\(MAX \- (.+)h\)$/, '离线 $1 的奖励 (最大 - $2小时）'],
    [/^(.+) kills \(Zone (.+) , Stage (.+)\)$/, '$1 击杀（区域 $2，关卡 $3）'],
    [/^(.+) DMG per COMBO \[MAX\- (.+)\]; (.+) COMBO per hit\[(.+) to get additional COMBO\]; COMBO Resets (.+) if you was hit by enemy$/, '$1 伤害每连击[最高 - $2]；每次命中 $3连击[$4获得额外连击]；如果你被敌人击中，重置$5'],
    [/^(.+) CRIT, (.+) CRIT DMG$/, '$1 暴击, $2 暴击伤害'],
    [/^(.+) CRIT, (.+) CRIT DMG WHEN HP is low$/, '$1 暴击, $2 暴击伤害 当生命值过低时'],
    [/^(.+) DMG and (.+) DEF after RISING for (.+) seconds$/, '$1 伤害 $2 防御，上升后持续 $3 秒'],
    [/^(.+) Heal (.+) HP when you kill enemy$/, '$1 治疗 $2 生命值当你击杀敌人'],
    [/^(.+) You can hit additional time; (.+) Attack per Second$/, '$1 你可以额外攻击的次数；每秒攻击力 $2'],
    [/^(.+) Min Level, (.+) Max Level$/, '$1 最小等级, $2 最大等级'],
    [/^(.+) curse Bonus. (.+) Max Curse$/, '$1 诅咒奖励。$2 最大诅咒'],
    [/^(.+) DEF PER (.+) Lost HP$/, '$1 防御每损失 $2 生命值'],
    [/^(.+) CRIT CHANCE CHECKS DOUBLE$/, '$1 暴击几率检查翻倍'],
    [/^(.+) First attack can STUN Enemy for 1 second$/, '$1 第一次攻击可以使敌人昏迷1秒'],
    [/^(.+) Crit chance is checked twice$/, '$1 暴击几率被检查两次'],
    [/^(.+) First attack will STUN Enemy for 1 second$/, '$1 第一次攻击将晕眩敌人1秒'],
    [/^(.+) When your Hit is Critical, you ignore the Enemy\'s Avoid$/, '$1 当你的命中为暴击时，无视敌人的闪避效果'],
    [/^(.+) Heal (.+) of Max HP \+ \[current stage\] after each Attack$/, '$1 每次攻击后恢复自身生命上限 $2 \+ \[当前关卡\]的生命'],
    [/^(.+) After RISING become immune to any damage for 4 seconds$/, '$1 复活后对任何伤害免疫4秒'],
    [/^(.+) DEF From Max HP$/, '$1 防御从最大生命值'],
    [/^(.+) After Stage (.+) enemies drop Stardust$/, '$1 $2关后敌人掉落星尘'],
    [/^(.+) Avoid chance checks double times$/, '$1 闪避几率检查两次'],
    [/^(.+) max Buff in Abyss$/, '$1 深渊里最大增益上限'],
    [/^(.+) WEAPON DROP CHANCE$/, '$1 武器掉率'],
    [/^(.+) SOUL APPEAR CHANCE$/, '$1 灵魂出现几率'],
    [/^(.+) extra kill per each 50 level;$/, '$1 额外击杀每50级；'],
    [/^(.+) You are immune to stunning$/, '$1 你会免疫眩晕'],
    [/^(.+) You gain EXP \&\& WEAPON CHANCE for each Overkilled Enemy$/, '$1 每击杀一个敌人，你都会获得经验和武器的几率'],
    [/^(.+) Extra MAX Equipment Tier$/, '$1 额外最大装备层级'],
    [/^(.+) Max Level per 1 SP$/, '$1 最大等级每 1 空间之力（SP）'],
    [/^(.+) extra Enhances$/, '$1 额外强化'],
    [/^(.+) extra MAX Equipment Tier$/, '$1 额外最大装备层级'],
    [/^(.+) Max Tier$/, '$1 最大层级'],
    [/^(.+) Stage requirement scales better$/, '$1 关卡要求比例更好'],
    [/^(.+) to avoid enemy HIT$/, '$1 避免被敌人击中'],
    [/^(.+) Space Boos appearance based on Rebirth Tier (.+)$/, '$1 空间Boss出现 基于重生层级的 $2'],
    [/^(.+) Equipment Chance based on Rebirth Tier (.+)$/, '$1 装备几率 基于重生层级的 $2'],
    [/^(.+) Potential based on Rebirth Tier (.+)$/, '$1 潜能 基于重生层级的 $2'],
    [/^(.+) MIN Level based on Rebirth Tier (.+)$/, '$1 最小等级 基于重生层级的 $2'],
    [/^(.+) Corruption weakness based on Rebirth Tier (.+)$/, '$1 腐败弱点 基于重生层级的 $2'],
    [/^(.+) Max Level Mult based on Rebirth Tier (.+)$/, '$1 最大等级乘数 基于重生层级的 $2'],
    [/^(.+) Rebirth Tier forces Abyss enemies getting weaker (.+)$/, '$1 重生层级使深渊敌人变弱 $2'],
    [/^(.+) Low HP, High DMG (.+)$/, '$1 低生命值，高伤害 $2'],
    [/^(.+) Lurking Spirit (.+)$/, '$1 潜伏精神 $2'],
    [/^(.+) Shard of Dusk (.+)$/, '$1 黄昏碎片 $2'],
    [/^(.+) Veiled Wraith (.+)$/, '$1 面纱魔灵 $2'],
    [/^(.+) Space Ring Tier per each Star(.+)$/, '$1 空间戒指层级每个星星$2'],
    [/^(.+) Ashen Echo (.+)$/, '$1 灰色回声 $2'],
    [/^(.+) Ebon Spark (.+)$/, '$1 乌木火花 $2'],
    [/^(.+) Unlock Blood Art (.+)$/, '$1 解锁血液艺术 $2'],
    [/^(.+) MIN Chance Enhance (.+)$/, '$1 最小几率强化 $2'],
    [/^(.+) Unlock Amulet: Suffix (.+)$/, '$1 解锁护身符：后缀 $2'],
    [/^(.+) Unlock Amulet: Prefix (.+)$/, '$1 解锁护身符：前缀 $2'],
    [/^(.+) Space Boss appearance based on Rebirth Tier (.+)$/, '$1 空间Boss出现基于重生层级 $2'],
    [/^you will get (.+) Ascension Shards from Total Shards, (.+) in AFK every second$/, '你将从总碎片中获得 $1 转生碎片，AFK时每秒获得 $2 的 转生碎片'],
    [/^you will get (.+) new Infinity Perks$/, '你将获得 $1 新的无限特权'],
    [/^(.+) to find SOUL per each soul found$/, '每找到一个灵魂，增加 $1 的灵魂成本'],
    [/^(.+) to STUN for (.+) seconds \(Bonus: (.+)$/, '$1 眩晕 $2 秒 (加成:  $3'],
    [/^(.+)Penetrate (.+) DEF \(Bonus: (.+)$/, '$1 穿透 $2 防御 (加成:  $3'],
    [/^(.+)Heal (.+) HP \(Bonus: (.+)$/, '$1 治疗 $2 生命值 (加成:  $3'],
    [/^(.+)Block (.+) DMG \(Bonus: (.+)$/, '$1 格挡 $2 伤害 (加成:  $3'],
    [/^(.+) to CRIT (.+) DMG \(Bonus: (.+)$/, '$1 暴击造成 $2 伤害 (加成:  $3'],
    [/^(.+) to avoid attack \(Bonus: (.+)$/, '$1 躲避攻击 (加成:  $2'],
    [/^(.+) Attack Per Second \(Bonus: (.+)$/, '$1 攻击每秒 (加成:  $2'],
    [/^(.+) Each of your attack deals you (.+) Max HP \(Bonus: (.+)$/, '$1 你的每一次攻击使你获得 $2 的最大生命值 (加成:  $3'],
    [/^(.+) to bleed by (.+) from Attack for (.+) seconds \(Bonus: (.+)$/, '$1 从攻击中流血 $2，持续 $3 秒 (加成:  $4'],
    [/^(.+) The Hero\'s Regeneration is weaker by (.+) \(Bonus: (.+)$/, '$1 英雄的回复速度降低 $2 (加成:  $3'],
    [/^(.+) Attack \(Bonus: (.+)$/, '$1 攻击 (加成:  $2'],
    [/^(.+) Enemies gets (.+) DEF from Max HP \(Bonus: (.+)$/, '$1 敌人获得 $2 防御从最大生命值 (加成:  $3'],
    [/^(.+) Max HP \(Bonus: (.+)$/, '$1 最大生命值 (加成:  $2'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) MULT Rebirth Pts$/, '$1 多重重生点数'],
    [/^\+([\d\.]+)\% to Mutagen \[T([\d\.]+)\]$/, '\+$1\% 到诱变剂 [T$2]'],
    [/^\+([\d\.]+)\% DEF$/, '\+$1\% 防御'],
    [/^\+([\d\.]+)\% Extra Life Chance$/, '\+$1\% 额外生命几率'],
    [/^\+([\d\.]+)\% Souls LOOT$/, '\+$1\% 灵魂战利品'],
    [/^\+([\d\.]+)\% to SOUL search for each soul found$/, '\+$1\% 到灵魂搜索对于找到的每个灵魂'],
    [/^\+([\d\.]+) MULT EXP for each tier of equipment$/, '\+$1 每层装备的多重经验'],
    [/^\+([\d\.]+) MULT DMG per each killed enemy \[HARDCAP \- ([\d\.]+)\]$/, '每杀死一个敌人 \+$1 的多重伤害[硬上限 - $2]'],
    [/^\+([\d\.]+) HP$/, '\+$1 生命值'],
    [/^\+([\d\.]+) Space Tier$/, '\+$1 空间层级'],
    [/^\+([\d\.]+) MULT$/, '\+$1 乘数'],
    [/^\+([\d\.]+) SP$/, '\+$1 空间之力'],
    [/^\+([\d\.]+) INF Penalty Reduction$/, '\+$1 无限惩罚减免'],
    [/^\+([\d\.]+) Potential$/, '\+$1 潜能'],
    [/^\+([\d\.]+) Extra Max Level per Soul$/, '\+$1 额外等级上限每灵魂'],
    [/^\+([\d\.]+) free Tree Points$/, '\+$1 免费技能树点数'],
    [/^\+([\d\.]+) CRIT DMG$/, '\+$1 暴击伤害'],
    [/^\+([\d\.]+) DEF per ([\d\.]+) Potential$/, '\+$1 防御每 $2 潜能'],
    [/^\+([\d\.]+) DMG per ([\d\.]+) Potential$/, '\+$1 伤害每 $2 潜能'],
    [/^\+([\d\.]+) HP per ([\d\.]+) Potential$/, '\+$1 生命值每 $2 潜能'],
    [/^\+([\d\.]+) Min Level$/, '\+$1 最小等级'],
    [/^\+([\d\.]+) IP MULT per Inf Tier in main Dimension$/, '每个无限层级 \+$1 无限点数乘数在主维度'],
    [/^\+([\d\.]+) kill$/, '\+$1 击杀'],
    [/^\+\[([\d\.]+)\] Potential$/, '\+[$1] 潜能'],
    [/^\+([\d\.]+) Max MULT Level$/, '\+$1 最大多重等级'],
    [/^\+([\d\.]+) MULT EXP for each tier of Equipment$/, '\+$1 每一层装备的经验值'],
    [/^\+([\d\.]+) BASE CRIT CHANCE$/, '\+$1 基础暴击率'],
    [/^\+([\d\.]+) Rebirth Tier$/, '\+$1 重生层级'],
    [/^\+([\d\.]+) MAX Level$/, '\+$1 最大等级'],
    [/^\+([\d\.]+) DANGER per Level$/, '\+$1 危险每级'],
    [/^\+([\d\.]+) Tree Tier$/, '\+$1 技能树层级'],
    [/^\+([\d\.]+) MIN Armor Base$/, '\+$1 最小护甲基数'],
    [/^\+([\d\.]+) MIN Sword Base$/, '\+$1 最小剑基数'],
    [/^\+([\d\.]+) MIN Ring Base$/, '\+$1 最小戒指基数'],
    [/^\+([\d\.]+) MIN Boots Base$/, '\+$1 最小提升基数'],
    [/^\+([\d\.]+) MIN LEVEL$/, '\+$1 最低等级'],
    [/^\+([\d\.]+) MULT DMG$/, '\+$1 多重伤害'],
    [/^\+([\d\.]+) Max Level$/, '\+$1 最大等级'],
    [/^\+([\d\.]+) MAX LEVEL$/, '\+$1 最大等级'],
    [/^\+([\d\.]+) ATTACK PER SECOND$/, '\+$1 攻击每秒'],
    [/^\-([\d\.]+) Enemy HP$/, '\-$1 敌人生命值'],
    [/^\-([\d\.]+)\% Enemy HP$/, '\-$1\% 敌人生命值'],
    [/^\-([\d\.]+)\% Enemy Max HP$/, '\-$1\% 敌人最大生命值'],
    [/^\-([\d\.]+)\% Enemy Max Damage$/, '\-$1\% 敌人最大伤害'],
    [/^\-([\d\.]+) Enemy Attack per Second$/, '\-$1 敌人攻击每秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) pts → (.+) MIN LEVELS$/, '$1 点数 → $2 最小等级'],
    [/^([\d\.,]+) pts → Stage requirement scales better$/, '$1 点数 → 关卡需求比例更好'],
    [/^([\d\.,]+) pts → Unlock Extra Equipment Tier$/, '$1 点数 → 解锁额外装备层级'],
    [/^([\d\.,]+) pts → Levels scales better$/, '$1 点数 → 等级比例更好'],
    [/^([\d\.,]+) pts → Stages scales better$/, '$1 点数 → 关卡比例更好'],
    [/^([\d\.,]+) pts → EVO LOOT affects to Rebirth Pts$/, '$1 点数 → 进化战利品影响重生点数'],
    [/^([\d\.,]+) pts → EVO LOOT affects the BUFF$/, '$1 点数 → 进化战利品影响BUFF'],
    [/^([\d\.,]+) pts → EVO LOOT affects the Ascension Shards when you Ascend$/, '$1 点数 → 进化战利品影响转生时的转生碎片'],
    [/^([\d\.,]+) pts → EVO LOOT affects the chance of the soul appearance$/, '$1 点数 → 进化战利品影响灵魂出现几率'],
    [/^([\d\.,]+) pts → Unlock new BUFF: $/, '$1 点数 → 解锁 新BUFF: '],
    [/^([\d\.,]+) pts → Skip stage when you kill enemy. It works until (.+) Max Stage Reached (.+)$/, '$1 点数 → 击杀敌人跳过关卡。达到 $2 最大关卡时生效 $3'],
    [/^([\d\.,]+) pts → Increases your level while your level is below (.+) of Max Level (.+)$/, '$1 点数 → 增加你的等级当你的等级低于最高等级的 $2 时 $3'],
    [/^([\d\.,]+) pts → You have (.+) to avoid DMG$/, '$1 点数 → 你有 $2 的时间避免伤害'],
    [/^([\d\.,]+) pts → Unlock (.+) Equipment$/, '$1 点数 → 解锁 $2 装备'],
    [/^([\d\.,]+) pts → Unlock Formation(.+)$/, '$1 点数 → 解锁 阵型$2'],
    [/^([\d\.,]+) pts → Unlock Amulet(.+)$/, '$1 点数 → 解锁 护身符$2'],
    [/^([\d\.,]+) pts → Open equipment (.+) set$/, '$1 点数 → 打开 装备 $2 套装'],
    [/^([\d\.,]+) pts → Open Amulet(.+) Suffix$/, '$1 点数 → 打开 护身符$2 后缀'],
    [/^([\d\.,]+) pts → Open Amulet(.+) Prefix$/, '$1 点数 → 打开 护身符$2 前缀'],
    [/^([\d\.,]+) pts → Levels scale better$/, '$1 点数 → 等级比例更好'],
    [/^([\d\.,]+) pts → Rebirth Pts Mult based on Rebirth Tier$/, '$1 点数 → 基于重生层级的重生点数乘数'],
    [/^([\d\.,]+) pts → Break the world rule. Unlock First Space Fragment$/, '$1 点数 → 打破世界规则。解锁第一个空间碎片'],
    [/^([\d\.,]+) pts → Level requirement scales better$/, '$1 点数 → 等级要求比例更好'],
    [/^([\d\.,]+) pts → Unlock Tier ([\d\.,]+) Equipment Set$/, '$1 点数 → 解锁层级 $2 装备套装'],
    [/^([\d\.,]+) pts → (.+) Max Buff Slot$/, '$1 点数 → $2 最大BUFF栏位'],
    [/^([\d\.,]+) pts → (.+) BASE CRIT$/, '$1 点数 → $2 基础暴击'],
    [/^([\d\.,]+) pts → (.+) Potential$/, '$1 点数 → $2 潜能'],
    [/^([\d\.,]+) pts → (.+) BUFF$/, '$1 点数 → $2 BUFF'],
    [/^([\d\.,]+) pts → (.+) to find soul per Rebirth Tier$/, '$1 点数 → $2 几率找到灵魂 每个重生层级'],
    [/^([\d\.,]+) pts → (.+) Ascension Shards when you Ascend$/, '$1 点数 → $2 转生时的转生碎片'],
    [/^([\d\.,]+) pts → (.+)x$/, '$1 点数 → $2x'],
    [/^(.+) Ascension Shards (.+)$/, '$1 转生碎片 $2'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Space Fragments$/, '$1 空间碎片'],
    [/^([\d\.,]+) Space Power$/, '$1 空间之力'],
    [/^You killed (.+) and gained (.+) exp$/, '成功击杀 $1，获得 $2 经验'],
    [/^Unlock T([\d\.,]+) Body$/, '解锁 T$1 身体'],
    [/^Unlock T([\d\.,]+) Boots$/, '解锁 T$1 靴子'],
    [/^Unlock T([\d\.,]+) Ring$/, '解锁 T$1 戒指'],
    [/^Unlock T([\d\.,]+) Sword$/, '解锁 T$1 剑'],
    [/^Reach ([\d\.,]+) stage$/, '达到 $1 关'],
    [/^Reach ([\d\.,]+) Rebirth Pts$/, '达到 $1 重生点数'],
    [/^Stage ([\d\.,]+)$/, '关卡 $1'],
    [/^Upgrade \(([\d\.,]+)\)$/, '升级 （$1）'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^TIER ([\d\.,]+)$/, '层 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Next rebirth Tier: (.+) Level$/, '下一个重生层级：$1 等级'],
    [/^You gained: (.+) Pts$/, '你获得了：$1 点数'],
    [/^Next tier: (.+) kills.$/, '下一层级：$1 击杀。'],
    [/^S: (.+) CRIT$/, 'S：$1 暴击'],
    [/^P: (.+) CRIT DMG$/, 'P：$1 暴击伤害'],
    [/^Reward: (.+) IP$/, '奖励：$1 IP'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);