//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "加成",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "An idle factory simulation game": "一款放置工厂模拟游戏",
    "Build & Automate": "建造 & 自动化",
    "Build your industrial empire from the ground up": "从头开始建立你的工业帝国",
    "Construct buildings and automate resource production": "建造建筑物和自动化资源生产",
    "Exchange resources and build trade networks": "交换资源，建立贸易网络",
    "Factory Works Idle": "工厂运行放置",
    "Gather resources, research technologies, and automate your factory": "收集资源，研究技术，自动化你的工厂",
    "Research & Advance": "研究 & 发展",
    "Start Game": "开始游戏",
    "Trade & Prosper": "贸易 & 繁荣",
    "Unlock new technologies and expand your capabilities": "解锁新技术并扩展您的能力",
    "Lv.": "等级",
    "Iron": "铁",
    "General": "常规",
    "items": "物品",
    "Locked": "未解锁",
    "Max Resources": "最大资源",
    "Prestige": "声望",
    "Production": "生产",
    "Research": "研究",
    "Research Required": "研究要求",
    "Resources": "资源",
    "Starting Game...": "开始游戏...",
    "Stone": "石头",
    "Stone Age": "石器时代",
    "Stone Mine": "石头矿",
    "Storage": "存储",
    "Tech": "科技",
    "Trading": "贸易",
    "Unlock All": "解锁全部",
    "Static": "静态",
    "Wood": "木头",
    "Woodcutter": "伐木工",
    "⏰ Dedicated Player": "⏰专注玩家",
    "🔓 Unlock Orphaned Resources": "🔓解锁孤立资源",
    "All Buildings": "所有建筑",
    "Automation": "自动化",
    "Available:": "可用:",
    "Basic resource gathering and simple tools": "基础的资源采集和简单的工具",
    "Build": "建造",
    "Buildings": "建筑",
    "Click Power": "点击威力",
    "Copper": "铜",
    "Copper": "铜",
    "Developer Tools": "开发者工具",
    "Development mode only": "仅限开发模式",
    "Era": "时代",
    "Fixes resources stuck in \"locked\" state (check console for details)": "修复资源卡在\“锁定\”状态（详细信息请查看控制台）",
    "Done": "完成",
    "Digital Age": "数字时代",
    "Complete": "完成",
    "Upgrade": "升级",
    "Total:": "总计:",
    "Unlock": "解锁",
    "Add": "增加",
    "Antimatter Era": "反物质时代",
    "Add Prestige Points": "添加声望点数",
    "🖱️ First Click": "🖱️ 第一次点击",
    "🏗️ First Building": "🏗️ 第一个建筑",
    "🏆 Wood Collector": "🏆 木头收集者",
    "🏆 Stone Collector": "🏆 石头收集者",
    "Available Points:": "可用点数:",
    "Building": "建筑",
    "Basic Trading": "基础贸易",
    "Basic Click Efficiency": "基础点击效率",
    "Current Points:": "当前点数:",
    "Current Status": "当前状态",
    "In Queue": "队列中",
    "Iron Age": "铁器时代",
    "level": "等级",
    "Level": "等级",
    "Manage Queue": "管理队列",
    "MAX": "最大",
    "Net:": "净值:",
    "Producers (": "生产者 (",
    "Prestige Level:": "声望等级:",
    "Double the resources gained per click": "每次点击获得双倍的资源",
    "Electronics Era": "电子时代",
    "Enable Prestige": "启用声望",
    "Fusion Age": "聚变时代",
    "Instantly complete research (no cost/time)": "立即完成研究（无需成本/时间）",
    "Instantly upgrade buildings to next level (no cost/time)": "立即将建筑升级到下一级（无需成本/时间）",
    "Mining Technology": "采矿技术",
    "Nano Era": "纳米时代",
    "Perform Prestige": "执行声望",
    "Quantum Age": "量子时代",
    "Research Completed:": "研究完成:",
    "Reset Game": "重置游戏",
    "Reset Tech Notifications": "重置技术通知",
    "Resets game with prestige bonuses (requires 10+ available points)": "重置游戏获得声望加成（需要10+可用点数）",
    "Robotics Era": "机器人时代",
    "Singularity": "奇点",
    "Singularity Produced:": "奇点产出：",
    "Singularity:": "奇点:",
    "storage": "存储",
    "total level": "总等级",
    "Total Points:": "总点数：",
    "Unlock the ability to trade resources with nearby settlements": "解锁与附近定居点交易资源的能力",
    "Unlocks all buildings to level 50, completes 45+ research, produces 500+ singularity": "解锁所有建筑至50级，完成45+研究，产生500+奇点",
    "Unlocks iron and copper mining": "解锁铁矿和铜矿开采",
    "Active": "活跃",
    "Available Research": "可用研究",
    "Base click power: 2x per click": "基础点击力量：每点击2x",
    "Cost:": "成本:",
    "Effects:": "效果:",
    "Enables Wood ⇄ Stone trading": "启用木头⇄石材贸易",
    "Queued": "排队",
    "Queued:": "排队:",
    "Research Queue": "研究队列",
    "Research Tree": "研究树",
    "Scaled by resource rarity (100% for Wood/Stone down to 1% for Singularity)": "根据资源稀有程度缩放（100%的木头/石头下降到1%的奇点）",
    "Time:": "时间:",
    "Iron Mine, Copper Mine, Metal Storage": "铁矿，铜矿，金属存储",
    "Iron, Copper": "铁，铜",
    "🔬 First Research": "🔬 第一个研究",
    "Target": "目标",
    "Select": "选择",
    "research": "研究",
    "Gear": "齿轮",
    "Gear Factory, Component Storage": "齿轮工厂, 组件存储",
    "Iron Mine": "铁矿",
    "Module Type": "模块类型",
    "Modules:": "模块:",
    "No Automation Modules": "无自动化模块",
    "Cancel": "取消",
    "Cannot Afford": "负担不起",
    "Auto-Build": "自动建造",
    "Auto-Research": "自动研究",
    "Automation Control": "自动化控制",
    "a building": "一个建筑",
    "+ Add New Module": "+ 添加新模块",
    "Active Modules": "活跃模块",
    "Add Module": "添加模块",
    "Copper Mine": "铜矿",
    "Enables gear production": "启用齿轮生产",
    "Metal Working": "金属加工",
    "Add automation modules to automatically manage buildings and research.": "添加自动化模块来自动管理建筑和研究。",
    "Add New Automation Module": "添加新的自动化模块",
    "Available Circuits": "可用电路",
    "Available Robots": "可用机器人",
    "Circuit": "电路",
    "Circuit Factory": "电路工厂",
    "Electronics": "电子产品",
    "Enables circuit production": "实现电路生产",
    "Metal extraction and forging": "金属提取和锻造",
    "💱 Execute Trade": "💱 执行交易",
    "Available Trade Routes": "可用的贸易路线",
    "Base Rate:": "基本费率：",
    "Basic Trading Complete!": "基础交易完成！",
    "Exchange Rate:": "汇率:",
    "Max:": "最大：",
    "Next update in:": "距离下次更新：",
    "Routes:": "路线:",
    "Select a trade route to begin trading": "选择一条贸易路线开始交易",
    "Storage:": "存储：",
    "Trade Details": "贸易详情",
    "Trade Quantity:": "贸易数量：",
    "Trading Market": "交易市场",
    "You Receive:": "你收到:",
    "You Spend:": "你花费：",
    "🔨 Craft": "🔨 制作",
    "⚡ Activate": "⚡ 激活",
    "| Cooldown:": "| 冷却时间:",
    "Tip:": "提示:",
    "Play time:": "游戏时间:",
    "Play Time": "游戏时间",
    "Plastic Factory": "塑料工厂",
    "Plastic": "塑料",
    "Owned:": "拥有:",
    "Music": "音乐",
    "Music Volume": "音乐音量",
    "Glass": "玻璃",
    "Glass Factory": "玻璃工厂",
    "Gear Factory": "齿轮工厂",
    "Game started:": "游戏开始于:",
    "Game Settings": "游戏设置",
    "Game Progress": "游戏进度",
    "Game Info": "游戏信息",
    "Epic": "史诗",
    "Enabled": "启用",
    "Effect:": "效果:",
    "Duration:": "持续时间:",
    "Close Dialog": "关闭弹框",
    "Click Master": "点击大师",
    "Boosters": "助推器",
    "Antimatter": "反物质",
    "Antimatter Collector": "反物质收集器",
    "Available Boosters": "可用助推器",
    "Computer": "计算机",
    "Computer Factory": "计算机工厂",
    "Factory Factory": "机器人工厂",
    "Computer Science": "计算机科学",
    "Last saved:": "最近保存:",
    "Quantum Core": "量子核心",
    "Save Game": "保存游戏",
    "SFX Volume": "音效音量",
    "Steel": "钢",
    "Statistics & Progress": "统计 & 进度",
    "Sound Effects": "声音效果",
    "Sound Settings": "声音设置",
    "Robot": "机器人",
    "Singularity Core": "奇点核心",
    "Technology Unlocked!": "科技已解锁!",
    "UI Sounds": "界面声音",
    "UI Volume": "界面音量",
    "Version:": "版本:",
    "Master Volume": "大师音量",
    "Export Save File": "导出存档文件",
    "Import Save File": "导入存档文件",
    "Completed Research": "已完成研究",
    "About Factory Works Idle": "关于工厂运行放置",
    "High-Tech Storage": "高科技存储",
    "1 nanite, 5 robot, 10 computer": "1个纳米，5个机器人，10个电脑",
    "2 quantum, 20 computer, 30 circuit": "2量子，20计算机，30电路",
    "5x research speed for 10 minutes": "5倍研究速度，持续10分钟",
    "Achievement Unlocked!": "成就解锁！",
    "Advanced computing and digital systems": "先进的计算机和数字系统",
    "Buildings Constructed": "已建建筑物",
    "Consumers (": "消费者(",
    "Efficiency Catalyst": "效率催化剂",
    "Export your save file to transfer your progress between different platforms (web, Steam, etc.) or to create backups.": "导出您的保存文件以在不同平台（web， Steam等）之间传输您的进度或创建备份。",
    "Factory Works Idle is an idle factory building game where you build and manage an industrial empire.": "《Factory Works Idle》是一款放置工厂建设游戏，玩家可以在其中建造和管理一个工业帝国。",
    "Fusion Core": "聚变堆芯",
    "Fusion Reactor": "聚变反应堆",
    "Instant": "瞬间",
    "Instant Building Completion": "建筑瞬间完成",
    "Instantly completes the next building in queue": "立即完成队列中的下一个建筑",
    "Keyboard Shortcuts": "键盘快捷键",
    "Multi-Gather": "多重采集",
    "Nanite Factory": "纳米工厂",
    "Nanite Swarm": "纳米群",
    "Nanite Swarm Pack": "纳米群包",
    "Press ESC to close any open dialog or modal": "按ESC关闭任何打开的对话框或模式",
    "Quantum Amplifier": "量子放大器",
    "Quantum Laboratory": "量子实验室",
    "Reach 100 click power": "达到100点击力量",
    "Reset Progress": "重置进度",
    "Resource Magnet": "资源磁铁",
    "Resources Consumed": "资源消耗",
    "Resources Produced": "资源生产",
    "Save file exported successfully!": "导出文件保存成功！",
    "Save File Management": "保存文件管理",
    "Steel Foundry": "炼钢厂",
    "Transcendent artificial superintelligence": "卓越的人工超级智能",
    "Your game is automatically saved every 30 seconds. You can manually save anytime using the button above.": "你的游戏每30秒自动保存一次。您可以随时使用上面的按钮手动保存。",
    "10 circuit, 15 gear, 20 steel": "10电路，15齿轮，20钢",
    "Doubles production speed for 5 minutes": "生产速度翻倍，持续5分钟",
    "No research available to complete": "没有研究可以完成",
    "paused": "暂停",
    "Robot Factory": "机器人工厂",
    "Unlocked": "已解锁",
    "Uncommon": "罕见",
    "Remove": "移除",
    "Ready": "就绪",
    "Special": "特殊",
    "Show Hidden": "显示隐藏",
    "Iron Collector": "铁收集者",
    "Wood Collector": "木头收集者",
    "Stone Collector": "石头收集者",
    "Speed Clicker": "速度点击者",
    "Scientist": "科学家",
    "Trader": "贸易者",
    "Storage King": "存储之王",
    "Progress": "进度",
    "Rare": "稀有",
    "points)": "点数)",
    "Legendary": "传说",
    "First Research": "第一个研究",
    "First Click": "第一次点击",
    "First Building": "第一个建筑",
    "First Trade": "第一次交易",
    "First Prestige": "第一次声望",
    "Factory Owner": "工厂拥有者",
    "Cooldown": "冷却时间",
    "Cooldown (seconds)": "冷却时间 (秒)",
    "Easter Egg": "复活蛋",
    "Hidden": "隐藏",
    "💱 First Trade": "💱 第一次交易",
    "⚛️ Quantum Parallel Processing": "⚛️ 量子并行处理",
    "Common": "普通",
    "Priority:": "优先级:",
    "Priority (1-10)": "优先级 (1-10)",
    "Missing Resources:": "缺少资源:",
    "Milestone": "里程碑",
    "Mass Producer": "大规模生产者",
    "Active Automation Modules": "活跃的自动化模块",
    "All available research completed!": "已完成所有可用的研究！",
    "Auto-Build: Woodcutter": "自动建造：伐木工人",
    "Building Master": "建筑大师",
    "Click 100 times in 10 seconds": "10秒内点击100次",
    "Click to gather your first resource": "点击收集你的第一个资源",
    "Complete your first research project": "完成你的第一个研究项目",
    "Complete your first trade": "完成你的第一笔交易",
    "Construct your first building": "建造你的第一座建筑",
    "Continue playing to unlock more research opportunities.": "继续游戏可以解锁更多的研究机会。",
    "Dedicated Player": "忠实玩家",
    "Find the hidden achievement": "寻找隐藏的成就",
    "Hardcore Player": "硬核玩家",
    "Have 10,000 total storage capacity": "拥有10000的总存储容量",
    "Have 5 buildings at level 5 or higher": "有5个5级或更高级别的建筑",
    "Higher priority modules run first": "优先级高的模块优先运行",
    "How often this module should run": "这个模块应该多久运行一次",
    "Insufficient Resources": "资源不足",
    "Perform your first prestige": "完成你的第一次声望",
    "Play for 1 hour": "玩1个小时",
    "Play for 10 hours": "玩10个小时",
    "Prestige Master": "声望大师",
    "Produce 10,000 total resources": "累计产出10000资源",
    "Reach level 10 with any building": "任意建筑达到10级",
    "Reach prestige level 5": "达到声望等级5",
    "Researcher": "研究员",
    "Stop at Level (0 = no limit)": "停止等级（0 = 无限制）",
    "Stop upgrading at this level (0 = no limit, max:": "在这个等级停止升级 (0 = 无限制，最大：",
    "🏢 Building Master": "🏢 建筑大师",
    "Lvl": "等级",
    "in queue)": "在队列中)",
    "• 200 Antimatter = 1 prestige point": "• 200反物质 = 1声望点数",
    "• 50 Singularity = 1 prestige point": "• 50奇点 = 1声望点数",
    "• Keep prestige points and upgrades": "• 保留声望点数和升级",
    "• Only available in late Singularity era (100+ singularity produced)": "• 仅在奇点时代后期可用（产生100+奇点）",
    "• Points earned from endgame buildings, research, and resource production": "• 从终局建筑、研究和资源生产中获得的点数",
    "• Requires at least 10 points to prestige": "• 声望至少需要10点",
    "• Reset most progress to gain permanent bonuses": "• 重置大部分进度可获得永久加成",
    "• Unlock new content and faster progression": "• 解锁新的内容和更快的进度",
    "⚠️ Banked points will be reset to 0 after you prestige": "⚠️ 获得声望后，银行积分将清零",
    "💡 Conversion Rates:": "💡 转化率:",
    "Active Bonuses": "活跃的加成",
    "Automation and intelligent machines": "自动化和智能机器",
    "available": "可用",
    "Banked Points": "银行点数",
    "Banked points are added to your total when you prestige": "当您获得声望时，银行积分将添加到您的总积分中",
    "Build Cooldown": "建造冷却",
    "Building Cooldown": "建筑冷却时间",
    "Building Cost": "建筑成本",
    "Can convert:": "可以转换:",
    "Clear All": "清除所有",
    "Controlled nuclear fusion and energy mastery": "控制核聚变和能量掌握",
    "Convert endgame resources into prestige points": "将游戏结束时的资源转换成声望点数",
    "Exotic matter and energy manipulation": "奇异物质和能量操纵",
    "Molecular engineering and nanotechnology": "分子工程和纳米技术",
    "Next ascension will grant powerful permanent bonuses...": "下一次转生将给予强大的永久加成...",
    "Not Enough": "不足",
    "Prestige Banking": "声望银行",
    "Prestige Level": "声望等级",
    "Prestige Points": "声望点数",
    "Prestige Upgrades": "声望升级",
    "Production Bonus": "生产加成",
    "Progress to Ascension": "转生进度",
    "Quantum physics and computing": "量子物理与计算",
    "Research Discount": "研究折扣",
    "Storage Bonus": "存储加成",
    "The Singularity": "奇点",
    "The Singularity - Prestige System": "奇点 - 声望系统",
    "What is Prestige?": "什么是声望？",
    "15% reduction in automation robot costs": "自动化机器人成本降低15%",
    "20% research speed bonus when 2+ research items queued": "2个以上科研物品排队时，科研速度提升20%",
    "Assemble circuits by hand with robotic assistance": "在机器人的帮助下用手组装电路",
    "Basic Automation": "基础自动化",
    "Build robots by hand using fusion-powered tools": "使用聚变动力工具手工构建机器人",
    "Computing Technology": "计算技术",
    "Consumes robots and circuits to maintain active rules": "消耗机器人和电路来维持主动规则",
    "Create plastic and glass using quantum-enhanced techniques": "使用量子增强技术制造塑料和玻璃",
    "Enables manual gathering of computers": "允许手动收集计算机",
    "Enables researching 2 items simultaneously (instead of 1)": "允许同时研究2个物品（而不是1个）",
    "Forge steel manually with precision techniques": "用精密技术手工锻造钢",
    "Manipulate quantum states by hand using singularity insights": "使用奇点洞察力手动操纵量子态",
    "Manual Electronics Assembly": "手动电子装配",
    "Manual Material Synthesis": "手工材料合成",
    "Manual Quantum Manipulation": "人工量子操纵",
    "Manual Robot Assembly": "手动机器人组装",
    "Manual Steelwork": "手工炼钢",
    "Quantum Computing": "量子计算",
    "Unlocks automation rules for buildings and research": "解锁建筑物和研究的自动化规则",
    "Unlocks Quantum Amplifier booster crafting": "解锁量子放大器助推器制作",
    "Unlocks quantum computing applications and advanced processing": "解锁量子计算应用和高级处理",
    "Unlocks the ability to create automation rules for your factory (consumes robots)": "解锁为您的工厂创建自动化规则的能力（消耗机器人）",
    "Manual Nanite Control": "手动纳米控制",
    "": "",
    "Direct nanite assembly through direct neural interface": "通过直接神经接口直接组装纳米粒子",
    "Base click power: 3x per click": "基础点击威力：3倍/次点击",
    "Basic Click Efficiency Complete!": "基础点击效率完成！",
    "Stone Tool Enhancement": "石制工具强化",
    "Triple the resources gained per click": "每次点击获得三倍的资源",
    "Enables Wood/Stone → Iron trading routes": "启用木头/石头→铁的贸易路线",
    "Establish trade routes for more resources": "建立贸易路线以获取更多资源",
    "Improved Trading": "改进交易",
    "🧪 Researcher": "🧪 研究员",
    "Iron Automation": "铁自动化",
    "10% cost reduction for Woodcutter, Stone Mine, Iron Mine, Copper Mine": "伐木工、石矿、铁矿、铜矿成本降低10%",
    "15% production boost for mining buildings": "采矿建筑产量提升15%",
    "25% reduction in robot costs for automation rules": "自动化规则的机器人成本降低25%",
    "5% cost discount per building in batch (max 25% for 5+ buildings)": "每栋建筑5%的批量成本折扣（5栋以上最多25%）",
    "50% reduction in robot costs for automation rules": "自动化规则的机器人成本降低50%",
    "Advanced Automation": "高级自动化",
    "Advanced Click Mechanics": "高级点击机制",
    "Advanced Materials": "高级材料",
    "Advanced Mining": "高级采矿",
    "Advanced Trading": "高级交易",
    "AI-powered automation with predictive capabilities (50% robot cost reduction)": "具有预测能力的人工智能自动化（机器人成本降低50%）",
    "Antimatter Automation": "反物质自动化",
    "Antimatter Click Annihilation": "反物质点击湮灭",
    "Automate antimatter collector operations": "自动化反物质收集器操作",
    "Automate circuit factory operations": "自动化电路工厂操作",
    "Automate computer factory operations": "自动化计算机工厂操作",
    "Automate copper mine operations": "铜矿自动化作业",
    "Automate fusion reactor operations": "聚变反应堆操作自动化",
    "Automate gear workshop operations": "齿轮车间操作自动化",
    "Automate glass factory operations": "玻璃厂操作自动化",
    "Automate iron mine operations": "铁矿作业自动化",
    "Automate lumber mill operations": "自动化伐木场操作",
    "Automate nanite factory operations": "自动化纳米工厂操作",
    "Automate plastic factory operations": "塑料工厂操作自动化",
    "Automate quantum lab operations": "自动化量子实验室操作",
    "Automate quarry operations": "采石场作业自动化",
    "Automate research completion": "自动完成研究",
    "Automate robot factory operations (meta-automation)": "自动化机器人工厂操作（元自动化）",
    "Automate steel furnace operations": "自动化炼钢炉操作",
    "Basic Combo System": "基本连击系统",
    "Circuit Automation": "电路自动化",
    "Click Mastery": "点击精通",
    "Click multiple resources simultaneously with reduced efficiency": "同时点击多个资源，降低效率",
    "Combo Mastery": "精通连击",
    "Computer Automation": "计算机自动化",
    "Computer Processing Enhancement": "增强计算机处理能力",
    "Control fusion reactions through enhanced consciousness": "通过增强意识控制聚变反应",
    "Copper Automation": "铜自动化",
    "Copper Conductive Tools": "铜导电工具",
    "Craft gears by hand using advanced techniques": "用先进的技术手工制作齿轮",
    "Create singularities through pure consciousness manipulation": "通过纯粹的意识操纵创造奇点",
    "Develop complex trade networks for advanced resources": "发展复杂的贸易网络，获取先进资源",
    "Each additional resource reduces efficiency": "每增加一个资源都会降低效率",
    "Electronic Click Accelerator": "电子点击加速器",
    "Enables Circuit, Glass, Computer, and Robot trading": "允许电路，玻璃，计算机和机器人交易",
    "Enables clicking multiple resources at the same time": "允许同时点击多个资源",
    "Enables combo multiplier for consecutive clicks on same resource": "为连续点击同一资源启用连击乘数",
    "Enables critical mining (chance for bonus resources)": "开启暴击采矿（有概率获得额外资源）",
    "Enables Efficiency Catalyst booster crafting": "可以制造效率催化剂助力器",
    "Enables Fusion, Antimatter, and Singularity trading": "启用聚变，反物质和奇点交易",
    "Enables Iron ⇄ Copper, Copper → Gear, Iron → Steel trading": "实现铁/铜、铜→齿轮、铁→钢的贸易",
    "Enables plastic and glass production": "可生产塑料和玻璃",
    "Enables Quantum Core and advanced resource trading": "启用量子核和高级资源交易",
    "Establish quantum-entangled trade networks": "建立量子纠缠贸易网络",
    "Establish worldwide trade networks for all resources": "为所有资源建立全球贸易网络",
    "Exotic Trading": "异域贸易",
    "Fusion Automation": "聚变自动化",
    "Fusion Click Energy": "聚变点击能量",
    "Gear Automation": "齿轮自动化",
    "Glass Automation": "玻璃自动化",
    "Global Trading": "全球贸易",
    "Harvest antimatter through transcendent understanding": "通过超然的理解收获反物质",
    "Improves automation efficiency and unlocks more complex rules (25% robot cost reduction)": "提高自动化效率，解锁更复杂的规则（机器人成本降低25%）",
    "Improves mining efficiency and unlocks advanced mining techniques": "提高采矿效率，解锁先进的采矿技术",
    "Intelligent Automation": "智能自动化",
    "Iron Reinforced Tools": "铁质强化工具",
    "Learn advanced techniques to manually extract iron and copper": "学习人工提取铁和铜的先进技术",
    "Learn how to create steel": "学习如何制造钢铁",
    "Manual Antimatter Harvesting": "人工反物质收集",
    "Manual Fusion Control": "手动聚变控制",
    "Manual Metalworking": "手动金属加工",
    "Manual Mining Techniques": "手工采矿技术",
    "Manual Singularity Creation": "手动创建奇点",
    "Mass Production": "大规模生产",
    "Master the art of manual gathering - 10x click power bonus": "掌握手工收集的艺术- 10倍点击能力奖励",
    "Maximum combo multiplier: 2x (at 50+ combo)": "最大连击倍率：2倍（50+连击）",
    "Mechanical Click Amplifier": "机械式咔嗒放大器",
    "Multi-Resource Clicking": "多资源点击",
    "Multiplies all manual gathering by 10x": "将所有人工收集乘以10倍",
    "Nanite Automation": "纳米自动化",
    "Nanite Click Replication": "纳米点击复制",
    "Plastic Automation": "塑料自动化",
    "Plastic Factory, Glass Factory": "塑料厂，玻璃厂",
    "Plastic, Glass": "塑料、玻璃",
    "Polymer Click Enhancement": "聚合物点击增强",
    "Quantum Automation": "量子自动化",
    "Quantum Click Manipulation": "量子点击操作",
    "Quantum Trading": "量子交易",
    "Research Automation": "研究自动化",
    "Robot Automation": "机器人自动化",
    "Robotic Click Automation": "机器人点击自动化",
    "Singularity Click Transcendence": "奇点点击超越",
    "Stacks with Advanced Automation for 62.5% total reduction": "先进自动化堆栈减少62.5%",
    "Stacks with Intelligent Automation for 62.5% total reduction": "与智能自动化叠加，累计减少62.5%",
    "Steel Automation": "钢铁自动化",
    "Steel Production": "钢铁生产",
    "Steel-Enhanced Collection": "钢增强收集",
    "Stone Automation": "石头自动化",
    "Stone Tool Enhancement Complete!": "石器工具增强完成！",
    "Trade in exotic matter and energy": "进行外来物质和能源的贸易",
    "Ultimate Combo": "终极连击",
    "Unlock advanced combo system and critical hits for manual gathering": "解锁手动收集的高级连击系统和暴击",
    "Unlock basic combo system for manual gathering (max 2x multiplier)": "解锁手动收集的基本连击系统（最大2倍乘数）",
    "Unlocks batch building construction": "解锁批量构建",
    "Unlocks batch production and improved factory efficiency": "解锁批量生产，提高工厂效率",
    "Unlocks critical hits: 3x reward with base 5% chance": "解锁暴击：3倍奖励，基础几率为5%",
    "Unlocks Resource Magnet booster crafting": "解锁资源磁铁助推器制作",
    "Visual feedback for combos and critical hits": "对连击和暴击的视觉反馈",
    "Wood Automation": "木头自动化",
    "(CD:": "(冷却时间:",
    "15 circuit, 10 gear, 25 iron, 20 copper": "15个电路，10个齿轮，25个铁，20个铜",
    "Active Effects": "积极的效果",
    "Doubles manual gathering for 3 minutes": "手动采集翻倍，持续3分钟",
    "PRESTIGE! (+": "声望! (+",
    "pts)": "点数)",
    "🌟 Ready for Ascension! 🌟": "🌟 转生已就绪! 🌟",
    "(MAX)": "(最大)",
    "Quantum Storage": "量子存储",
    "Exotic Storage": "异域存储",
    "Component Storage": "组件存储",
    "Stone Storage": "石头存储",
    "Wood Storage": "木头存储",
    "Metal Storage": "金属存储",
    "• All buildings will be reset": "• 所有建筑将被重置",
    "• All current prestige upgrades will be kept": "• 所有当前的声望升级将被保留",
    "• All research will be reset": "• 所有研究将被重置",
    "• All resources will be reset": "• 所有资源将被重置",
    "• Faster progression on next run": "• 在下一次运行中加快进程",
    "• Permanent multiplier bonuses": "• 永久乘数加成",
    "• Tutorial progress will be reset": "• 教程进度将被重置",
    "⚠️ Warning: This will reset your progress!": "⚠️ 警告：这将重置您的进度！",
    "✓ You will gain:": "✓ 你将获得：",
    "Confirm Prestige": "确认声望",
    "🔄 Reset & Prestige": "🔄 重置与声望",
    "Choose your prestige option:": "选择您的声望选项：",
    "Keep": "保留",
    "maintains your current upgrade choices.": "保持你目前的升级选择。",
    "refunds all upgrade points to redistribute them.": "退款所有升级点数重新分配。",
    "Reset": "重置",
    "Game saved successfully!": "游戏保存成功！",
    "Yes, Reset Game": "确定，重置游戏",
    "Are you sure you want to reset all progress? This cannot be undone!": "您确定要重置所有进度吗？这是无法挽回的！",
    "Game reset successfully. Starting fresh!": "游戏重置成功。重新开始！",
    "⏳ Queued": "⏳ 已排队",
    "🔨 Building": "🔨 建造",
    "Progress:": "进度:",
    "Total Levels:": "总等级:",
    "Total Time:": "总时间:",
    "Total Items:": "总项目:",
    "remaining": "剩余",
    "Building Queue Manager": "建造队列管理",
    "Drag items or use arrows to reorder • Active item cannot be moved": "拖动项目或使用箭头重新排序 • 活动项目无法移动",
    "Circuits and electronic components": "电路及电子元件",
    "Quantum Physics": "量子物理学",
    "Quantum Laboratory, Quantum Storage": "量子实验室，量子存储",
    "Unlocks quantum computing technology": "解锁量子计算技术",
    "📦 Available Boosters": "📦 可用助推器",
    "Booster Inventory": "助推器库存",
    "Craft Cost:": "制作成本:",
    "Duration": "持续时长",
    "⏱️ Cooldown:": "⏱️ 冷却时间:",
    "🔥 Active Effects": "🔥 激活效果",
    "ACTIVE": "激活中",
    "Time Remaining": "剩余时间",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Esc": "Esc",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "🏭": "🏭",
    "💱": "💱",
    "🔬": "🔬",
    "/": "/",
    "•": "•",
    "⚙️": "⚙️",
    "⚡": "⚡",
    "✕": "✕",
    "⭐": "⭐",
    "🏆": "🏆",
    "🏗️": "🏗️",
    "📊": "📊",
    "📦": "📦",
    "🔒": "🔒",
    "🔥": "🔥",
    "🤖": "🤖",
    "🪨": "🪨",
    "🪵": "🪵",
    "●": "●",
    "☢️": "☢️",
    "⚛️": "⚛️",
    "⛏️": "⛏️",
    "✓": "✓",
    "🌌": "🌌",
    "💥": "💥",
    "💻": "💻",
    "🔌": "🔌",
    "⏳": "⏳",
    "⏸️": "⏸️",
    "🛠️": "🛠️",
    "(-": "(-",
    "×": "×",
    "⚒️": "⚒️",
    "🔨": "🔨",
    "→": "→",
    "↑": "↑",
    "↓": "↓",
    "💰": "💰",
    "%": "%",
    "(⏸)": "(⏸)",
    "© 2025 Factory Works Idle": "© 2025 Factory Works Idle",
    "−": "−",
    "⌨️": "⌨️",
    "⏱️": "⏱️",
    "⏸": "⏸",
    "⚗️": "⚗️",
    "✅": "✅",
    "✨": "✨",
    "🌠": "🌠",
    "💡": "💡",
    "💾": "💾",
    "📈": "📈",
    "📱": "📱",
    "🖥️": "🖥️",
    "🧲": "🧲",
    "⏰⏰": "⏰⏰",
    "🌟🌟": "🌟🌟",
    "⏰": "⏰",
    "🎓": "🎓",
    "🏢": "🏢",
    "👨‍🔬": "👨‍🔬",
    "🖱️": "🖱️",
    "🥚": "🥚",
    "🧪": "🧪",
    "🚀": "🚀",
    "ℹ️": "ℹ️",
    "💎": "💎",
    "🌟": "🌟",
    "🔧": "🔧",
    "🦾": "🦾",
    "🧬": "🧬",
    "#": "#",
    "⋮": "⋮",
    "▲": "▲",
    "▼": "▼",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Stone Mine Queued!": "石头矿已排队！",
    "Iron Mine Queued!": "铁矿已排队！",
    "Copper Mine Queued!": "铜矿已排队！",
    "Woodcutter Queued!": "伐木工已排队！",
    "Stone Storage Queued!": "石头存储已排队！",
    "Wood Storage Queued!": "木头存储已排队！",
    "Unlocks resources: ": "解锁资源: ",
    "Unlocks buildings: ": "解锁建筑: ",
    "CRITICAL! x": "暴击! x",
    "🏆 ": "🏆 ",
    "Max discount reached ": "已达到最大折扣 ",
    "Max reduction reached ": "已达到最大减少 ",
    "⭐ ": "⭐ ",
    "Antimatter Collector Queued! ": "反物质收集器排队！",
    "Circuit Factory Queued! ": "电路工厂排队！",
    "Component Storage Queued! ": "组件存储排队！",
    "Computer Factory Queued! ": "计算机工厂排队！",
    "Exotic Storage Queued! ": "外来存储排队！",
    "Fusion Reactor Queued! ": "聚变反应堆排队！",
    "Gear Factory Queued! ": "齿轮工厂排队！",
    "Glass Factory Queued! ": "玻璃厂排队！",
    "High-Tech Storage Queued! ": "高科技存储排队！",
    "Metal Storage Queued! ": "金属仓库排队！",
    "Nanite Factory Queued! ": "纳米工厂排队！",
    "Plastic Factory Queued! ": "塑料工厂排队中！",
    "Quantum Laboratory Queued! ": "量子实验室排队！",
    "Quantum Storage Queued! ": "量子存储排队！",
    "Robot Factory Queued! ": "机器人工厂排队！",
    "Singularity Core Queued! ": "奇点核心排队！",
    "Steel Foundry Queued! ": "铸钢厂排队！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/s": "/秒",
    "% efficiency)": "% 效率)",
    " points needed": " 点数需要",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)s \(([\d\.]+)\%\)$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^x \(([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% per level$/, '+$1% 每级'],
    [/^\-([\d\.]+)\% per level \(max ([\d\.]+)\%\)$/, '-$1% 每级 (最大 $2%)'],
    [/^\+([\d\.]+)\% Production Speed$/, '+$1% 生产速度'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) min$/, '$1 分钟'],
    [/^([\d\.,]+)x Manual Gathering$/, '$1x 手动采集'],
    [/^([\d\.,]+)x Research Speed$/, '$1x 研究速度'],
    [/^([\d\.,]+)s total time$/, '$1秒 总时间'],
    [/^([\d\.,]+)s remaining • ([\d\.,]+)s total$/, '$1秒 剩余 • $2秒 总计'],
    [/^✨ \+([\d\.,]+) pts$/, '✨ +$1 点数'],
    [/^\+([\d\.,]+) Level$/, '+$1 等级'],
    [/^\+([\d\.,]+) Circuit$/, '+$1 电路'],
    [/^\+([\d\.,]+) Plastic$/, '+$1 塑料'],
    [/^\+([\d\.,]+) Steel$/, '+$1 钢'],
    [/^\+([\d\.,]+) Gear$/, '+$1 齿轮'],
    [/^\+([\d\.,]+) Glass$/, '+$1 玻璃'],
    [/^\+([\d\.,]+) Iron$/, '+$1 铁'],
    [/^\+([\d\.,]+) Copper$/, '+$1 铜'],
    [/^\+([\d\.,]+) Computer$/, '+$1 计算机'],
    [/^\+([\d\.,]+) Stone$/, '+$1 石头'],
    [/^\+([\d\.,]+) Wood$/, '+$1 木头'],
    [/^Upgrade \(([\d\.,]+) pts\)$/, '升级 ($1 点数)'],
    [/^Gain ([\d\.,]+) resources per click$/, '每次点击获得 $1 资源'],
    [/^Increase maximum combo multiplier to ([\d\.,]+)x$/, '提高最大连击乘数到 $1x'],
    [/^Increases maximum combo multiplier to ([\d\.,]+)x \(at ([\d\.,]+)\+ combo\)$/, '提高最大连击乘数到 $1x (在 $2+ 连击)'],
    [/^Maxed \(([\d\.,]+) pts\)$/, '最大 ($1 点数)'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Complete ([\d\.,]+) trades$/, '完成 $1 次交易'],
    [/^Complete ([\d\.,]+) research projects$/, '完成 $1 研究项目'],
    [/^Gather ([\d\.,]+) iron$/, '采集 $1 铁'],
    [/^Gather ([\d\.,]+) wood$/, '采集 $1 木头'],
    [/^Gather ([\d\.,]+) stone$/, '采集 $1 石头'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Base click power: (.+) per click$/, '基础点击力量：$1 每次点击'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);