//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Data": "数据",
    "Data Processing": "数据处理",
    "Energy": "能量",
    "Energy Boost": "能量提升",
    "Core System": "核心系统",
    "Generate Energy": "生成能量",
    "Node Info": "节点信息",
    "Click on a node to see details": "单击节点查看详细信息",
    "Manual Actions": "手动操作",
    "Network Basics": "网络基础",
    "Network Simulator": "网络模拟器",
    "Nodes Unlocked:": "解锁节点：",
    "Power Management": "电源管理",
    "Process Data": "处理数据",
    "Research Lab": "研究实验室",
    "Total Data:": "总数据：",
    "Total Energy:": "总能量:",
    "✓ Unlocked": "✓ 已解锁",
    "⛏️ Data Miner": "⛏️ 数据矿工",
    "Unlock": "解锁",
    "Firewall": "防火墙",
    "Effects": "效果",
    "Efficiency": "效率",
    "Data Miner": "数据矿工",
    "Cannot Afford": "负担不起",
    "Ascension": "转生",
    "Ascend": "转生",
    "🛡️ Firewall": "🛡️ 防火墙",
    "☀️ Solar Panel": "☀️ 太阳能电池板",
    "⚙️ Optimization": "⚙️ 优化",
    "⚡ Energy Boost": "⚡ 能量提升",
    "⚡ Voltage Regulator": "⚡ 稳压器",
    "❄️ Heat Sink": "❄️ 散热器",
    "🌐 Network Basics": "🌐 网络基础",
    "🌪️ Wind Turbine": "🌪️ 风力生成器",
    "🎭 Proxy Server": "🎭 代理服务器",
    "🎯 Simulation": "🎯 模拟",
    "🎲 Monte Carlo": "🎲 蒙特卡洛",
    "💫 Superconductor": "💫 超导体",
    "💾 Data Storage": "💾 数据存储",
    "📈 Efficiency I": "📈 效率 I",
    "📊 Data Processing": "📊 数据处理",
    "📡 Router": "📡 路由器",
    "📦 Data Cache": "📦 数据缓存",
    "🔀 Network Switch": "🔀 网络交换机",
    "🔃 Deduplication": "🔃 去重",
    "🔋 Battery Array": "🔋 电池阵列",
    "🔋 Generator Mk1": "🔋 生成器Mk1",
    "🔌 Generator Mk2": "🔌 生成器Mk2",
    "🔧 Power Management": "🔧 电源管理",
    "🔬 Research Lab": "🔬 研究实验室",
    "🔮 Core System": "🔮 核心系统",
    "🗄️ Database": "🗄️ 数据库",
    "🗜️ Compression": "🗜️ 压缩",
    "🧮 Algorithms": "🧮 算法",
    "🪫 Capacitor Bank": "🪫 电容器组",
    "🚀 Overclocking": "🚀 超频",
    "Advanced generator with improved output.": "先进的生成器与改进的输出。",
    "Algorithms": "算法",
    "Antimatter Reactor": "反物质反应堆",
    "Automatically mines data from the network.": "自动从网络中挖掘数据。",
    "Automations": "自动化",
    "Bandwidth": "带宽",
    "Basic energy generator. Produces energy automatically.": "基础能量发生器。自动产生能量。",
    "Battery Array": "电池阵列",
    "Better cooling for improved performance.": "更好的冷却，提高性能。",
    "Better manage your power resources.": "更好的管理自己的电力资源。",
    "Capacitor Bank": "电容器组",
    "Capture a star's entire energy output.": "捕获一颗恒星的全部能量输出。",
    "Compress data for efficient storage.": "压缩数据以提高存储效率。",
    "Compression": "压缩",
    "Connect multiple devices efficiently.": "高效连接多台设备。",
    "Connect to external networks.": "连接外部网络。",
    "Data Cache": "数据缓存",
    "Data Gen": "数据生成",
    "Data Lake": "数据湖",
    "Data Storage": "数据存储",
    "Data Warehouse": "数据仓库",
    "Database": "数据库",
    "Deduplication": "去重",
    "Deep Learning": "深度学习",
    "Description": "描述",
    "Develop efficient algorithms.": "开发高效的算法。",
    "Distribute network load evenly.": "均衡分配网络负载。",
    "Dyson Sphere": "戴森球",
    "Encryption": "加密",
    "Energy Gen": "能量生成",
    "Establish basic research capabilities.": "建立基础科研能力。",
    "Fast data retrieval with indexes.": "带索引的快速数据检索。",
    "Fusion Core": "聚变堆芯",
    "Gateway": "网关",
    "Generate energy from wind.": "利用风能发电。",
    "Generator Mk1": "生成器Mk1",
    "Generator Mk2": "生成器Mk2型",
    "Genetic Algorithm": "遗传算法",
    "Harness the power of the sun.": "利用太阳的能量。",
    "Heat Sink": "散热器",
    "Hide your network traffic.": "隐藏您的网络流量。",
    "Improves energy generation efficiency.": "提高能源生产效率。",
    "Increases manual energy generation.": "增加手动能量生成。",
    "Indexing": "索引",
    "Learn the fundamentals of networking.": "学习网络的基础知识。",
    "Load Balancer": "负载均衡器",
    "Machine Learning": "机器学习",
    "Massive data storage facility.": "海量数据存储设施。",
    "Massive energy production facility.": "大规模的能源生产设施。",
    "Massive energy storage system.": "巨大的能量存储系统。",
    "Monte Carlo": "蒙特卡洛",
    "Network Switch": "网络交换机",
    "Optimization": "优化",
    "Optimize all system processes.": "优化所有系统进程。",
    "Overclocking": "超频",
    "Parallel Process": "并行处理",
    "Plasma Conduit": "等离子体通道",
    "Probabilistic simulations.": "概率模拟。",
    "Process multiple data streams simultaneously.": "同时处理多个数据流。",
    "Protects your network and improves stability.": "保护您的网络，提高稳定性。",
    "Proxy Server": "代理服务器",
    "Push your systems beyond their limits.": "让你的系统超越极限。",
    "Quick access to frequently used data.": "快速访问常用数据。",
    "Remove duplicate data efficiently.": "有效地删除重复数据。",
    "Required for advanced networking nodes": "高级组网节点必备",
    "Required for advanced security": "需要高级安全性",
    "Required for advanced simulations": "需要高级模拟",
    "Required for security branch": "安全分支需要",
    "Requires": "需要",
    "Reset progress for permanent upgrades": "重置永久升级进度",
    "Router": "路由器",
    "Routes data more efficiently through your network.": "通过网络更有效地路由数据。",
    "Run simulations to predict outcomes.": "运行模拟来预测结果。",
    "Secure data transmission protocols.": "安全的数据传输协议。",
    "Simulation": "模拟",
    "Solar Panel": "太阳能电池板",
    "Stabilize power output.": "稳定功率输出。",
    "Starting node - unlocked by default": "启动节点-默认为未锁定",
    "Store and accumulate more data.": "存储和积累更多的数据。",
    "Store excess energy for later use.": "储存多余的能量以备后用。",
    "Structured data storage system.": "结构化数据存储系统。",
    "Superconductor": "超导体",
    "Teach machines to learn patterns.": "教机器学习模式。",
    "The central hub of your network. Everything begins here.": "网络的中心枢纽。一切都从这里开始。",
    "Unlock Bandwidth resource, +0.5 Bandwidth/s": "解锁带宽资源，+0.5带宽/秒",
    "Unlock Data Processing button": "解锁数据处理按钮",
    "Unlocks bandwidth as a new resource with passive generation.": "将带宽作为被动生成的新资源解锁。",
    "Unlocks research and upgrade paths": "解锁研究和升级路径",
    "Unlocks the ability to process data.": "解锁处理数据的能力。",
    "Vast unstructured data storage.": "庞大的非结构化数据存储。",
    "Voltage Regulator": "电压调整器",
    "Wind Turbine": "风力涡轮机",
    "Zero Point Energy": "零点能量",
    "Zero-resistance energy transfer.": "零阻力能量传递。",
    "Big Data": "大数据",
    "Bandwidth Gen": "带宽生成",
    "AI Core": "AI核心",
    "⚖️ Load Balancer": "⚖️ 负载均衡器",
    "🌑 Darknet Access": "🌑 暗网接入",
    "🏭 Data Warehouse": "🏭 数据仓库",
    "💀 Zero Day": "💀 零日",
    "📈 Efficiency": "📈 效率",
    "📑 Indexing": "📑 索引",
    "📶 Bandwidth": "📶 带宽",
    "🔀 Parallel Process": "🔀 并行进程",
    "🔐 Encryption": "🔐 加密",
    "🔒 VPN Tunnel": "🔒 V.P.N隧道",
    "🕸️ Mesh Network": "🕸️ 组网",
    "🤖 Machine Learning": "🤖 机器学习",
    "🧠 Neural Network": "🧠 神经网络",
    "🧬 Deep Learning": "🧬 深度学习",
    "🧬 Genetic Algorithm": "🧬 遗传算法",
    "🚪 Gateway": "🚪 网关",
    "3D data storage technology.": "3D数据存储技术。",
    "Access the hidden network.": "访问隐藏网络。",
    "AI-powered automation system.": "人工智能驱动自动化系统。",
    "Artificial General Intelligence.": "人工通用智能。",
    "Brain-inspired computing.": "大脑启发的计算。",
    "Content Delivery Network.": "内容交付网络。",
    "Darknet Access": "暗网接入",
    "Decentralized network topology.": "分散式网络拓扑。",
    "Distributed Computing": "分布式计算",
    "Evolution-based optimization.": "基于进化学的优化。",
    "Exploit unknown vulnerabilities.": "利用未知的漏洞。",
    "Extract energy from quantum vacuum.": "从量子真空中提取能量。",
    "Galactic Network": "银河网络",
    "Harness distributed processing power.": "利用分布式处理能力。",
    "Harness matter-antimatter annihilation.": "利用物质-反物质湮灭。",
    "Holographic Storage": "全息存储",
    "Instant communication via entanglement.": "通过纠缠进行即时通信。",
    "Instantly unlock one random locked node": "立即解锁一个随机锁定的节点",
    "Invisible network infrastructure.": "隐形的网络基础设施。",
    "Mesh Network": "网状网络",
    "Multi-layer neural processing.": "多层神经处理。",
    "Network spanning galaxies.": "跨越星系的网络。",
    "Neural Network": "神经网络",
    "Neural Processor": "神经处理器",
    "Process massive datasets.": "处理海量数据集。",
    "Quantum computing capabilities.": "量子计算能力。",
    "Quantum CPU": "量子处理器",
    "Quantum Link": "量子链接",
    "Quantum Sim": "量子模拟",
    "Secure encrypted tunnels.": "安全加密隧道。",
    "Shadow Network": "影子网络",
    "Simulate quantum systems.": "模拟量子系统。",
    "Super-heated plasma energy transfer.": "过热等离子体能量传递。",
    "VPN Tunnel": "V.P.N隧道",
    "Zero Day": "零日",
    "🌊 Data Lake": "🌊 数据湖",
    "🌐 Distributed Computing": "🌐 分布式计算",
    "📊 Big Data": "📊 大数据",
    "Contains all possible data.": "包含所有可能的数据。",
    "Omniscient DB": "全知数据库",
    "💠 Quantum CPU": "💠 量子CPU",
    "Quantum Memory": "量子内存条",
    "🧠 Neural Processor": "🧠 神经处理器",
    "Mind Upload": "心灵上传",
    "Transfer consciousness to the network.": "将意识转移到网络中。",
    "🌀 Multiverse Access": "🌀 多元宇宙访问",
    "🔗 Quantum Link": "🔗 量子链接",
    "🔮 Quantum Sim": "🔮 量子模拟",
    "🤖 AI Core": "🤖 AI核心",
    "Access parallel universes.": "进入平行宇宙。",
    "Beyond human intelligence.": "超越人类的智慧。",
    "Multiverse Access": "多元宇宙访问",
    "Superintelligence": "超智",
    "🌞 Dyson Sphere": "🌞 戴森球",
    "Extract energy from black holes.": "从黑洞中提取能量。",
    "Singularity Tap": "奇点丝锥",
    "Store data in quantum states.": "以量子态存储数据。",
    "☢️ Fusion Core": "☢️ 聚变堆芯",
    "⚛️ Antimatter Reactor": "⚛️ 反物质反应堆",
    "🌀 Zero Point Energy": "🌀 零点能量",
    "🔥 Plasma Conduit": "🔥 等离子体导管",
    "Cosmic Battery": "宇宙电池",
    "Forge new stars for energy.": "锻造新的能源之星。",
    "Stellar Forge": "恒星锻造",
    "Store universe-scale energy.": "储存宇宙尺度的能量。",
    "+15 per process, 2x all rates": "+15 每个进程, 2x 所有速率",
    "⭐ Stellar Forge": "⭐ 恒星锻造",
    "💿 Holographic Storage": "💿 全息存储",
    "🔋 Cosmic Battery": "🔋 宇宙电池",
    "Compile data into reality.": "将数据转化为现实。",
    "Reality Compiler": "现实编译器",
    "🌌 Galactic Network": "🌌 银河网络",
    "🌌 Reality Compiler": "🌌 现实编译器",
    "🌟 Superintelligence": "🌟 超智",
    "👤 Shadow Network": "👤 影子网络",
    "💎 Quantum Memory": "💎 量子存储器",
    "💭 Mind Upload": "💭 心灵上传",
    "📚 Omniscient DB": "📚 全知数据库",
    "🕳️ Singularity Tap": "🕳️ 奇点丝锥",
    "10x all rates, +100 per click": "10倍的所有费率，+100每点击",
    "Access the universal database of all knowledge.": "访问所有知识的通用数据库。",
    "Akashic Records": "阿卡西记录",
    "Collective consciousness of all networks.": "所有网络的集体意识。",
    "Hivemind": "蜂巢思维",
    "Omega Point": "欧米伽点",
    "Tap into the energy of the universe itself.": "挖掘宇宙本身的能量。",
    "The ultimate convergence of all intelligence.": "所有智慧的终极汇聚。",
    "Universal Energy": "宇宙能量",
    "Quantum Cores": "量子核心",
    "🌌 Ascension": "🌌 转生",
    "+50% all automation rates": "+50%所有自动化速率",
    "2x Quantum Cores earned": "获得2x量子核心",
    "Ascensions": "转生",
    "Auto-Clicker": "自动点击器",
    "Bandwidth Genesis": "带宽起源",
    "Click Power": "点击威力",
    "Core Multiplier": "核心乘数",
    "Cost Reduction": "降低成本",
    "Data Affinity": "数据亲和力",
    "Efficient Learning": "高效学习",
    "Eternal Generator": "永恒生成器",
    "Fastest Clear:": "最快通关：",
    "Genesis Protocol": "创世协议",
    "Headstart": "先手行动",
    "Instant Tier 1": "即时第1层",
    "Not enough cores": "核心不足",
    "Prestige Mastery": "声望精通",
    "Purchase": "购买",
    "Quantum Efficiency": "量子效率",
    "Quick Start": "快速启动",
    "Requirements not met": "未满足要求",
    "Requires:": "要求:",
    "Speed Research": "速度研究",
    "Start with +5 Energy": "初始能量+5",
    "Start with 3 random Tier 1 nodes": "从3个随机的一级节点开始",
    "Start with ALL Tier 1 nodes": "从所有1阶节点开始",
    "Start with Bandwidth unlocked": "从带宽解锁开始",
    "Start with Data Processing unlocked": "从解锁数据处理开始",
    "Start with Energy Boost unlocked": "从能量提升开启开始",
    "Tier 1-2 nodes cost 50% less": "1-2级节点成本降低50%",
    "Total Cores Earned:": "总核心数：",
    "Total Energy Earned:": "获得的总能量：",
    "Total Nodes Unlocked:": "已解锁节点总数：",
    "Welcome back! Earned resources while away.": "欢迎回来！在此期间获得的资源。",
    "✓ Purchased": "✓ 已购买",
    "✨ Click Power I": "✨ 点击威力I",
    "✨ Data Affinity": "✨ 数据亲和力",
    "✨ Efficient Learning": "✨ 高效学习",
    "✨ Headstart I": "✨ 先手行动",
    "✨ Quick Start": "✨ 快速开始",
    "✨ Speed Research": "✨ 速度研究",
    "🌍 CDN": "🌍 CDN",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "CDN": "CDN",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "⚡": "⚡",
    "🌐": "🌐",
    "📊": "📊",
    "🔧": "🔧",
    "🔬": "🔬",
    "🔮": "🔮",
    "☀️": "☀️",
    "☢️": "☢️",
    "⚖️": "⚖️",
    "⚙️": "⚙️",
    "🗄️": "🗄️",
    "🗜️": "🗜️",
    "🤖": "🤖",
    "🧬": "🧬",
    "🧮": "🧮",
    "🪫": "🪫",
    "🚀": "🚀",
    "🚪": "🚪",
    "🛡️": "🛡️",
    "💾": "💾",
    "🏭": "🏭",
    "💫": "💫",
    "🎲": "🎲",
    "🎯": "🎯",
    "🎭": "🎭",
    "🌞": "🌞",
    "🌪️": "🌪️",
    "🌀": "🌀",
    "🌊": "🌊",
    "🌌": "🌌",
    "❄️": "❄️",
    "✓": "✓",
    "⛏️": "⛏️",
    "⚛️": "⚛️",
    "🔋": "🔋",
    "🔃": "🔃",
    "📶": "📶",
    "📦": "📦",
    "📑": "📑",
    "📡": "📡",
    "📈": "📈",
    "🔀": "🔀",
    "🔥": "🔥",
    "🔌": "🔌",
    "🔐": "🔐",
    "🌍": "🌍",
    "🌑": "🌑",
    "💀": "💀",
    "💠": "💠",
    "💿": "💿",
    "🔒": "🔒",
    "🔗": "🔗",
    "🕸️": "🕸️",
    "🧠": "🧠",
    "👤": "👤",
    "📚": "📚",
    "💎": "💎",
    "💭": "💭",
    "🌟": "🌟",
    "🕳️": "🕳️",
    "⭐": "⭐",
    "✨": "✨",
    "🐝": "🐝",
    "📜": "📜",
    "🔱": "🔱",
    "✕": "✕",
    "🔄": "🔄",
    "✗": "✗",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "🔒 Locked: ": "🔒 未解锁: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " (passive)": " (被动)",
    " unlocked!": " 已解锁!",
    " purchased!": " 已购买!",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+) \/ ([\d\.]+)$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+) 💎$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\+([\d\.,]+) 💎$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^🌌 Ascended! (.+) Quantum Cores$/, '🌌 已转生! $1 量子核心'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^\+([\d\.]+)\/second$/, '+$1\/秒'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)x Data gains$/, '$1x 数据增益'],
    [/^([\d\.]+)x Data processing$/, '$1x 数据处理'],
    [/^([\d\.]+)x all passive rates$/, '$1x 所有被动速率'],
    [/^\-([\d\.]+)\% all node costs$/, '-$1% 所有节点成本'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Quantum Cores earned$/, '+$1% 获得的量子核心'],
    [/^\+([\d\.]+) Energy\/second$/, '+$1 能量/秒'],
    [/^\+([\d\.]+) Energy\/s from start$/, '+$1 能量/秒 从开始时'],
    [/^\+([\d\.]+) Energy\/s permanent$/, '+$1 能量/秒 永久性的'],
    [/^\+([\d\.]+) Bandwidth\/second$/, '+$1 带宽/秒'],
    [/^\+([\d\.]+) Bandwidth\/s$/, '+$1 带宽/秒'],
    [/^\+([\d\.]+) Data\/second$/, '+$1 数据/秒'],
    [/^\+([\d\.]+) Energy per click$/, '+$1 能量每次点击'],
    [/^\+([\d\.]+) Energy\/s, \+([\d\.]+) per click$/, '+$1 能量/秒, +$2 每点击'],
    [/^\+([\d\.]+) per click, \+([\d\.]+) Energy\/s$/, '+$1 每点击, +$2 能量/秒'],
    [/^\+([\d\.]+) per process, \+([\d\.]+) Data\/s$/, '+$1 每进程, +$2 数据/秒'],
    [/^\+([\d\.]+) per process, ([\d\.]+)x multiplier$/, '+$1 每进程, $2x 乘数'],
    [/^\+([\d\.]+) Bandwidth\/s, ([\d\.]+)x Data$/, '+$1 带宽/秒, $2x 数据'],
    [/^\+([\d\.]+) Bandwidth\/s, ([\d\.]+)x rates$/, '+$1 带宽/秒, $2x 速率'],
    [/^\+([\d\.]+) Data\/s, ([\d\.]+)x all rates$/, '+$1 数据/秒, $2x 所有速率'],
    [/^\+([\d\.]+) Bandwidth\/s, ([\d\.]+)x all rates$/, '+$1 带宽/秒, $2x 所有速率'],
    [/^\+([\d\.]+) Data\/s, ([\d\.]+)x multiplier$/, '+$1 数据/秒, $2x 乘数'],
    [/^\+([\d\.]+) Data\/s$/, '+$1 数据/秒'],
    [/^\+([\d\.]+) Energy, \+([\d\.]+) Data per click, ([\d\.]+)x rates$/, '+$1 能量, +$2 数据每次点击, $3x 速率'],
    [/^\+([\d\.]+) Energy and Data per action$/, '+$1 能量和数据每次动作'],
    [/^\+([\d\.]+) base Energy per click$/, '+$1 基础能量每次点击'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) \(costs ([\d\.,]+)⚡\)$/, '+$1  (成本 $2⚡)'],
    [/^\+([\d\.,]+)(.+) \(costs ([\d\.,]+)⚡\)$/, '+$1$2  (成本 $3⚡)'],
    [/^Unlock ([\d\.,]+) more Tier ([\d\.,]+) nodes$/, '需解锁 $1 个层级 $2 节点'],
    [/^Ascension ([\d\.,]+)$/, '转生 $1'],
    [/^Tier ([\d\.,]+)$/, '层级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^\+(.+) Data per process$/, '\+$1 数据每个进程'],
    [/^\+(.+) Data per process, (.+)x multiplier$/, '+$1 数据每个进程, $2x 乘数'],
    [/^\+(.+)\/second$/, '+$1/秒'],
    [/^\(\+([\d\.]+)(.+)\/s\)$/, '(+$1$2\/秒)'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);