/*

  汉化: 锅巴汉化 + wangshen + Git游戏

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类:
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Create a Home Gym": "建一个家庭健身房",
    "Create Competition": "创建竞赛",
    "Create Local Conference": "创建本地会议",
    "Create National Conference": "创建全国会议",
    "Create State-wide Conference": "创建州级会议",
    "Create World-wide Conference": "创建世界级会议",
    "Create Regional Conference": "创建地区会议",
    "Creating Classes": "创建课程",
    "Designing Ads": "设计广告",
    "Current:": "当前:",
    "Elite": "精英",
    "Endurance:": "耐力:",
    "Energy": "能量",
    "Energy max": "最大能量",
    "Energy recovery": "能量恢复",
    "Even More Loyalty": "更加忠诚",
    "Export Save": "导出存档",
    "Faster Training": "更快的训练",
    "Fastest Start": "最快的开始",
    "Faster Start": "更快的开始",
    "Fight Gang": "战斗团队",
    "Gym": "健身房",
    "Follower:": "粉丝:",
    "Follower Growth:": "粉丝增长:",
    "Gym Capacity:": "健身房容量:",
    "Gym Members:": "健身房会员:",
    "Work": "工作",
    "Workout": "锻炼",
    "World Class": "世界级",
    "Take a Free Marketing Course": "参加免费营销课程",
    "Try to Look Smarter": "尝试让自己看起来更聪明",
    "Type of Gym to Open": "开设健身房的类型",
    "Unlock Permanent Confidence": "解锁永久信心",
    "Strength:": "力量:",
    "Stop": "停止",
    "Submit": "提交",
    "Train Gang": "训练团队",
    "Training Members": "训练成员",
    "Views:": "播放量:",
    "World-wide Conferences": "全球会议",
    "Street workout gang members to go up faster, post-prestige": "街头健身团队成员提升更快，声望后",
    "Street workout gang strength to go up faster, post-prestige": "街头健身团队力量提升更快，声望后",
    "Stats": "属性",
    "Smarter Advertising": "更智能的广告",
    "Sort Comments by Best": "按最佳排序评论",
    "Speculate About Fitness": "关于健身的推测",
    "State-wide Conferences": "全州会议",
    "Still Insta-Famous": "仍然在 Instagram 上名声大噪",
    "Support Holds": "支撑保持",
    "Buy Coffee": "购买咖啡",
    "Subpar": "欠佳",
    "Buy Agility Supplements": "购买敏捷补充剂",
    "Buy Me Coffee": "请我喝咖啡",
    "Buy Creatine": "购买肌酸",
    "Buy Endurance Supplements": "购买耐力补充剂",
    "Buy Pullup Bar": "购买引体向上杆",
    "Buy Stronger Coffee": "购买浓咖啡",
    "Buy Wooden Gymnastic Rings": "购买木制体操环",
    "Clickbait Titles": "点击诱饵标题",
    "Code Bots": "代码机器人",
    "Conference Help": "会议帮助",
    "COMPETE!": "竞争！",
    "Cost:": "成本:",
    "Drink Coffee": "喝咖啡",
    "Dips": "臂屈伸",
    "Efficient Coding": "高效编码",
    "Effective Marketing": "有效的营销",
    "Flex Online": "弹性在线",
    "Film Squats": "拍摄深蹲",
    "Focused Training": "针对性训练",
    "Followers:": "粉丝:",
    "Get Sponsors": "获得赞助商",
    "Gang Members": "团队成员",
    "Gang Power": "团队实力",
    "Gang Workouts": "团队锻炼",
    "Gang Strength": "团队力量",
    "Gang Recruiting": "团队招聘",
    "Gang Colors": "团队颜色",
    "Global Upgrades": "全局升级",
    "Go Viral Accidentally": "不小心走红",
    "Good Business": "生意兴隆",
    "Good Investing": "良好的投资",
    "Guest Stars": "客座明星",
    "Half-Energy Bench": "半能量长凳",
    "Half-Energy Curls": "半能量弯举",
    "Confidence:": "信心:",
    "- Hire a\n                                            nutritionist to\n                                            increase the effectiveness of sales reps, trainers, and program\n                                            coordinators by": "-聘请营养师，通过以下方式提高销售代表、训练师和项目协调员的效率",
    "- A bit more expensive, but doubles energy recovery again.": "- 有点贵，但能量恢复又加倍。",
    "- Adception. Doubles views per follower.": "- 接受。 每个关注者的观看次数翻倍。",
    "- Allows you to periodically collect your earnings!": "- 允许您定期收取收入！",
    "- Always start with +1 of each advertising employee and +$50": "- 始终从每位广告员工的 +1 和 +50$ 开始",
    "- Always start with +1 of each gym employee and +$50": "- 始终从每个健身房员工的 +1 和 +50$ 开始",
    "- Always start with a flat $.10/s. This money is not affected by any doubling upgrades": "- 始终以固定的 $.10/s 开始。 这笔钱不受任何双倍升级的影响",
    "- Always start with an additional flat $.10/s. This money is not affected by any doubling upgrades.": "- 始终从额外的固定 $.10/s 开始。 这笔钱不受任何双倍升级的影响。",
    "- Always start with one of each gym employee and +$10.": "- 始终从每位健身房员工一名开始，并 + 10 $。",
    "- Annoy some followers by livestreaming pushups all day. Adds a portion of your total pushups to your follower growth.": "- 全天直播俯卧撑，惹恼一些粉丝。 将您的俯卧撑总数的一部分添加到您的关注者增长中。",
    "- Annoy some followers by livestreaming rows all day. Adds a portion of your total rows to your follower growth.": "- 整天直播争吵，惹恼一些粉丝。 将总行数的一部分添加到您的关注者增长中。",
    "- Ask questions online so they can do your research. Doubles research speed.": "- 在线提问，以便他们为您进行研究。 研究速度加倍。",
    "- Auto-Absorb Gangs (toggle in options tab).": "- 自动吸收团队（在选项选项卡中切换）。",
    "- Autobuy Conferences (toggle in options tab).": "- 自动购买会议（在选项选项卡中切换）。",
    "- Autoclicks coffee (toggle in options tab).": "- 自动点击咖啡（在选项选项卡中切换）。",
    "- Bench gives double stats per bar fill.": "- 长凳为每次进度条填充提供双倍属性。",
    "- Bench uses half the energy.": "- 长凳使用一半的能量。",
    "- Bot growth is doubled.": "- 机器人增长翻倍。",
    "- Bring some important people into the channel to discuss with me. Intelligence gain is doubled from research.": "- 邀请一些重要的人进入频道与我讨论。 研究的智力增益加倍。",
    "- Buy ad coordinators as they become available (toggle in options tab).": "- 购买可用的广告协调员（在选项选项卡中切换）。",
    "- Buy ad designers as they become available (toggle in options tab).": "- 购买可用的广告设计师（在选项选项卡中切换）。",
    "- Buy advertising upgrades as they become available (toggle in options tab).": "- 购买可用的广告升级（在选项选项卡中切换）。",
    "- Buy gym upgrades as they become available (toggle in options tab).": "- 购买可用的健身房升级（在选项选项卡中切换）。",
    "- Buy marketing managers as they become available (toggle in options tab).": "- 购买可用的营销经理（在选项选项卡中切换）。",
    "- Buy nutritionists as they become available (toggle in options tab).": "- 在营养师可用时购买他们（在选项选项卡中切换）。",
    "- Buy program coordinators as they become available (toggle in options tab).": "- 购买可用的项目协调员（在选项选项卡中切换）。",
    "- Buy sales reps as they become available (toggle in options tab).": "- 在销售代表可用时购买他们（在选项选项卡中切换）。",
    "- Buy trainers as they become available (toggle in options tab).": "- 购买可用的训练鞋（在选项选项卡中切换）。",
    "- Buy workout upgrades as they become available (toggle in options tab).": "- 购买可用的锻炼升级（在选项选项卡中切换）。",
    "- Carefully place products in my videos. Double the views per follower.": "- 小心地将产品放入我的视频中。 每个关注者的观看次数翻倍。",
    "- Change all of your video titles to scare people into clicking. Views go up faster per follower.": "- 更改所有视频标题以吓唬人们点击。 每个关注者的观看次数上升得更快。",
    "- Choose which tier to focus on for trainers.": "- 选择训练师要关注的级别。",
    "- Confidence gained from absorbing gangs provides a permanent 2% per point boost to all gym functions.": "- 通过吸收团队而获得的信心为所有健身房功能提供永久的每点 2% 的提升。",
    "- create a\n                                        local conference to generate competitions": "- 创建一个本地会议来开展竞赛",
    "- create a\n                                        national conference to generate state-wide conferences": "- 创建\n全国会议以产生全州范围的会议",
    "- create a\n                                        regional conference to generate local conferences": "- 创建\n区域会议以产生本地会议",
    "- create a\n                                        state-wide conference to generate regional conferences": "- 创建一个全州范围的会议以产生区域会议",
    "- create a\n                                        world-wide conference to generate national conferences. The first 10 purchased give .1 leadership each.": "- 创建\n世界范围的会议以产生国家会议。 前 10 个购买的每个给予 0.1 领导力。",
    "- Creatine will double your energy recovery.": "- 肌酸将使您的能量恢复加倍。",
    "- Curls give double stats per bar fill.": "- 弯举为每次进度条填充提供双倍属性。",
    "- Curls use half the energy.": "- 弯举消耗一半的能量。",
    "- Deadlifts give double stats per bar fill.": "- 硬拉为每次进度条填充提供双倍属性。",
    "- Deadlifts use half the energy.": "- 硬拉消耗一半的能量。",
    "- Dips give double stats per bar fill.": "- 臂屈伸为每次进度条填充提供双倍属性。",
    "- Dips use half the energy.": "- 臂屈伸使用一半的能量。",
    "- Double Adception. Doubles money growth.": "- 双重接受。 货币增长翻倍。",
    "- Double energy expenditure of bodyweight leg exercises, but double stat gains as well.": "- 自重腿部练习的能量消耗加倍，但属性增益也加倍。",
    "- Double energy expenditure of dips and pullups, but double stat gains as well.": "- 臂屈伸和引体向上的能量消耗加倍，但属性增益也加倍。",
    "- Double energy expenditure of pushups and rows, but double stat gains as well.": "- 俯卧撑和划船的能量消耗加倍，但属性增益也加倍。",
    "- Double energy recovery and max energy": "- 双倍能量回收和最大能量",
    "- Double member recruitment for the gang.": "- 团队招募双重成员。",
    "- Double strength gain for the gang.": "- 团队力量加倍。",
    "- Double the intelligence growth of research.": "- 研究的智力增长加倍。",
    "- Doubles agility modifier.": "- 双倍敏捷修饰语。",
    "- Doubles endurance modifier.": "- 双倍耐力修正。",
    "- Doubles gym and advertising modifier (all stats).": "- 双打健身房和广告修改器（所有属性）。",
    "- Doubles intelligence modifier.": "- 双倍智力调整值。",
    "- Doubles starting gym capacity.": "- 健身房起始容量增加一倍。",
    "- Doubles strength modifier.": "- 双倍力量修正。",
    "- Doubles the intelligence generation of advertising.": "- 广告智能生成加倍。",
    "- Doubles trainer effectiveness.": "- 使教练效率加倍。",
    "- Eat big to get big. Doubles energy recovery.": "- 吃大点才能变大。 能量回收加倍。",
    "- Everyone loves a contest. Adds pullups to follower growth.": "- 每个人都喜欢比赛。 为粉丝增长添加引体向上。",
    "- Everyone loves ads! Double your money per view.": "- 每个人都喜欢广告！ 每次观看的费用双倍。",
    "- Everyone wants to see some squats. Adds squats to follower growth.": "- 每个人都想看一些深蹲。 增加深蹲以促进粉丝的成长。",
    "- First impressions count. Doubles intelligence from research.": "- 第一印象很重要。 研究的智力加倍。",
    "- Get influencers researching too. Doubles research speed.": "- 让有影响力的人也进行研究。 研究速度加倍。",
    "- Get that heart rate up! Doubles the effectiveness of agility.": "- 提高心率！ 使敏捷性的有效性加倍。",
    "- Get that sweet money. Doubles views per follower.": "- 得到那笔甜蜜的钱。 每个关注者的观看次数翻倍。",
    "- Hire a\n                                                marketing manager to increase the effectiveness of ad coordinators and\n                                                ad designers by": "- 聘请一名营销经理来提高广告协调员和广告设计师的效率",
    "- Hire a program\n                                            coordinator to\n                                            offer classes that increase money per member": "- 聘请一名计划\n协调员\n提供可增加每位会员收入的课程",
    "- Hire a sales\n                                            representative to increase the\n                                            speed of recruiting new members": "- 聘请销售代表以提高\n招募新会员的速度",
    "- Hire a trainer to\n                                            increase the\n                                            speed of training gym members": "- 聘请教练\n提高\n训练健身房会员的速度",
    "- Hire an\n                                                Ad Coordinator to run ad campaigns.": "- 聘请\n 广告协调员来开展广告活动。",
    "- Hire an ad\n                                                designer to design ads.": "- 聘请广告设计师来设计广告。",
    "- How are they monetizing their channel? Double your money growth.": "- 他们如何通过频道获利？ 让你的金钱增长双倍。",
    "- How do these people do it. There must be some secret. Doubles the influencer multiplier on follower growth.": "- 这些人是怎么做到的？ 一定有什么秘密。 粉丝增长的影响者乘数翻倍。",
    "- How does my friend know I have all this money. Is he a follower of mine? Doubles Squat Speed.": "- 我的朋友怎么知道我有这么多钱。 他是我的粉丝吗？ 加倍臂屈伸速度。",
    "- How to build endurance. Doubles the effectiveness of endurance.": "- 如何增强耐力。 耐力的有效性加倍。",
    "- How to build muscle. Doubles the effectiveness of strength.": "- 如何增强肌肉。 力量的有效性加倍。",
    "- I am one with the universe. Doubles the effectivess of intelligence.": "- 我与宇宙合一。 使智力的效率加倍。",
    "- I must learn the secrets of the dark side. Double views per follower.": "- 我必须了解黑暗面的秘密。 每个关注者的观看次数双倍。",
    "- I need to get coordinated to bring more followers into my channel. Double influencer growth.": "- 我需要进行协调，以吸引更多关注者进入我的频道。 影响力双倍增长。",
    "- I'm becoming an influencer. Double the effectiveness of stats on follower growth.": "- 我正在成为一名有影响力的人。 将关注者增长属性的有效性提高一倍。",
    "- I'm flying! Unlocks Pullups.": "- 我在飞！ 解锁引体向上。",
    "- I'm getting buff. Doubles the influence of stats on follower growth.": "- 我变黄了。 属性对关注者增长的影响加倍。",
    "- I'm seriously getting mad at this guy. Doubles dip speed.": "- 我真的很生这个家伙的气。 臂屈伸速度加倍。",
    "- Increase energy with coffee": "- 用咖啡补充能量",
    "- Increases follower growth based on all stats.": "- 根据所有属性增加粉丝增长。",
    "- Is this deserved? Always start with one of each advertising employee and +$10.": "- 这是应得的吗？ 始终从每位广告员工开始，并+ 10$。",
    "- It's time to get serious about sleep hygiene. Double your energy recovery.": "- 是时候认真对待睡眠卫生了。 双倍能量恢复。",
    "- Leadership gained from creating world-wide conferences provides a permanent 2% per point boost to all stat gain.": "- 通过举办世界范围的会议获得的领导力为所有属性增益提供永久的每点 2% 的提升。",
    "- Learning to flex your smarts online will add your strength modifier to post growth.": "- 学习在线发挥你的聪明才智将为你的成长后添加力量调节剂。",
    "- Lifting weights provide double the modifier for competitions.": "- 举重为比赛提供双倍的修正。",
    "- Market to your audience. Doubles views per follower.": "- 向您的受众进行营销。 每个关注者的观看次数翻倍。",
    "- Market your channel in your posts to double follower growth.": "- 在帖子中推销您的频道，使关注者数量翻倍。",
    "- Maybe he's trying to launch a competing channel? Doubles Romanian Deadlift Speed.": "- 也许他正在尝试推出一个竞争频道？ 罗马尼亚硬拉速度加倍。",
    "- Maybe I'll make things more scientific. Adds a portion of your total posts to follower growth.": "- 也许我会让事情变得更科学。 将帖子总数的一部分添加到关注者增长中。",
    "- Mounted rings should give me a more stable platform for dips. Halves the energy expenditure of dips.": "- 安装环应该为我提供更稳定的双杠臂屈伸平台。 将双臂屈伸的能量消耗减半。",
    "- My friend keeps wanting more money. Doubles pullup speed.": "- 我的朋友一直想要更多的钱。 上拉速度加倍。",
    "- My friend wants to show me the correct way to do pushups and rows. Halves the energy expenditure of pushups and rows.": "- 我的朋友想向我展示做俯卧撑和划船的正确方法。 将俯卧撑和划船的能量消耗减半。",
    "- No bad comments allowed. Doubles research speed.": "- 不允许发表任何不好的评论。 研究速度加倍。",
    "- No one can ever do romanian deadlifts correctly. I'll show them. Adds romanian deadlifts to follower growth.": "- 没有人能正确地做罗马尼亚硬拉。 我会告诉他们。 增加罗马尼亚硬拉以促进粉丝的增长。",
    "- No one will ever realize I'm talking nonsense. Double your work speed.": "- 没有人会意识到我在胡说八道。 让你的工作速度加倍。",
    "- Not sure what happened. Adds 5000 views": "- 不知道发生了什么。 增加 5000 次观看",
    "- Overhead press gives double stats per bar fill.": "- 过顶推举每条填充提供双倍属性。",
    "- Overhead press uses half the energy.": "- 过头推举使用一半的能量。",
    "- Placing ads on my influencer's pages will add to follower growth per influencer.": "- 在我的影响者的页面上放置广告将增加每个影响者的粉丝增长。",
    "- Pose for the camera! Doubles the stat modifier for follower growth.": "- 对着镜头摆好姿势！ 粉丝增长的属性修饰语加倍。",
    "- Protein shakes let you build strength faster. Why get your protein from chicken when you can drink it. Makes strength more effective.": "- 蛋白质奶昔让您更快增强力量。 既然可以喝鸡肉，为什么还要从鸡肉中获取蛋白质呢？ 让力量更加有效。",
    "- Pullups give double stats per bar fill.": "- 引体向上每条填充提供双倍属性。",
    "- Pullups use half the energy.": "- 引体向上使用一半的能量。",
    "- Pushup handles should double my pushup speed. That's how physics work.": "- 俯卧撑手柄应该使我的俯卧撑速度加倍。 这就是物理学的原理。",
    "- Pushups give double stats per bar fill.": "- 俯卧撑每条填充提供双倍属性。",
    "- Pushups use half the energy.": "- 俯卧撑消耗一半的能量。",
    "- Recruit influencers to increase follower growth.": "- 招募有影响力的人以增加粉丝的增长。",
    "- Refine the code. Doubles the effect of bots on post growth.": "- 完善代码。 使机器人对后期增长的影响加倍。",
    "- Romanian Deadlifts give double stats per bar fill.": "- 罗马尼亚硬拉每条填充提供双倍属性。",
    "- Romanian Deadlifts use half the energy.": "- 罗马尼亚硬拉消耗一半的能量。",
    "- Rows give double stats per bar fill.": "- 每次划船进度条填充给出双倍属性。",
    "- Rows use half the energy.": "- 划船消耗一半的能量。",
    "- Seems reasonable. Halves the energy expenditure of bodyweight leg exercises.": "- 看起来很合理。 将自重腿部练习的能量消耗减半。",
    "- Squats give double stats per bar fill.": "- 深蹲每条填充提供双倍属性。",
    "- Squats use half the energy.": "- 深蹲消耗一半的能量。",
    "- Stop being a bro. Unlocks squats and romanian deadlifts.": "- 别再当兄弟了。解锁深蹲和罗马尼亚硬拉。",
    "- Strength, endurance, agility, and intelligence all have 10 added at the start.": "- 力量、耐力、敏捷和智力一开始都增加了 10。",
    "- Strength, endurance, agility, and intelligence all have 100 added at the start": "- 力量、耐力、敏捷和智力一开始都增加了 100",
    "- Supplements should give my agility more of an impact.": "- 补充剂应该对我的敏捷性产生更大的影响。",
    "- Supplements should give my endurance more of an impact.": "- 补充剂应该对我的耐力产生更大的影响。",
    "- Supplements should give my intelligence more of an impact.": "- 补充剂应该对我的智力产生更大的影响。",
    "- Thanks internet! Doubles follower growth.": "- 感谢互联网！ 粉丝增长翻倍。",
    "- The best sorting is best. Double your research speed.": "- 最好的排序是最好的。 双倍你的研究速度。",
    "- These cheaply made gymnastic rings should let me do rows. Once I do some research, I should be able to do dips too.": "- 这些廉价的体操环应该可以让我划船。 一旦我做了一些研究，我也应该能够做双臂屈伸。",
    "- These nice, wooden made gymnastic rings should let me do rows at double speed.": "- 这些漂亮的木制体操环应该可以让我以双倍速度划船。",
    "- This won't annoy anyone! Doubles money growth.": "- 这不会惹恼任何人！ 货币增长翻倍。",
    "- Unlock competitions.": "- 解锁比赛。",
    "- Unlock lifting gyms.": "- 解锁举重健身房。",
    "- Unlock Open Gym (prestige).": "- 解锁开设健身房（声望）。",
    "- Unlock street workout gangs.": "- 解锁街头健身团队。",
    "- Unlocks research.": "- 解锁研究。",
    "- Very expensive, but doubles the effectiveness of agility.": "- 非常昂贵，但敏捷性的有效性加倍。",
    "- Very expensive, but doubles the effectiveness of endurance.": "- 非常昂贵，但耐力效果加倍。",
    "- Very expensive, but doubles the effectiveness of intelligence.": "- 非常昂贵，但使智力的有效性加倍。",
    "- Very expensive, but doubles the effectiveness of strength.": "- 非常昂贵，但力量效果加倍。",
    "- Well, maybe not everyone loves a contest. I love contests. Adds dips to follower growth.": "- 好吧，也许不是每个人都喜欢比赛。 我喜欢比赛。 增加粉丝增长的臂屈伸。",
    "- When I dip you dip we dip. Unlocks dips.": "- 当我臂屈伸你臂屈伸时我们臂屈伸。 解锁跌幅。",
    "- With bots, I can read posts faster. Unlocks Code Bots.": "- 有了机器人，我可以更快地阅读帖子。 解锁代码机器人。",
    "- With proper equipment, anything is possible. Halves the energy expenditure of pullups.": "- 有了适当的设备，一切皆有可能。 将引体向上的能量消耗减半。",
	"- Work with influencers to go 'viral'. Doubles the recruitment of influencers.": "- 与有影响力的人合作，“病毒式传播”。 影响力人物的招募数量翻倍。",
    "- Yelling always makes people love you. Doubles follower growth.": "- 大喊大叫总是让人爱你。 粉丝增长翻倍。",
    "- You might miss some important facts, but it's just fitness. Doubles post read speed.": "- 你可能会错过一些重要的事实，但这只是健身。 帖子阅读速度加倍。",
    "You have successfully vanquished all other street workout gangs. Your gang now\n                                        consists of a variety of strange individuals all focused on getting gainz.": "你已经成功击败了所有其他街头健身团队。 你的团队现在\n由各种奇怪的人组成，他们都专注于获取增益。",
    "x all stat modifier": "x 所有属性修饰语",
    "(Resting)": "(休息中)",
    "% each.": "% 每个.",
    ".\n                                        Agility modifier helps:": ".\n 敏捷修饰语有助于:",
    ".\n                                        Intelligence modifier helps:": ".\n 智力修饰语有助于:",
    ". All\n                                        stat modifier helps:": "。 全部\n 属性修饰语有助于:",
    ". Endurance modifier helps:": "。 耐力修改器有助于:",
    ". Strength modifier helps:": "。 力量调节剂有助于:",
    "Ad Campaign Growth:": "广告活动增长:",
    "Ad Campaigns:": "广告活动:",
    "Ads Designed:": "广告设计:",
    "Ads Within Ads": "广告中的广告",
    "Ads Within Ads Within Ads": "广告中的广告 广告中的广告",
    "Advanced": "高级",
    "Advanced Research Techniques": "先进的研究技术",
    "Advertise with Influencers": "与有影响力的人一起做广告",
    "Agility:": "敏捷:",
    "All gym and advertising jobs except nutritionists and marketing\n                                                managers, post-prestige": "所有健身房和广告工作，除了营养师和营销经理\n、后期声望",
    "All stat gain from exercise and research/advertising": "所有属性均来自锻炼和研究/广告",
    "Arch Hangs": "拱门悬挂",
    "Assisted Squat": "辅助臂屈伸",
    "Autobuy Ad Coordinators": "自动购买广告协调员",
    "Autobuy Ad Designers": "自动购买广告设计师",
    "Autobuy Advertising Upgrades": "自动购买广告升级",
    "Autobuy Gym Upgrades": "自动购买健身房升级",
    "Autobuy Marketing Managers": "自动购买营销经理",
    "Autobuy Nutritionists": "自动购买营养师",
    "Autobuy Program Coordinators": "自动购买计划协调员",
    "Autobuy Sales Reps": "自动购买销售代表",
    "Autobuy Trainers": "自动购买训练师",
    "Autobuy Workout Upgrades": "自动购买锻炼升级",
    "Better Form for Bodyweight Legs Exercises": "更好的自重腿部练习形式",
    "Better Form for Dips and Pullups": "更好的双臂屈伸和引体向上动作",
    "Better Form for Pushups and Rows": "更好的俯卧撑和划船动作",
    "Bigger Starting Locations": "更大的起始地点",
    "Bodyweight\n                                            Point(s)": "体重\n点数",
    "Bodyweight Upgrades": "体重升级",
    "Bots:": "机器人:",
    "Braniac": "布拉尼亚克",
    "Bring Research into Videos": "将研究融入视频中",
    "Browse Reddit Posts About\n                                        Fitness": "浏览有关健身的 Reddit 帖子\n",
    "Buy Intelligence Supplements": "购买智力补充剂",
    "Buy L-Citrulline in Bulk": "批量购买 L-瓜氨酸",
    "Class Multiplier on Money/s:": "货币类别乘数:",
    "Classes:": "课程:",
    "Collect Revenue": "收取收入",
    "Compete in Dip Contest": "参加双臂屈伸比赛",
    "Compete in Pullup Contest": "参加引体向上比赛",
    "Competition Money Multiplier:": "竞争资金乘数:",
    "Competition Strength": "竞争实力",
    "competitions": "比赛",
    "Competitions": "比赛",
    "Coordinate Better with Influencers": "与影响者更好地协调",
    "Copy/paste the text below into a different browser to import, or save it to a text\n                                    file for safe keeping.": "将下面的文本复制/粘贴到其他浏览器中进行导入，或将其保存到文本文件中以便安全保存。",
    "Cost: $": "费用:$",
    "Double Stat Bench": "双倍属性长凳",
    "Double Stat Curls": "双倍属性弯举",
    "Double Stat Deadlifts": "双倍属性硬拉",
    "Double Stat Dips": "双倍属性臂屈伸",
    "Double Stat Overhead press": "Double Stat 过头推举",
    "Double Stat Pullups": "双倍属性引体向上",
    "Double Stat Pushups": "双倍属性俯卧撑",
    "Double Stat Romanian Deadlifts": "双倍属性罗马尼亚硬拉",
    "Double Stat Rows": "双倍属性划船",
    "Double Stat Squats": "双倍属性深蹲",
    "Drink\n                        Coffee": "喝\n咖啡",
    "Edit Gang\n                                            Name": "编辑团队\n名称",
    "Examine Your Beliefs": "检查你的信念",
    "Exceptional": "卓越",
    "Exercise progressions to go up faster (multiplier * 1 for number of\n                                                reps)": "锻炼进展速度更快（重复次数的乘数 * 1）",
    "Experimental Supplements for Agility": "敏捷实验补充剂",
    "Experimental Supplements for Endurance": "耐力实验补充剂",
    "Experimental Supplements for Intelligence": "智力实验补充剂",
    "Experimental Supplements for Strength": "实验性力量补充剂",
    "Film Romanian Deadlifts": "拍摄罗马尼亚硬拉",
    "Follower growth, pre-prestige": "粉丝增长，预声望",
    "Gang": "团队",
    "Global\n                                            Point(s)": "全局\n点数",
    "Half-Energy Deadlifts": "半能量硬拉",
    "Half-Energy Dips": "半能量臂屈伸",
    "Half-Energy Overhead Press": "半能量过头推举",
    "Half-Energy Pullups": "半能量引体向上",
    "Half-Energy Pushups": "半能量俯卧撑",
    "Half-Energy Romanian Deadlifts": "半能量罗马尼亚硬拉",
    "Half-Energy Rows": "半能量划船",
    "Half-Energy Squats": "半能量深蹲",
    "Hide Downvoted Posts": "隐藏被否决的帖子",
    "High Intensity Interval Training": "高强度间歇训练",
    "High Reps": "高次数",
    "Hire\n                                                Ad\n                                                Designer": "雇用\n 广告\n 设计师",
    "Hire\n                                                Ad Coordinator": "雇用\n广告协调员",
    "Hire\n                                                Marketing Manager": "聘请\n营销经理",
    "Hire\n                                            Nutritionist": "聘请\n营养师",
    "Hire Program\n                                            Coordinator": "雇用计划\n 协调员",
    "Hire Sales\n                                            Representative": "雇用销售\n 代表",
    "Hire Trainer": "聘请训练师",
    "Homemade Gymnastic Rings": "自制体操环",
    "Homemade Pushup Handles": "自制俯卧撑手柄",
    "Hypertrophy": "肥大",
    "Idle Gainz": "健身放置",
    "Import Save": "导入存档",
    "Incline Pushups": "上斜俯卧撑",
	"Pushups": "俯卧撑",
	"Horizontal Rows": "水平划船",
    "Incline Rows": "上斜划船",
    "Influence:": "影响:",
    "Influencers:": "影响者:",
    "Intelligence:": "智力:",
    "Intermediate": "中级",
    "Intravenous Coffee": "静脉注射咖啡",
    "Leadership:": "领导:",
    "Learn Speed Reading": "学习快速阅读",
    "Leg Day": "腿部日",
    "Lifting\n                                            Point(s)": "举重\n点数",
    "Lifting Competitions and Conferences": "举重比赛和会议",
    "Lifting Gyms": "举重健身房",
    "Lifting Upgrades": "举重升级",
    "Livestream Pushups": "直播俯卧撑",
    "Livestream Rows": "直播划船",
    "Load": "加载",
    "Local Conferences": "地方会议",
    "Long-Lasting": "持久",
    "Loyal Employees": "忠诚的员工",
    "Make Misleading Claims": "做出误导性声明",
    "Make YouTube Videos About Exercise": "制作有关锻炼的 YouTube 视频",
    "Meditation": "冥想",
    "Member Breakdown": "会员分类",
    "Modifiers": "修饰语",
    "Money:": "现金:",
    "More Effective Bots": "更有效的机器人",
    "More Loyalty": "更多忠诚度",
    "Most Loyalty": "最忠诚",
    "Mount Rings and Expand Home Gym": "安装环并扩展家庭健身房",
    "National Conferences": "全国会议",
    "Novice": "新手",
    "On Reset:": "重置时:",
    "Open a\n                                            Lifting\n                                            Gym": "开设\n举重\n健身房",
    "Open a Bodyweight\n                                            Fitness Gym": "开设体重\n健身馆",
    "Open Gym": "开放健身房",
    "Opening a gym will grant points from the previous gym and reset your game. These\n                                    points can be spent on global upgrades as well as exercise specific upgrades.": "开设健身房将获得之前健身房的点数并重置你的游戏。 这些点数可用于全局升级以及进行特定升级。",
    "Opening a New Gym": "开设新健身房",
    "Owned:": "拥有:",
    "Pay a Friend to Teach You": "花钱请朋友来教你",
    "Pay Day!": "发薪日！",
    "Pay for Dip Training": "支付臂屈伸训练费用",
    "Pay for Leg Hypertrophy Guide": "腿部肥大付费指南",
    "Pay for Pullup Training": "支付引体向上训练费用",
    "Pay for Squat Training": "支付臂屈伸训练费用",
    "Pay Romanian Deadlift Training": "付费罗马尼亚硬拉训练",
    "Planned Viral Video": "计划传播的视频",
    "Plug Products": "植入产品",
    "Posing": "摆姿势",
    "Posts Growth:": "帖子增长:",
    "Posts Read:": "帖子阅读:",
    "Posts to go up faster, pre-prestige": "帖子上升速度更快，预声望",
    "Powerful": "强大的",
    "Proficient": "精通",
    "Protein Shakes": "蛋白质奶昔",
    "Purchase Bulk Supplements to Sell": "购买大量补充剂进行销售",
    "Put Ads on Videos": "在视频上投放广告",
    "Put Followers to Work": "让粉丝工作",
    "Put Influencers to Work": "让影响者发挥作用",
    "Put Link to Workout Plan in Bio": "将锻炼计划链接放入 Bio 中",
    "Recruit Influencers": "招募影响者",
    "Recruit Members": "招募会员",
    "Refine Marketing Techniques": "完善营销技巧",
    "Regional Conferences": "区域会议",
    "Research": "研究",
    "Research Bots": "研究机器人",
    "Research Bulking": "研究膨胀",
    "Research Recruiting Influencers": "研究招募影响者",
    "Research:": "研究:",
    "Reset\n                                    Game": "重置\n游戏",
    "Romanian Deadlifts (No Weight)": "罗马尼亚硬拉（无重量）",
    "Running Ad Campaigns": "运行广告活动",
    "Saved": "已保存",
    "Scream Very Loudly in All Workout Videos": "在所有锻炼视频中大声尖叫",
    "Sell Supplements on Channel": "在渠道上销售补充剂",
    "Send Marketing Emails": "发送营销电子邮件",
    "Show Off Body": "炫耀身材",
    "Sleeping Better": "睡得更好",
    "Speedy": "迅速",
    "Street Workout Gangs": "街头健身团队",
    "Study Influencers": "研究影响者",
    "Study Other YouTube Channels": "研究其他 YouTube 频道",
    "Unlock Permanent Leadership": "解锁永久领导力",
    "Untrained": "未经训练",
    "x agility modifier": "x 敏捷修饰语",
    "x endurance\n                                            modifier": "x 耐力\n 修饰语",
    "x intelligence modifier": "x 智力调整值",
    "x strength\n                                            modifier": "x 力量\n 修饰语",
    "A portion is multiplied against 1 for the total number of reps per bar fill.": "将一部分乘以 1，即为每个进度条填充的重复总数。",
    "A portion is multiplied against any stat increase.": "一部分会乘以任何属性的增加。",
    "A portion is multiplied against energy regeneration.": "一部分乘以能量再生。",
    "A portion is multiplied against max energy.": "一部分乘以最大能量。",
    "Each bar fill gives followers and views. Followers generate views, but you always get 1 view per bar fill.": "每个进度条填充都会提供关注者和观点。 关注者会产生观看次数，但每次进度条填充时您始终会获得 1 个观看次数。",
    "Each follower generates views.": "每个关注者都会产生播放量。",
    "Each view generates money.": "每次播放都会产生金钱。",
    "Energy and stat growth is doubled every progression.": "每进展一次，能量和属性都会加倍。",
    "Incline Pushups -> Pushups -> Diamond Pushups -> Pseudo Planche Pushups -> Planche Pushups": "上斜俯卧撑 -> 俯卧撑 -> 钻石俯卧撑 -> 伪平板俯卧撑 -> 平板俯卧撑",
    "The amount of followers gained per bar fill. All stats add a small portion of their total to follower growth.": "每个进度条填充获得的关注者数量。 所有属性都会将其总数的一小部分添加到关注者增长中。",
    ". Let's see if there's anything I can buy in the meantime to get harder better faster stronger. (check workout tab)": "。 让我们看看我是否可以同时购买任何东西来让自己变得更努力、更好、更快、更强。 （点击“锻炼”选项卡）",
    "Each bar fill gives posts and intelligence.": "每次进度条填充都会提供帖子和智力。",
    "Each post generates research.": "每个帖子都会产生研究。",
    "I'll browse Reddit for some insights and fitness information. (check research tab)": "我会浏览 Reddit 以获取一些见解和健身信息。 （点击“研究”选项卡）",
    "It might take a while to become popular": "可能需要一段时间才能流行起来",
    "The number of posts added per bar fill.": "每次进度条填充添加的帖子数。",
    "Why do my followers keep leaving?": "为什么我的粉丝不断离开？",
    "Arch Hangs -> Pullup Negatives -> Pullups -> Assisted One-Arm Pullups -> One-Arm Pullups": "拱门悬挂 -> 上拉负片 -> 引体向上 -> 辅助单臂引体向上 -> 单臂引体向上",
    "Incline Rows -> Horizontal Rows -> Tuck Front Lever Rows -> Advanced Tuck Front Lever Rows -> Front Lever Rows": "倾斜划船 -> 水平划船 -> 前杆划船 -> 高级前杆划船 -> 前杆划船",
    "Support Holds -> Dip Negatives -> Dips -> Ring Dips -> Rings Turned-Out Dips": "支撑保持 -> 臂屈伸负片 -> 臂屈伸 -> 环臂屈伸 -> 环转出臂屈伸",
    "Each bar fill gives influencers.": "每次进度条填充都会产生影响者。",
    "Each influencer generates follower growth.": "每个影响者都会带来粉丝的增长。",
    "Loaded.": "已加载。",
    "Assisted Squat -> Squat -> Split Squat -> Bulgarian Split Squat -> Pistol Squat": "辅助深蹲 -> 深蹲 -> 分腿深蹲 -> 保加利亚分腿深蹲 -> 手枪深蹲",
    "Each bar fill gives bots and intelligence.": "每次进度条填充都提供机器人和智力。",
    "Each bot increases post growth.": "每个机器人都提高帖子增长。",
    "Romanian Deadlifts (No Weight) -> Single-Legged Deadlifts -> Banded Nordic Curl Negatives -> Banded Nordic Curls -> Nordic Curls": "罗马尼亚硬拉（无重量） -> 单腿硬拉 -> 负向北欧带状弯举 -> 北欧带状弯举 -> 北欧弯举",
    "! It's time to fulfill my dream and open a gym. (check Open Gym tab)": "!是时候实现我的梦想，开一家健身房了。 （点击“开设健身房”选项卡）",
    "I'm so rich and strong now": "我现在是如此富有和强大",
    "- A must have for any filthy gym. Double the effectivness of nutritionists.": "- 任何肮脏健身房的必备品。 营养师的效率加倍。",
    "- Ad Coordinators are twice as effective.": "- 广告协调员的效率提高了一倍。",
    "- Adding a new level will make the gym much bigger. Double gym capacity": "- 添加新的关卡将使健身房变得更大。 双倍健身房容量",
    "- Ads are doubled per bar fill.": "- 每填充一个栏，广告就会加倍。",
    "- Also the only coach I've worked with so far. Double energy expenditure of dips and pullups, but double stat gains as well.": "- 也是迄今为止我唯一合作过的教练。 臂屈伸和引体向上的能量消耗加倍，但属性增益也加倍。",
    "- Basic space management. Double gym capacity": "- 基本空间管理。 双倍健身房容量",
    "- Best coach I've ever had, hands down. Double energy expenditure of pushups and rows, but double stat gains as well.": "- 毫无疑问，我遇到过的最好的教练。 俯卧撑和划船的能量消耗加倍，但属性增益也加倍。",
    "- Charge more for classes. Doubles the value of classes on money growth.": "- 课程收费更高。 金钱增长课程的价值加倍。",
    "- Classes can fit more people, so more money. Doubles the effect of each class on money growth.": "- 课程可以容纳更多人，因此可以赚更多钱。 每个类别对金钱增长的影响加倍。",
    "- Coach is really putting me to work. Doubles Squat Speed.": "- 教练真的让我努力工作。 加倍深蹲速度。",
    "- Design is not subjective at all. Doubles the effect of ads on campaign growth.": "- 设计根本不是主观的。 使广告对广告活动增长的影响加倍。",
    "- Double intelligence gain from advertising.": "- 从广告中获得双重情报。",
    "- Doubles gym capacity.": "- 健身房容量增加一倍。",
    "- Efficiency is key. Double your influence generation.": "- 效率是关键。 让你的影响力翻倍。",
    "- Everyone must see each other at all times. Double gym capacity": "- 每个人都必须始终见面。 双倍健身房容量",
    "- Give tours around the facility. Doubles the effectiveness of sales reps.": "- 参观设施周围。 使销售代表的效率加倍。",
    "- Go legit. Doubles members trained per trainer.": "- 合法化。 双打成员由教练员训练。",
    "- How are they monetizing their gyms? Double your money growth.": "- 他们如何通过健身房货币化？ 让你的金钱增长双倍。",
    "- I better be good enough to take over this gym by the end of it. Doubles Romanian Deadlift Speed.": "- 我最好足够优秀，在这家健身房结束时接管它。 罗马尼亚硬拉速度加倍。",
    "- I need to reduce the leg swing and coach is there for me. Halves the energy expenditure of pullups.": "- 我需要减少腿部摆动，教练就在我身边。 将引体向上的能量消耗减半。",
    "- I'm nearly ready to take over this gym. Double energy expenditure of bodyweight leg exercises, but double stat gains as well.": "- 我几乎准备好接管这个健身房了。 自重腿部练习的能量消耗加倍，但属性增益也加倍。",
    "- Improves gym and research based on all stats.": "- 根据所有属性改进健身房和研究。",
    "- It's still worth it to double dip. Doubles dip speed.": "- 双底还是值得的。 臂屈伸速度加倍。",
    "- It's time to get serious about sleep. Double your energy recovery.": "- 是时候认真对待睡眠了。 双倍能量恢复。",
    "- Let's actually vet out some of these people before hiring. Doubles intelligence gain from advertising.": "- 让我们在雇用之前实际审查一下其中一些人。 广告带来的情报收益加倍。",
    "- Let's make even better use of the space we have - no more walls! Double gym capacity": "- 让我们更好地利用我们拥有的空间 - 不再有墙壁！ 双倍健身房容量",
    "- Make members work to get to the next level. Doubles the amount of classes per program coordinator.": "- 让会员努力达到新的水平。 每个项目协调员的课程数量增加一倍。",
    "- Make them all talk to each other. Doubles intelligence gain from advertising.": "- 让他们互相交谈。 广告带来的情报收益加倍。",
    "- Market your gym more effectively to double money gain.": "- 更有效地推销您的健身房，使收入翻倍。",
    "- Marketing managers are twice as effective.": "- 营销经理的效率提高了一倍。",
    "- My coach has big plans for keeping tighter in dips. Halves the energy expenditure of dips.": "- 我的教练有一个宏伟的计划，要在双臂屈伸时保持更紧。 将双臂屈伸的能量消耗减半。",
    "- My coach keeps wanting more money. Doubles pullup speed.": "- 我的教练一直想要更多的钱。 上拉速度加倍。",
    "- My coach wants to show me the correct way to do pushups and rows. Halves the energy expenditure of pushups and rows.": "- 我的教练想向我展示做俯卧撑和划船的正确方法。 将俯卧撑和划船的能量消耗减半。",
    "- No bad comments allowed. Doubles influence generation.": "- 不允许发表任何不好的评论。 双倍影响力的产生。",
    "- Nutritionists create custom eating plans for client. Doubles the effectiveness of nutritionists.": "- 营养师为客户制定定制饮食计划。 使营养师的效率加倍。",
    "- Pay to help recruit more nutritionists. Halves the cost of nutritionists.": "- 付费帮助招募更多营养师。 营养师的费用减半。",
    "- Pay to help recruit more program coordinators. Halves the cost of program coordinators.": "- 付费帮助招募更多项目协调员。 项目协调员的成本减半。",
    "- Pay to help recruit more sales reps. Halves the cost of sales reps.": "- 付费帮助招募更多销售代表。 将销售代表的成本减半。",
    "- Pay to help recruit more trainers. Halves the cost of trainers.": "- 付费帮助招募更多培训师。 培训师费用减半。",
    "- Post some fliers around town. Doubles money growth.": "- 在城镇周围张贴一些传单。 货币增长翻倍。",
    "- Pushup handles should double my protege's pushup speed. That's how physics work.": "- 俯卧撑手柄应该可以使我徒弟的俯卧撑速度加倍。 这就是物理学的原理。",
    "- Sales reps can provide virtual tours. Doubles the effectiveness of sales reps.": "- 销售代表可以提供虚拟参观。 使销售代表的效率加倍。",
    "- Seems reasonable, coach is reselling it. Halves the energy expenditure of bodyweight leg exercises.": "- 看起来很合理，教练正在转售。 将自重腿部练习的能量消耗减半。",
    "- Should have done this long ago. Double gym capacity": "- 早就应该这样做了。 双倍健身房容量",
    "- Sneaky sneaky! Doubles influence generation.": "- 鬼鬼祟祟的！ 双倍影响力的产生。",
    "- Teach everyone the basics. Doubles the stat modifier that applies to gym and advertising (all stats).": "- 教大家基础知识。 将适用于健身房和广告的属性修正值加倍（所有属性）。",
    "- Teach technique. Doubles the stat modifier that applies to gym and advertising (all stats).": "- 传授技术。 将适用于健身房和广告的属性修正值加倍（所有属性）。",
    "- They must get better!. Doubles the effectiveness of trainers.": "- 他们必须变得更好！ 使培训师的效率加倍。",
    "- Trainers will train the advertising folks. Doubles intelligence gain from advertising.": "- 培训师将培训广告人员。 广告带来的情报收益加倍。",
    "- We are one with the economy. Doubles the effectivess of intelligence.": "- 我们与经济合而为一。 使智力的效率加倍。",
    "- Why stop at one? Doubles the time coffee lasts.": "- 为什么停在一个？ 使咖啡的保存时间加倍。",
    "- You can call me Mr. Clean. Doubles the stat modifier that applies to gym and advertising (all stats).": "- 你可以叫我清洁先生。 将适用于健身房和广告的属性修正值加倍（所有属性）。",
    "Advanced Advertising Techniques": "先进的广告技术",
    "Advertising": "广告",
    "Better Classes": "更好的课程",
    "Certifications": "认证证书",
    "Cleaner Facilities": "清洁设施",
    "Cleaning Stations": "清洁站",
    "Cross-Pollinating": "异花授粉",
    "Each ad campaign increases influence per second.": "每个广告活动每秒都会增加影响力。",
    "Each bar fill gives ads and intelligence.": "每次进度条填充都会提供广告和情报。",
    "Each bar fill gives campaigns and intelligence.": "每次进度条填充都提供活动和情报。",
    "Each class increases money per member.": "每个班级都会增加每个成员的金钱。",
    "Each coordinator can create 1 class and speed up creating classes.": "每个协调员可以创建1个班级，加快创建班级的速度。",
    "Each designed ad increases ad campaign growth.": "每个设计的广告都会增加广告活动的增长。",
    "Each member generates money.": "每个成员都会赚钱。",
    "Each member tier earns more money than the one before.": "每个会员级别的收入都比之前的会员级别高。",
    "Each member's money per second is multiplied by this amount.": "每个成员每秒的金钱乘以该金额。",
    "Each trainer can train someone .1 of the way to the next level and speeds up training. All stats add a small portion of their total to member training.": "每个培训师可以培训某人 0.1 到下一个级别并加快培训速度。 所有属性都将其总数的一小部分添加到会员培训中。",
    "Eating Plans": "饮食计划",
    "Economic Fundamentals": "经济基本面",
    "focus": "重点",
    "focused": "专注的",
    "Fundamentals": "基础知识",
    "Hiring Tests": "招聘测试",
    "Host Classes in Different Buildings": "在不同的大楼举办课程",
    "How many ad campaigns you receive per bar fill. Increased by ads designed.": "每条填充时您会收到多少个广告活动。 通过广告设计增加。",
    "I can now train my replacement before opening another franchise location.": "我现在可以在开设另一个特许经营店之前培训我的替代者。",
    "Manager Training": "经理培训",
    "Many Cups of Coffee": "许多杯咖啡",
    "More Classroom Space": "更多教室空间",
    "More Coordination": "更多协调",
    "More Effective Designers": "更高效的设计师",
    "My new gym is open!": "我的新健身房开业了！",
    "Nutritionist Recruiting": "营养师招聘",
    "Open Floor Plan": "开放式平面图",
    "Pay Coach to Teach You": "付费教练教你",
    "Pay for Dip Form Training": "支付 Dip 形式培训费用",
    "Pay for Pullup Form Training": "支付引体向上训练费用",
    "Pay Members to Advertise at Other Gyms": "向会员支付在其他健身房做广告的费用",
    "Post Fliers Around Town": "在城镇周围张贴传单",
    "Program Coordinator Recruiting": "项目协调员招聘",
    "Purge Negative Reviews": "清除负面评论",
    "Rearrange Equipment": "重新排列设备",
    "Remove Walls": "拆除墙壁",
    "Rent Apartments Upstairs in Exchange for Maintenance": "租楼上的公寓以换取维修费",
    "Rent More Space": "租用更多空间",
    "Sales Recruiting": "销售招聘",
    "Second Story": "第二个故事",
    "Setup High Intensity Interval Training Classes": "设置高强度间歇训练课程",
    "Setup Hypertrophy Classes": "设置肥大课程",
    "Sleeping at the Gym": "在健身房睡觉",
    "Slimmer Equipment": "更薄的设备",
    "Socialize Employees": "员工社交",
    "Study the Opposition": "研究反对派",
    "Teach Bulking": "教增肌",
    "Teach High Reps": "教授高次数",
    "Teach Technique": "传授技术",
    "The max gym members (upgradeable).": "最大健身房会员（可升级）。",
    "Tiered Classes": "分级课程",
    "Tours": "旅游",
    "Train the Trainer": "训练实习者",
    "Trainer Recruiting": "培训师招募",
    "Virtual Tours": "虚拟旅游",
    "Work Smarter, Not Harder": "更聪明地工作，而不是更努力地工作",
    "Absorb Gang": "吸收团队",
    "Compete Against Gang": "与团队竞争",
    "Girl Scouts": "女童子军",
    "Members accumulate over time and is affected by the intelligence stat.": "成员会随着时间的推移而积累，并受到智力属性的影响。",
    "Members accumulate over time, faster for more difficult rivals.": "会员随着时间的推移而积累，对于更难对付的对手来说，积累得更快。",
    "Strength * Members": "力量*成员",
    "Strength accumulates over time and is affected by the strength stat": "力量会随着时间的推移而积累，并受到力量属性的影响",
    "Strength accumulates over time, faster for more difficult rivals.": "力量随着时间的推移而积累，对于更难对付的对手来说，积累得更快。",
    "They need to earn their 'gainz' badge": "他们需要赢得“gainz”徽章",
    "Your Gang": "你的团队",
    "Bored Gamers": "无聊的游戏玩家",
    "Lumbering Llamas": "笨重的骆驼",
    "Slow and steady, time under tension": "缓慢而稳定，紧张的时间",
    "They've played it all, and now they're playing a real life incremental game": "他们已经玩完了这一切，现在他们正在玩现实生活中的增量游戏",
    "Failure!": "失败！",
    "Success!": "成功！",
    "Only Bobs need apply": "只有鲍勃需要申请",
    "Every rep is loud and obnoxious": "每个代表都很吵闹且令人讨厌",
    "Screaming Cats": "尖叫的猫",
    "Dream Eaters": "食梦者",
    "Skull Busters": "骷髅克星",
    "Shriveled Prunes": "枯萎的李子",
    "These grannies are deceptively agile": "这些老奶奶看似敏捷",
    "They're so good that they make you question your life choices": "他们是如此优秀以至于让你质疑你的人生选择",
    "You know they're serious when the name is serious": "当名字很严肃的时候你就知道他们是认真的",
    "Each point gives a 2% boost to all gym functions, but only after you buy the bodyweight upgrade. Confidence is permanent and doesn't reset on prestige.": "每一点都会使所有健身房功能提升 2%，但前提是您购买了体重升级。 信心是永久的，不会因声望而重置。",
    "Bootcamp Brides": "新娘训练营",
    "Obvious Onions": "明显的洋葱",
    "Prepare to cry": "准备哭吧",
    "": "",
    "They got in shape for their wedding and they're ready to prove it": "他们为婚礼做好了准备，并准备好证明这一点",
    "Bootcamp Brides": "训练营新娘",
    "Diamond Pushups": "钻石俯卧撑",
    "Dip Negatives": "臂屈伸负片",
    "Pullup Negatives": "上拉负片",
    "Single-Legged Deadlifts": "单腿硬拉",
    "Squat": "深蹲",
    "Tuck Front Lever Rows": "折叠前杆划船",
    "Front Lever Rows": "前杆划船",
    "Nordic Curls": "北欧弯举",
    "One-Arm Pullups": "单臂引体向上",
    "Pistol Squat": "枪式深蹲",
    "Planche Pushups": "普朗什俯卧撑",
    "Rings Turned-Out Dips": "环转出臂屈伸",
    "- Also the only coach I've worked with so far. Double energy expenditure of overhead press and curls, but double stat gains as well.": "- 也是迄今为止我唯一合作过的教练。 过头推举和弯举的能量消耗加倍，但统计数据增益也加倍。",
    "- Best coach I've ever had, hands down. Double energy expenditure of bench and rows, but double stat gains as well.": "- 毫无疑问，我遇到过的最好的教练。 卧推和划船的能量消耗加倍，但统计增益也加倍。",
    "- Better bench technique will let me rep faster. Doubles bench speed.": "- 更好的替补技术会让我跑得更快。 使板凳速度加倍。",
    "- Curls are very hard to do correctly. Halves the energy expenditure of curls.": "- 卷发很难正确做。 将卷发的能量消耗减半。",
    "- Get some grip trainers to practice holding onto the bar better. Doubles row speed.": "- 找一些握力训练器来练习更好地握住杠铃。 行速度加倍。",
    "- Get those massive biceps. Doubles curl speed.": "- 获得那些巨大的二头肌。 卷曲速度加倍。",
    "- I better be good enough to take over this gym by the end of it. Doubles deadlift speed.": "- 我最好足够优秀，在这家健身房结束时接管它。 硬拉速度加倍。",
    "- I'm losing the bar in front of me, and coach is there for me. Halves the energy expenditure of overhead press.": "- 我快要失去面前的杠铃了，而教练就在我身边。 将过头推举的能量消耗减半。",
    "- I'm nearly ready to take over this gym. Double energy expenditure of leg exercises, but double stat gains as well.": "- 我几乎准备好接管这个健身房了。 腿部练习的能量消耗加倍，但统计增益也加倍。",
    "- My coach keeps wanting more money. Doubles overhead press speed.": "- 我的教练一直想要更多的钱。 使过顶压力机速度加倍。",
    "- My coach wants to show me the correct way to do bench and rows. Halves the energy expenditure of bench and rows.": "- 我的教练想向我展示卧推和划船的正确方法。 将卧推和划船的能量消耗减半。",
    "- Seems reasonable, coach is reselling it. Halves the energy expenditure of leg exercises.": "- 看起来很合理，教练正在转售。 将腿部锻炼的能量消耗减半。",
    "Bench Technique": "工作台技术",
    "Better Form for Bench and Rows": "更好的卧推和划船姿势",
    "Better Form for Overhead Press and Curls": "过头推举和弯举的更好形式",
    "Energy and stat growth are multiplied by 1.02 each weight increase.": "每次重量增加，能量和属性增长都会乘以 1.02。",
    "Grip Training": "握力训练",
    "Pay Deadlift Training": "付费硬拉训练",
    "Pay for Curl Form Training": "支付弯举训练费用",
    "Pay for Curl Training": "支付弯举训练费用",
    "Pay for Overhead Press Form Training": "支付高架新闻形式培训费用",
    "Pay for Overhead Press Training": "支付过顶推举训练费用",
	"Wow I'm out of shape!": "呃，抱歉，我好久没锻炼了，身体不好。",
    "I'll do some pushups to get stronger.": "我会做一些俯卧撑来变得更强壮。",
    "I need a break!": "我需要休息一下！",
    "I'm actually so strong now, I should start a YouTube channel! (check work tab)": "我现在变得强壮一些了，我应该开一个YouTube频道！（点击“工作”选项卡）",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Bob Squad": "鲍勃小队",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'VS': 'VS',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如:Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头:"Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑:",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式:",
    "In-line Exponent: ": "直列指数:",
    "Single-Tab Mode: ": "单标签模式:",
    "Time Played: ": "已玩时长:",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示:",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Total Reps:": "总重复次数:",
    "Strength:": "力量:",
    "Endurance:": "耐力:",
    "Energy:": "能量:",
    "Base intelligence: ": "基础智力:",
    "Agility: ": "敏捷:",
    "Squats": "深蹲",
    "Barbell Curls": "杠铃弯举",
    "Barbell Row": "杠铃划船",
    "Bench Press": "卧推",
    "Deadlift": "硬拉",
    "Overhead Press": "过头推举",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如:13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾:" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字:(\d+)
//逗号:([\d\.,]+)
//小数点:([\d\.]+)
//原样输出的字段:(.+)
//换行加空格:\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) of my members left to join them!$/, '$1 我的会员离开并加入了他们！'],
    [/^(.+) of their members joined me!$/, '$1 他们的会员加入了我！'],
    [/^All of the (.+) have joined me now!$/, '所有的 $1 现在都加入了我的行列！'],
    [/^I've gained (.+) confidence and they brought along (.+)! On to the next contender.$/, '我获得了 $1 的信心，他们带来了 $2！ 挑战下一个竞争者。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^coffee gone \- ([\d\.]+)s$/, '咖啡喝完了 \- $1秒'],
    [/^COFFEE ACTIVATED! \- ([\d\.]+)s$/, '咖啡激活了！ \- $1秒'],
    [/^waiting for pay day \- ([\d\.]+)s$/, '等待发薪日 \- $1秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\(([\d\.]+)\/s\)$/, '（$1\/秒）'],
    [/^\(([\d\.]+)e\+([\d\.,]+)\/s\)$/, '（$1e\+$2\/秒）'],
    [/^\$([\d\.]+)\/s$/, '\$ $1\/秒'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) research$/, '成本:$1 研究'],
    [/^Cost: (.+) influence$/, '成本:$1 影响力'],
    [/^Cost: (.+) follower$/, '成本:$1 粉丝'],
    [/^Cost: (.+) followers$/, '成本:$1 粉丝'],
    [/^Cost: (.+) Lifting Point$/, '成本:$1 举重点数'],
    [/^Cost: (.+) Lifting Points$/, '成本:$1 举重点数'],
    [/^Cost: (.+) Bodyweight Point$/, '成本:$1 体重点数'],
    [/^Cost: (.+) Bodyweight Points$/, '成本:$1 体重点数'],
    [/^Cost: (.+) Global Point$/, '成本:$1 全局点数'],
    [/^Cost: (.+) Global Points$/, '成本:$1 全局点数'],
    [/^Cost: (.+) points$/, '成本:$1 点数'],
    [/^Cost: \$([\d\.]+)$/, '成本:\$ $1'],
    [/^Req: (.+) elves$/, '要求:$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求:$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途:$1\/'],
    [/^workers: (\d+)\/$/, '工人:$1\/'],

]);